# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸智云PaaS平台社区版 (BlueKing PaaS Community
Edition) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://opensource.org/licenses/MIT

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""
# Generated by Django 1.11.2 on 2017-09-26 13:51
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(db_index=True, help_text='项目id', max_length=64)),
                ('activity_time', models.DateTimeField(auto_now_add=True)),
                ('activity_type', models.IntegerField(choices=[(0, 'NOTE'), (1, 'ADD'), (2, 'MODIFY'), (3, 'DELETE'), (4, 'BEGIN'), (5, 'END'), (6, 'START'), (7, 'PAUSE'), (8, 'CONTINUE'), (9, 'STOP'), (10, 'RESTART'), (11, 'QUERY')], default=0, help_text='操作类型')),
                ('resource', models.CharField(help_text='操作对象', max_length=32)),
                ('resource_type', models.CharField(help_text='操作对象类型', max_length=32)),
                ('resource_id', models.CharField(help_text='操作对象id', max_length=64)),
                ('activity_status', models.IntegerField(choices=[(0, 'UNKNOWN'), (1, 'COMPLETED'), (2, 'BUSY'), (3, 'SUCCEED'), (4, 'FAILED')], default=0, help_text='操作状态')),
                ('user', models.CharField(help_text='发起者', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UserActivityLogLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_index=True, max_length=32)),
                ('key', models.CharField(db_index=True, max_length=32)),
                ('value', models.TextField()),
                ('activity_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity_log.UserActivityLog')),
            ],
        ),
    ]
