FROM tencentos/tencentos4-minimal

COPY hyper/bcs-cluster-autoscaler-1.16 /bcs-cluster-autoscaler-1.16
COPY hyper/bcs-cluster-autoscaler-1.22 /bcs-cluster-autoscaler-1.22
CMD ["/bcs-cluster-autoscaler-1.22"]
