export default {
    project_create: window.i18n.t('项目创建'),
    project_view: window.i18n.t('项目查看'),
    project_delete: window.i18n.t('项目删除'),
    project_edit: window.i18n.t('项目编辑'),
    cluster_create: window.i18n.t('集群创建'),
    cluster_view: window.i18n.t('集群查看'),
    cluster_manage: window.i18n.t('集群管理'),
    cluster_delete: window.i18n.t('集群删除'),
    templateset_copy: window.i18n.t('模板集复制'),
    templateset_create: window.i18n.t('模板集创建'),
    templateset_view: window.i18n.t('模板集查看'),
    templateset_delete: window.i18n.t('模板集删除'),
    templateset_update: window.i18n.t('模板集更新'),
    templateset_instantiate: window.i18n.t('模板集实例化'),
    namespace_delete: window.i18n.t('命名空间删除'),
    namespace_update: window.i18n.t('命名空间更新'),
    namespace_view: window.i18n.t('命名空间查看'),
    namespace_create: window.i18n.t('命名空间创建'),
    namespace_scoped_view: window.i18n.t('命名空间域查看'),
    namespace_scoped_update: window.i18n.t('命名空间域更新'),
    namespace_scoped_delete: window.i18n.t('命名空间域删除'),
    namespace_scoped_use: window.i18n.t('命名空间域使用')
}
