/*
 * Tencent is pleased to support the open source community by making Blueking Container Service available.
 * Copyright (C) 2019 THL A29 Limited, a Tencent company. All rights reserved.
 * Licensed under the MIT License (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 * http://opensource.org/licenses/MIT
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/Tencent/bk-bcs/bcs-runtime/bcs-k8s/bcs-component/bcs-general-pod-autoscaler/pkg/apis/autoscaling/v1alpha1"
	scheme "github.com/Tencent/bk-bcs/bcs-runtime/bcs-k8s/bcs-component/bcs-general-pod-autoscaler/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// GeneralPodAutoscalersGetter has a method to return a GeneralPodAutoscalerInterface.
// A group's client should implement this interface.
type GeneralPodAutoscalersGetter interface {
	GeneralPodAutoscalers(namespace string) GeneralPodAutoscalerInterface
}

// GeneralPodAutoscalerInterface has methods to work with GeneralPodAutoscaler resources.
type GeneralPodAutoscalerInterface interface {
	Create(ctx context.Context, generalPodAutoscaler *v1alpha1.GeneralPodAutoscaler, opts v1.CreateOptions) (*v1alpha1.GeneralPodAutoscaler, error)
	Update(ctx context.Context, generalPodAutoscaler *v1alpha1.GeneralPodAutoscaler, opts v1.UpdateOptions) (*v1alpha1.GeneralPodAutoscaler, error)
	UpdateStatus(ctx context.Context, generalPodAutoscaler *v1alpha1.GeneralPodAutoscaler, opts v1.UpdateOptions) (*v1alpha1.GeneralPodAutoscaler, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.GeneralPodAutoscaler, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.GeneralPodAutoscalerList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GeneralPodAutoscaler, err error)
	GeneralPodAutoscalerExpansion
}

// generalPodAutoscalers implements GeneralPodAutoscalerInterface
type generalPodAutoscalers struct {
	client rest.Interface
	ns     string
}

// newGeneralPodAutoscalers returns a GeneralPodAutoscalers
func newGeneralPodAutoscalers(c *AutoscalingV1alpha1Client, namespace string) *generalPodAutoscalers {
	return &generalPodAutoscalers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the generalPodAutoscaler, and returns the corresponding generalPodAutoscaler object, and an error if there is any.
func (c *generalPodAutoscalers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.GeneralPodAutoscaler, err error) {
	result = &v1alpha1.GeneralPodAutoscaler{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("generalpodautoscalers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	// NOCC:nakedret/ret(设计如此)
	return
}

// List takes label and field selectors, and returns the list of GeneralPodAutoscalers that match those selectors.
func (c *generalPodAutoscalers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.GeneralPodAutoscalerList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.GeneralPodAutoscalerList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("generalpodautoscalers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	// NOCC:nakedret/ret(设计如此)
	return
}

// Watch returns a watch.Interface that watches the requested generalPodAutoscalers.
func (c *generalPodAutoscalers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("generalpodautoscalers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a generalPodAutoscaler and creates it.  Returns the server's representation of the generalPodAutoscaler, and an error, if there is any.
func (c *generalPodAutoscalers) Create(ctx context.Context, generalPodAutoscaler *v1alpha1.GeneralPodAutoscaler, opts v1.CreateOptions) (result *v1alpha1.GeneralPodAutoscaler, err error) {
	result = &v1alpha1.GeneralPodAutoscaler{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("generalpodautoscalers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(generalPodAutoscaler).
		Do(ctx).
		Into(result)
	// NOCC:nakedret/ret(设计如此)
	return
}

// Update takes the representation of a generalPodAutoscaler and updates it. Returns the server's representation of the generalPodAutoscaler, and an error, if there is any.
func (c *generalPodAutoscalers) Update(ctx context.Context, generalPodAutoscaler *v1alpha1.GeneralPodAutoscaler, opts v1.UpdateOptions) (result *v1alpha1.GeneralPodAutoscaler, err error) {
	result = &v1alpha1.GeneralPodAutoscaler{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("generalpodautoscalers").
		Name(generalPodAutoscaler.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(generalPodAutoscaler).
		Do(ctx).
		Into(result)
	// NOCC:nakedret/ret(设计如此)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *generalPodAutoscalers) UpdateStatus(ctx context.Context, generalPodAutoscaler *v1alpha1.GeneralPodAutoscaler, opts v1.UpdateOptions) (result *v1alpha1.GeneralPodAutoscaler, err error) {
	result = &v1alpha1.GeneralPodAutoscaler{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("generalpodautoscalers").
		Name(generalPodAutoscaler.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(generalPodAutoscaler).
		Do(ctx).
		Into(result)
	// NOCC:nakedret/ret(设计如此)
	return
}

// Delete takes name of the generalPodAutoscaler and deletes it. Returns an error if one occurs.
func (c *generalPodAutoscalers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("generalpodautoscalers").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *generalPodAutoscalers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("generalpodautoscalers").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched generalPodAutoscaler.
func (c *generalPodAutoscalers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GeneralPodAutoscaler, err error) {
	result = &v1alpha1.GeneralPodAutoscaler{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("generalpodautoscalers").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	// NOCC:nakedret/ret(设计如此)
	return
}
