# permissions for end users to edit hostnetportpools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hostnetportpool-editor-role
rules:
- apiGroups:
  - networkextension.bkbcs.tencent.com
  resources:
  - hostnetportpools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networkextension.bkbcs.tencent.com
  resources:
  - hostnetportpools/status
  verbs:
  - get
