{
 "title": "haproxy stats",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "cluster_id", "query": "label_values(cluster_id)" },
   { "name": "loadbalance", "query": "label_values(loadbalance)" },
   { "name": "backend", "query": "label_values(backend)" }
  ]
 },
 "panels": [
  { "title": "Loadbalance Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Loadbalance Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Current Connection",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "loadbalance_haproxy_current_conn{cluster_id=~'$cluster_id', loadbalance=~'$loadbalance'}",
     "legendFormat": "{{loadbalance}}"
    }
   ]
  },
  {
   "title": "Loadbalance Connection Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "loadbalance_haproxy_current_conn_rate{cluster_id=~'$cluster_id', loadbalance=~'$loadbalance'}",
     "legendFormat": "{{}}"
    }
   ]
  },
  {
   "title": "Incoming Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "loadbalance_haproxy_backend_bytes_in{cluster_id=~'${cluster_id}',backend=~'${backend}', loadbalance=~'${loadbalance}'}",
     "legendFormat": "{{loadbalance}} {{backend}}"
    }
   ]
  },
  {
   "title": "Out bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "loadbalance_haproxy_backend_bytes_out{loadbalance=~'$loadbalance', backend=~'$backend'}",
     "legendFormat": "{{loadbalance}} {{backend}}"
    }
   ]
  },
  {
   "title": "Backend Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "loadbalance_haproxy_backend_status{loadbalance=~'$loadbalance', backend=~'$backend'}",
     "legendFormat": "{{loadbalance}} {{backend}}"
    }
   ]
  },
  {
   "title": "Backend Up Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "loadbalance_haproxy_backend_down_time_second{loadbalance=~'$loadbalance', backend=~'$backend'}",
     "legendFormat": "{{loadbalance}} {{backend}}"
    }
   ]
  },
  {
   "title": "Current Session Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "loadbalance_haproxy_server_current_session_rate{loadbalance=~'$loadbalance', backend=~'$backend'}",
     "legendFormat": "{{loadbalance}} {{backend}}"
    }
   ]
  },
  {
   "title": "Max Session Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "loadbalance_haproxy_backend_max_session_rate{loadbalance=~'$loadbalance', backend=~'$backend'}",
     "legendFormat": "{{loadbalance}} {{backend}}"
    }
   ]
  },
  {
   "title": "Backend Current Queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "loadbalance_haproxy_backend_current_queue{loadbalance=~'$loadbalance', backend=~'$backend'}",
     "legendFormat": "{{loadbalance}} {{backend}}"
    }
   ]
  },
  {
   "title": "Backend Max Queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "loadbalance_haproxy_backend_max_queue{loadbalance=~'$loadbalance', backend=~'$backend'}",
     "legendFormat": "{{loadbalance}} {{backend}}"
    }
   ]
  },
  {
   "title": "Session Current",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "loadbalance_haproxy_backend_current_session{loadbalance=~'$loadbalance', backend=~'$backend'}",
     "legendFormat": "{{loadbalance}} {{backend}}"
    }
   ]
  },
  {
   "title": "Session Max",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "loadbalance_haproxy_backend_max_session{loadbalance=~'$loadbalance', backend=~'$backend'}",
     "legendFormat": "{{loadbalance}} {{backend}}"
    }
   ]
  },
  {
   "title": "Session Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "loadbalance_haproxy_backend_session_total{loadbalance=~'$loadbalance', backend=~'$backend'}",
     "legendFormat": "{{loadbalance}} {{backend}}"
    }
   ]
  },
  {
   "title": "Session Limit",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "loadbalance_haproxy_backend_session_limit{loadbalance=~'$loadbalance', backend=~'$backend'}",
     "legendFormat": "{{loadbalance}} {{backend}}"
    }
   ]
  },
  {
   "title": "Denied Request",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "loadbalance_haproxy_backend_request_deny{cluster_id=~'$cluster_id', loadbalance=~'$loadbalance', backend=~'$backend'}",
     "legendFormat": "{{loadbalance}} {{backen d}}"
    }
   ]
  },
  {
   "title": "Denied Response",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "loadbalance_haproxy_backend_response_deny{cluster_id=~'$cluster_id', loadbalance=~'$loadbalance', backend=~'$backend'}",
     "legendFormat": "{{loadbalance}} {{backend}}"
    }
   ]
  },
  {
   "title": "Error Request",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "loadbalance_haproxy_backend_request_error{cluster_id=~'$cluster_id', loadbalance=~'$loadbalance', backend=~'$backend'}",
     "legendFormat": "{{loadbalance}} {{backend}}"
    }
   ]
  },
  {
   "title": "Error Response",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "loadbalance_haproxy_backend_response_error{cluster_id=~'$cluster_id', loadbalance=~'$loadbalance', backend=~'$backend'}",
     "legendFormat": "{{loadbalance}} {{backend}}"
    }
   ]
  },
  {
   "title": "Retry",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "loadbalance_haproxy_backend_connect_retry{cluster_id=~'$cluster_id', loadbalance=~'$loadbalance', backend=~'$backend'}",
     "legendFormat": "{{loadbalance}} {{backend}}"
    }
   ]
  },
  {
   "title": "Redispatch",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "loadbalance_haproxy_backend_connect_redispatch{cluster_id=~'$cluster_id', loadbalance=~'$loadbalance', backend=~'$backend'}",
     "legendFormat": "{{loadbalance}} {{backend}}"
    }
   ]
  },
  {
   "title": "Check Down",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "loadbalance_haproxy_backend_check_down_num{cluster_id=~'$cluster_id', loadbalance=~'$loadbalance', backend=~'$backend'}",
     "legendFormat": "{{loadbalance}} {{backend}}"
    }
   ]
  }
 ]
}