all:
	@cd common && make
	@cd accessserver && make
	@cd businessserver && make
	@cd templateserver && make
	@cd datamanager && make
	@cd bcs-controller && make
	@cd connserver && make
	@cd integrator && make
	@cd sidecar && make

clean:
	@cd common && make clean
	@cd accessserver && make clean
	@cd businessserver && make clean
	@cd templateserver && make clean
	@cd datamanager && make clean
	@cd bcs-controller && make clean
	@cd connserver && make clean
	@cd integrator && make clean
	@cd sidecar && make clean
