all:
	@cd common && make
	@cd apiserver && make
	@cd authserver && make
	@cd templateserver && make
	@cd configserver && make
	@cd tunnelserver && make
	@cd datamanager && make
	@cd gse-controller && make
	@cd connserver && make
	@cd sidecar && make

clean:
	@cd common && make clean
	@cd apiserver && make clean
	@cd authserver && make clean
	@cd templateserver && make clean
	@cd configserver && make clean
	@cd tunnelserver && make clean
	@cd datamanager && make clean
	@cd gse-controller && make clean
	@cd connserver && make clean
	@cd sidecar && make clean
