/*
 * Tencent is pleased to support the open source community by making Blueking Container Service available.
 * Copyright (C) 2019 THL A29 Limited, a Tencent company. All rights reserved.
 * Licensed under the MIT License (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 * http://opensource.org/licenses/MIT
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// DNSEndpointListerExpansion allows custom methods to be added to
// DNSEndpointLister.
type DNSEndpointListerExpansion interface{}

// DNSEndpointNamespaceListerExpansion allows custom methods to be added to
// DNSEndpointNamespaceLister.
type DNSEndpointNamespaceListerExpansion interface{}

// DomainListerExpansion allows custom methods to be added to
// DomainLister.
type DomainListerExpansion interface{}

// DomainNamespaceListerExpansion allows custom methods to be added to
// DomainNamespaceLister.
type DomainNamespaceListerExpansion interface{}

// IngressDNSRecordListerExpansion allows custom methods to be added to
// IngressDNSRecordLister.
type IngressDNSRecordListerExpansion interface{}

// IngressDNSRecordNamespaceListerExpansion allows custom methods to be added to
// IngressDNSRecordNamespaceLister.
type IngressDNSRecordNamespaceListerExpansion interface{}

// ServiceDNSRecordListerExpansion allows custom methods to be added to
// ServiceDNSRecordLister.
type ServiceDNSRecordListerExpansion interface{}

// ServiceDNSRecordNamespaceListerExpansion allows custom methods to be added to
// ServiceDNSRecordNamespaceLister.
type ServiceDNSRecordNamespaceListerExpansion interface{}
