# Generated by Django 3.2.2 on 2022-02-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20200915_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='k8sloadblance',
            name='creator',
            field=models.CharField(max_length=64, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='k8sloadblance',
            name='updator',
            field=models.CharField(max_length=64, verbose_name='修改者'),
        ),
        migrations.AlterField(
            model_name='mesosloadblance',
            name='creator',
            field=models.CharField(max_length=64, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='mesosloadblance',
            name='updator',
            field=models.CharField(max_length=64, verbose_name='修改者'),
        ),
    ]
