{
 "title": "general-pod-autoscaler SLA",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "扩缩容成功率",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(keda_metrics_adapter_gpa_update_duration_count{status=\"success\"})/sum(keda_metrics_adapter_gpa_update_duration_count{})"
    }
   ]
  },
  {
   "title": "扩缩容延迟<250ms",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(keda_metrics_adapter_scaler_exec_duration_bucket{le=\"0.25\",status=\"success\"} or keda_metrics_adapter_gpa_update_duration_bucket{le=\"0.25\",status=\"success\"}) /sum(keda_metrics_adapter_scaler_exec_duration_count{status=\"success\"} or keda_metrics_adapter_gpa_update_duration_count{status=\"success\"})"
    }
   ]
  },
  {
   "title": "scaler执行延迟<250ms",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(keda_metrics_adapter_scaler_exec_duration_bucket{le=\"0.25\"})/sum(keda_metrics_adapter_scaler_exec_duration_count{})"
    }
   ]
  },
  {
   "title": "副本数更新延迟<250ms",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(keda_metrics_adapter_gpa_update_duration_bucket{le=\"0.25\",status=\"success\"})/sum(keda_metrics_adapter_gpa_update_duration_count{status=\"success\"})"
    }
   ]
  }
 ]
}