{
 "title": "user-manager SLA",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "权限和token管理成功率",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_usermanager_api_request_latency_time_count{handler=~\"GrantPermission|GetPermission|RevokePermission|VerifyPermission|VerifyPermissionV2|GetRegisterToken|CreateToken| GetToken|DeleteToken|UpdateToken|CreateTempToken|CreateClientToken|RefreshPlainToken|RefreshSaasToken\",status=\"success\"})/sum(bkbcs_usermanager_api_request_latency_time_count{handler=~\"GrantPermission|GetPermission|RevokePermission|VerifyPermission|VerifyPermissionV2|GetRegisterToken|CreateToken|GetToken|DeleteToken|UpdateToken|CreateTempToken|CreateClientToken|RefreshPlainToken|RefreshSaasToken\"})"
    }
   ]
  },
  {
   "title": "权限管理成功率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_usermanager_api_request_latency_time_count{handler=~\"GrantPermission|GetPermission|RevokePermission|VerifyPermission|VerifyPermissionV2\",status=\"success\"})/sum(bkbcs_usermanager_api_request_latency_time_count{handler=~\"GrantPermission|GetPermission|RevokePermission|VerifyPermission|VerifyPermissionV2\"})"
    }
   ]
  },
  {
   "title": "token管理成功率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_usermanager_api_request_latency_time_count{handler=~\"GetRegisterToken|CreateToken|GetToken|DeleteToken|UpdateToken|CreateTempToken|CreateClientToken|RefreshPlainToken|RefreshSaasToken\",status=\"success\"})/sum(bkbcs_usermanager_api_request_latency_time_count{handler=~\"GetRegisterToken|CreateToken|GetToken|DeleteToken|UpdateToken|CreateTempToken|CreateClientToken|RefreshPlainToken|RefreshSaasToken\"})"
    }
   ]
  },
  {
   "title": "权限和token管理延迟<256ms",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_usermanager_api_request_latency_time_bucket{handler=~\"GrantPermission|GetPermission|RevokePermission|VerifyPermission|VerifyPermissionV2|GetRegisterToken|CreateToken| GetToken|DeleteToken|UpdateToken|CreateTempToken|CreateClientToken|RefreshPlainToken|RefreshSaasToken\",le=\"0.256\",status=\"success\"})/sum(bkbcs_usermanager_api_request_latency_time_count{handler=~\"GrantPermission|GetPermission|RevokePermission|VerifyPermission|VerifyPermissionV2|GetRegisterToken|CreateToken|GetToken|DeleteToken|UpdateToken|CreateTempToken|CreateClientToken|RefreshPlainToken|RefreshSaasToken\",status=\"success\"})"
    }
   ]
  },
  {
   "title": "权限管理延迟<256ms",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_usermanager_api_request_latency_time_bucket{handler=~\"GrantPermission|GetPermission|RevokePermission|VerifyPermission|VerifyPermissionV2\",le=\"0.256\",status=\"success\"})/sum(bkbcs_usermanager_api_request_latency_time_count{handler=~\"GrantPermission|GetPermission|RevokePermission|VerifyPermission|VerifyPermissionV2\",status=\"success\"})"
    }
   ]
  },
  {
   "title": "token管理延迟<256ms",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_usermanager_api_request_latency_time_bucket{handler=~\"GetRegisterToken|CreateToken|GetToken|DeleteToken|UpdateToken|CreateTempToken|CreateClientToken|RefreshPlainToken|RefreshSaasToken\",le=\"0.256\",status=\"success\"})/sum(bkbcs_usermanager_api_request_latency_time_count{handler=~\"GetRegisterToken|CreateToken|GetToken|DeleteToken|UpdateToken|CreateTempToken|CreateClientToken|RefreshPlainToken|RefreshSaasToken\",status=\"success\"})"
    }
   ]
  }
 ]
}