{
 "title": "bcs-k8s-watch",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster_id",
    "query": "label_values(bkbcs_k8swatch_queue_handler_total_num{job=\"bcs-k8s-watch\"},cluster_id)"
   }
  ]
 },
 "panels": [
  { "title": "队列handler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "handler类型队列长度",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_k8swatch_queue_handler_total_num{cluster_id=~\"$cluster_id\", handler!~\"writer_normal_queue|writer_alarm_queue\"}) by(handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "writer队列长度",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_k8swatch_queue_handler_total_num{cluster_id=~\"$cluster_id\", handler=~\"writer_normal_queue|writer_alarm_queue\"}) by(handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "队列丢弃事件(1s阻塞)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_k8swatch_queue_handler_discard_events{cluster_id=~\"$cluster_id\",}) by(handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  { "title": "storage API接口数据", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "storage接口请求数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_k8swatch_storage_request_total_num{cluster_id=~\"$cluster_id\"})",
     "legendFormat": "total_request_num"
    }
   ]
  },
  {
   "title": "storage  API每秒请求数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bkbcs_k8swatch_storage_request_total_num{cluster_id=~\"$cluster_id\"}[5m]))",
     "legendFormat": "request/s"
    }
   ]
  },
  {
   "title": "storageAPI 时延",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_k8swatch_storage_request_latency_time_sum{cluster_id=~\"$cluster_id\"}) / sum(bkbcs_k8swatch_storage_request_latency_time_count{cluster_id=~\"$cluster_id\"})",
     "legendFormat": "lantency"
    }
   ]
  },
  {
   "title": "storage API成功率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_k8swatch_storage_request_total_num{cluster_id=~\"$cluster_id\",status=\"success\"}) / sum(bkbcs_k8swatch_storage_request_total_num{cluster_id=~\"$cluster_id\"})",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "storage 接口维度请求总数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_k8swatch_storage_request_total_num{cluster_id=~\"$cluster_id\"}) by(handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "storage 接口方法维度请求总数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_k8swatch_storage_request_total_num{cluster_id=~\"$cluster_id\"}) by(handler,method)",
     "legendFormat": "{{method}}-{{handler}}"
    }
   ]
  },
  {
   "title": "storage 接口维度时延",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(bkbcs_k8swatch_storage_request_latency_time_sum{cluster_id=~\"$cluster_id\"}) by (handler)) / (sum(bkbcs_k8swatch_storage_request_latency_time_count{cluster_id=~\"$cluster_id\"}) by (handler))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "storage 接口方法维度时延",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(bkbcs_k8swatch_storage_request_latency_time_sum{cluster_id=~\"$cluster_id\"}) by (handler,method)) / (sum(bkbcs_k8swatch_storage_request_latency_time_count{cluster_id=~\"$cluster_id\"}) by (handler,method))",
     "legendFormat": "{{method}}-{{handler}}"
    }
   ]
  },
  {
   "title": "storage 接口维度qps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bkbcs_k8swatch_storage_request_total_num{cluster_id=~\"$cluster_id\"}[5m])) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "storage 接口方法维度qps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bkbcs_k8swatch_storage_request_total_num{cluster_id=~\"$cluster_id\"}[5m])) by (handler,method)",
     "legendFormat": "{{method}}-{{handler}}"
    }
   ]
  },
  {
   "title": "storage 接口维度成功率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_k8swatch_storage_request_total_num{cluster_id=~\"$cluster_id\", status=\"success\"}) by(handler) / sum(bkbcs_k8swatch_storage_request_total_num{cluster_id=~\"$cluster_id\"}) by(handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "storage 接口方法维度成功率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_k8swatch_storage_request_total_num{cluster_id=~\"$cluster_id\",status=\"success\"}) by(handler,method) / sum(bkbcs_k8swatch_storage_request_total_num{cluster_id=~\"$cluster_id\"}) by(handler,method)",
     "legendFormat": "{{method}}-{{handler}}"
    }
   ]
  },
  {
   "title": "请求类型总量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_k8swatch_storage_request_total_num{status=\"susuccess\"}) by (method)"
    },
    {
     "expr": "sum(bkbcs_k8swatch_storage_request_total_num{cluster_id=~\"$cluster_id\", status!=\"susuccess\"}) by (method)"
    }
   ]
  },
  {
   "title": "接口请求频率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(bkbcs_k8swatch_storage_request_total_num{cluster_id=~\"$cluster_id\",}[5m])) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "url 接口请求总量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_k8swatch_storage_request_total_num{cluster_id=~\"$cluster_id\",status!=\"success\"}) by (handler)",
     "legendFormat": "failure-{{handler}}"
    },
    {
     "expr": "sum(bkbcs_k8swatch_storage_request_total_num{cluster_id=~\"$cluster_id\",status=\"success\"}) by (handler)",
     "legendFormat": "success-{{handler}}"
    }
   ]
  },
  {
   "title": "请求类型每秒请求数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(bkbcs_k8swatch_storage_request_total_num{cluster_id=~\"$cluster_id\",status=\"susuccess\"}[5m])) by (method)"
    },
    {
     "expr": "sum(irate(bkbcs_k8swatch_storage_request_total_num{cluster_id=~\"$cluster_id\",status!=\"susuccess\"}[5m])) by (method)"
    }
   ]
  }
 ]
}