{
 "title": "bcs-webconsole",
 "time": { "from": "2022-03-24T17:45:50.182Z", "to": "2022-03-25T17:45:50.182Z" },
 "panels": [
  { "title": "API接口维度指标聚合", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "接口维度时延",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "(sum(bkbcs_webconsole_api_request_latency_time_sum) by (handler))/(sum(bkbcs_webconsole_api_request_total_num) by (handler))"
    }
   ]
  },
  {
   "title": "接口维度请求总数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(bkbcs_webconsole_api_request_total_num{}) by(handler)"
    }
   ]
  },
  {
   "title": "接口维度qps",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(bkbcs_webconsole_api_request_total_num[5m])) by (handler)"
    }
   ]
  },
  {
   "title": "接口维度成功率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_webconsole_api_request_total_num{status=\"success\"}) by(handler,method) / sum(bkbcs_webconsole_api_request_total_num) by(handler,method)"
    }
   ]
  },
  { "title": "API接口方法维度指标聚合", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "接口方法维度请求总数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(bkbcs_webconsole_api_request_total_num{}) by(handler,method)"
    }
   ]
  },
  {
   "title": "接口方法维度qps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum(rate(bkbcs_webconsole_api_request_total_num[5m])) by (handler,method)"
    }
   ]
  },
  {
   "title": "接口方法维度时延",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "(sum(bkbcs_webconsole_api_request_latency_time_sum) by (handler,method)) / (sum(bkbcs_webconsole_api_request_total_num) by (handler,method))"
    }
   ]
  },
  {
   "title": "接口方法维度成功率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "sum(bkbcs_webconsole_api_request_total_num{status=\"success\"}) by(handler,method) / sum(bkbcs_webconsole_api_request_total_num) by(handler,method)"
    }
   ]
  },
  { "title": "pod维度指标聚合", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "创建pod成功率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "sum(bkbcs_webconsole_pod_create_total_num{status=\"success\"})/sum(bkbcs_webconsole_pod_create_total_num{})"
    }
   ]
  },
  {
   "title": "存活pod数量",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_webconsole_pod_create_total_num{status=\"success\"})-sum(bkbcs_webconsole_pod_delete_total_num{status=\"success\"})"
    }
   ]
  },
  {
   "title": "pod 创建成功耗时(s)分布",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "sum(bkbcs_webconsole_pod_create_duration_seconds_bucket{status=\"success\"}) by(le)"
    }
   ]
  },
  {
   "title": "pod 创建失败耗时(s)分布",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "expr": "sum(bkbcs_webconsole_pod_create_duration_seconds_bucket{status=\"failure\"}) by(le)"
    }
   ]
  },
  {
   "title": "pod 删除成功耗时(s)分布",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "sum(bkbcs_webconsole_pod_create_duration_seconds_bucket{status=\"failure\"}) by(le)"
    }
   ]
  },
  {
   "title": "pod 删除失败耗时(s)分布",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "targets": [
    {
     "expr": "sum(bkbcs_webconsole_pod_create_duration_seconds_bucket{status=\"failure\"}) by(le)"
    }
   ]
  },
  {
   "title": "pod创建耗时极值情况",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "max(bkbcs_webconsole_pod_create_duration_seconds_max) by(status)"
    },
    {
     "expr": "min(bkbcs_webconsole_pod_create_duration_seconds_min) by(status)"
    }
   ]
  },
  {
   "title": "pod删除耗时极值情况",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "targets": [
    {
     "expr": "max(bkbcs_webconsole_pod_delete_duration_seconds_max) by(status)"
    },
    {
     "expr": "min(bkbcs_webconsole_pod_delete_duration_seconds_min) by(status) "
    }
   ]
  },
  { "title": "ws连接维度指标聚合", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "websocket连接次数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 99 },
   "targets": [
    {
     "expr": "sum(bkbcs_webconsole_ws_connection_total_num) by(namespace,name)"
    }
   ]
  },
  {
   "title": "ws 连接延时",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 107 },
   "targets": [
    {
     "expr": "(sum(bkbcs_webconsole_ws_connection_duration_seconds_bucket) by (namespace, name)) / sum(bkbcs_webconsole_ws_connection_total_num) by(name,namespace)"
    }
   ]
  },
  {
   "title": "当前ws连接数量",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 107 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_webconsole_ws_connection_total_num) - sum(bkbcs_webconsole_ws_close_total_num)"
    }
   ]
  }
 ]
}