{
 "title": "GameWorkload / GameDeployment",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster_id",
    "query": "label_values(bkbcs_gamedeployment_reconcile_duration_seconds_sum{}, cluster_id)"
   },
   {
    "name": "namespace",
    "query": "label_values(bkbcs_gamedeployment_reconcile_duration_seconds_sum{}, gd)"
   },
   {
    "name": "gamedeployment",
    "query": "label_values(bkbcs_gamedeployment_reconcile_duration_seconds_sum{}, gd)"
   }
  ]
 },
 "panels": [
  { "title": "Pod 监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "各状态副本数量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bkbcs_gamedeployment_replicas{cluster_id=\"$cluster_id\",gd=\"$namespace/$gamedeployment\"}",
     "legendFormat": "Desired Replicas"
    },
    {
     "expr": "bkbcs_gamedeployment_ready_replicas{cluster_id=\"$cluster_id\",gd=\"$namespace/$gamedeployment\"}",
     "legendFormat": "Ready Replicas"
    },
    {
     "expr": "bkbcs_gamedeployment_current_replicas{cluster_id=\"$cluster_id\",gd=\"$namespace/$gamedeployment\"}",
     "legendFormat": "Current Replicas"
    },
    {
     "expr": "bkbcs_gamedeployment_updated_replicas{cluster_id=\"$cluster_id\",gd=\"$namespace/$gamedeployment\"}",
     "legendFormat": "Updated Replicas"
    },
    {
     "expr": "bkbcs_gamedeployment_updated_ready_replicas{cluster_id=\"$cluster_id\",gd=\"$namespace/$gamedeployment\"}",
     "legendFormat": "Updated Ready Replicas"
    }
   ]
  },
  {
   "title": "Pod 创建情况",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bkbcs_gamedeployment_pod_create_duration_seconds_count{status=\"success\",cluster_id=\"$cluster_id\",gd=\"$namespace/$gamedeployment\"}",
     "legendFormat": "成功总次数"
    },
    {
     "expr": "bkbcs_gamedeployment_pod_create_duration_seconds_count{status=\"failure\",cluster_id=\"$cluster_id\",gd=\"$namespace/$gamedeployment\"}",
     "legendFormat": "失败总次数"
    }
   ]
  },
  {
   "title": "Pod 创建时间分布",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "bkbcs_gamedeployment_pod_create_duration_seconds_bucket{cluster_id=\"$cluster_id\",status=\"success\",gd=\"$namespace/$gamedeployment\",le=\"0.001\"}",
     "legendFormat": "0.001 s"
    },
    {
     "expr": "bkbcs_gamedeployment_pod_create_duration_seconds_bucket{cluster_id=\"$cluster_id\",status=\"success\",gd=\"$namespace/$gamedeployment\",le=\"0.01\"} - bkbcs_gamedeployment_pod_create_duration_seconds_bucket{cluster_id=\"$cluster_id\",status=\"success\",gd=\"$namespace/$gamedeployment\",le=\"0.001\"}",
     "legendFormat": "0.01 s"
    },
    {
     "expr": "bkbcs_gamedeployment_pod_create_duration_seconds_bucket{cluster_id=\"$cluster_id\",status=\"success\",gd=\"$namespace/$gamedeployment\",le=\"0.1\"} - ignoring (le) bkbcs_gamedeployment_pod_create_duration_seconds_bucket{cluster_id=\"$cluster_id\",status=\"success\",gd=\"$namespace/$gamedeployment\",le=\"0.01\"} ",
     "legendFormat": "0.1 s"
    },
    {
     "expr": "bkbcs_gamedeployment_pod_create_duration_seconds_bucket{cluster_id=\"$cluster_id\",status=\"success\",gd=\"$namespace/$gamedeployment\",le=\"0.5\"} - ignoring (le) bkbcs_gamedeployment_pod_create_duration_seconds_bucket{cluster_id=\"$cluster_id\",status=\"success\",gd=\"$namespace/$gamedeployment\",le=\"0.1\"} ",
     "legendFormat": "0.5 s"
    },
    {
     "expr": "bkbcs_gamedeployment_pod_create_duration_seconds_bucket{cluster_id=\"$cluster_id\",status=\"success\",gd=\"$namespace/$gamedeployment\",le=\"1\"} - ignoring (le) bkbcs_gamedeployment_pod_create_duration_seconds_bucket{cluster_id=\"$cluster_id\",status=\"success\",gd=\"$namespace/$gamedeployment\",le=\"0.5\"} ",
     "legendFormat": "1 s"
    },
    {
     "expr": "bkbcs_gamedeployment_pod_create_duration_seconds_bucket{cluster_id=\"$cluster_id\",status=\"success\",gd=\"$namespace/$gamedeployment\",le=\"+inf\"} - ignoring (le) bkbcs_gamedeployment_pod_create_duration_seconds_bucket{cluster_id=\"$cluster_id\",status=\"success\",gd=\"$namespace/$gamedeployment\",le=\"1\"} ",
     "legendFormat": "+inf s"
    }
   ]
  },
  {
   "title": "Pod 更新情况",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bkbcs_gamedeployment_pod_update_duration_seconds_count{status=\"success\",cluster_id=\"$cluster_id\",gd=\"$namespace/$gamedeployment\"}",
     "legendFormat": "成功总次数"
    },
    {
     "expr": "bkbcs_gamedeployment_pod_update_duration_seconds_count{status=\"failure\",cluster_id=\"$cluster_id\",gd=\"$namespace/$gamedeployment\"}",
     "legendFormat": "失败总次数"
    }
   ]
  },
  {
   "title": "Pod 更新时间分布",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "bkbcs_gamedeployment_pod_update_duration_seconds_bucket{cluster_id=\"$cluster_id\",status=\"success\",gd=\"$namespace/$gamedeployment\",le=\"0.001\"}",
     "legendFormat": "0.001 s"
    },
    {
     "expr": "bkbcs_gamedeployment_pod_update_duration_seconds_bucket{cluster_id=\"$cluster_id\",status=\"success\",gd=\"$namespace/$gamedeployment\",le=\"0.01\"} - bkbcs_gamedeployment_pod_update_duration_seconds_bucket{cluster_id=\"$cluster_id\",status=\"success\",gd=\"$namespace/$gamedeployment\",le=\"0.001\"}",
     "legendFormat": "0.01 s"
    },
    {
     "expr": "bkbcs_gamedeployment_pod_update_duration_seconds_bucket{cluster_id=\"$cluster_id\",status=\"success\",gd=\"$namespace/$gamedeployment\",le=\"0.1\"} - ignoring (le) bkbcs_gamedeployment_pod_update_duration_seconds_bucket{cluster_id=\"$cluster_id\",status=\"success\",gd=\"$namespace/$gamedeployment\",le=\"0.01\"} ",
     "legendFormat": "0.1 s"
    },
    {
     "expr": "bkbcs_gamedeployment_pod_update_duration_seconds_bucket{cluster_id=\"$cluster_id\",status=\"success\",gd=\"$namespace/$gamedeployment\",le=\"0.5\"} - ignoring (le) bkbcs_gamedeployment_pod_update_duration_seconds_bucket{cluster_id=\"$cluster_id\",status=\"success\",gd=\"$namespace/$gamedeployment\",le=\"0.1\"} ",
     "legendFormat": "0.5 s"
    },
    {
     "expr": "bkbcs_gamedeployment_pod_update_duration_seconds_bucket{cluster_id=\"$cluster_id\",status=\"success\",gd=\"$namespace/$gamedeployment\",le=\"1\"} - ignoring (le) bkbcs_gamedeployment_pod_update_duration_seconds_bucket{cluster_id=\"$cluster_id\",status=\"success\",gd=\"$namespace/$gamedeployment\",le=\"0.5\"} ",
     "legendFormat": "1 s"
    },
    {
     "expr": "bkbcs_gamedeployment_pod_update_duration_seconds_bucket{cluster_id=\"$cluster_id\",status=\"success\",gd=\"$namespace/$gamedeployment\",le=\"+inf\"} - ignoring (le) bkbcs_gamedeployment_pod_update_duration_seconds_bucket{cluster_id=\"$cluster_id\",status=\"success\",gd=\"$namespace/$gamedeployment\",le=\"1\"} ",
     "legendFormat": "+inf s"
    }
   ]
  },
  {
   "title": "Pod 删除情况",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bkbcs_gamedeployment_pod_delete_duration_seconds_count{status=\"success\",cluster_id=\"$cluster_id\",gd=\"$namespace/$gamedeployment\"}",
     "legendFormat": "成功总次数"
    },
    {
     "expr": "bkbcs_gamedeployment_pod_delete_duration_seconds_count{status=\"failure\",cluster_id=\"$cluster_id\",gd=\"$namespace/$gamedeployment\"}",
     "legendFormat": "失败总次数"
    }
   ]
  },
  {
   "title": "Pod 删除时间分布",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "bkbcs_gamedeployment_pod_delete_duration_seconds_bucket{cluster_id=\"$cluster_id\",status=\"success\",gd=\"$namespace/$gamedeployment\",le=\"0.001\"}",
     "legendFormat": "0.001 s"
    },
    {
     "expr": "bkbcs_gamedeployment_pod_delete_duration_seconds_bucket{cluster_id=\"$cluster_id\",status=\"success\",gd=\"$namespace/$gamedeployment\",le=\"0.01\"} - bkbcs_gamedeployment_pod_delete_duration_seconds_bucket{cluster_id=\"$cluster_id\",status=\"success\",gd=\"$namespace/$gamedeployment\",le=\"0.001\"}",
     "legendFormat": "0.01 s"
    },
    {
     "expr": "bkbcs_gamedeployment_pod_delete_duration_seconds_bucket{cluster_id=\"$cluster_id\",status=\"success\",gd=\"$namespace/$gamedeployment\",le=\"0.1\"} - ignoring (le) bkbcs_gamedeployment_pod_delete_duration_seconds_bucket{cluster_id=\"$cluster_id\",status=\"success\",gd=\"$namespace/$gamedeployment\",le=\"0.01\"} ",
     "legendFormat": "0.1 s"
    },
    {
     "expr": "bkbcs_gamedeployment_pod_delete_duration_seconds_bucket{cluster_id=\"$cluster_id\",status=\"success\",gd=\"$namespace/$gamedeployment\",le=\"0.5\"} - ignoring (le) bkbcs_gamedeployment_pod_delete_duration_seconds_bucket{cluster_id=\"$cluster_id\",status=\"success\",gd=\"$namespace/$gamedeployment\",le=\"0.1\"} ",
     "legendFormat": "0.5 s"
    },
    {
     "expr": "bkbcs_gamedeployment_pod_delete_duration_seconds_bucket{cluster_id=\"$cluster_id\",status=\"success\",gd=\"$namespace/$gamedeployment\",le=\"1\"} - ignoring (le) bkbcs_gamedeployment_pod_delete_duration_seconds_bucket{cluster_id=\"$cluster_id\",status=\"success\",gd=\"$namespace/$gamedeployment\",le=\"0.5\"} ",
     "legendFormat": "1 s"
    },
    {
     "expr": "bkbcs_gamedeployment_pod_delete_duration_seconds_bucket{cluster_id=\"$cluster_id\",status=\"success\",gd=\"$namespace/$gamedeployment\",le=\"+inf\"} - ignoring (le) bkbcs_gamedeployment_pod_delete_duration_seconds_bucket{cluster_id=\"$cluster_id\",status=\"success\",gd=\"$namespace/$gamedeployment\",le=\"1\"} ",
     "legendFormat": "+inf s"
    }
   ]
  },
  { "title": "HookRun 监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "现存 hookrun 情况",
   "type": "graph",
   "description": "1 表示该 hookrun 正在运行，由于 Prometheus 的抓取间隔为 30s，因此 hookrun 运行时间小于 30s 的将在此 panel 中被忽略",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(delta(bkbcs_hook_hookrun_survive_time_seconds{cluster_id=\"$cluster_id\",exported_namespace=\"$namespace\",owner=\"GameDeployment|$gamedeployment\"}[1m]) / 60 > 0)"
    }
   ]
  },
  {
   "title": "hookrun 调谐次数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bkbcs_hook_hookrun_exec_duration_seconds_count{status=\"success\",cluster_id=\"$cluster_id\",exported_namespace=\"$namespace\",owner=\"GameDeployment|$gamedeployment\"}",
     "legendFormat": "成功总次数"
    },
    {
     "expr": "bkbcs_hook_hookrun_exec_duration_seconds_count{status=\"failure\",cluster_id=\"$cluster_id\",exported_namespace=\"$namespace\",owner=\"GameDeployment|$gamedeployment\"}",
     "legendFormat": "失败总次数"
    }
   ]
  },
  {
   "title": "hookrun 运行成功耗时分布",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "(count(bkbcs_hook_hookrun_survive_time_seconds{cluster_id=\"$cluster_id\",exported_namespace=\"$namespace\",owner=\"GameDeployment|$gamedeployment\",phase=\"Successful\"} < 30) or vector(0))",
     "legendFormat": "0~30s"
    },
    {
     "expr": "(count(bkbcs_hook_hookrun_survive_time_seconds{cluster_id=\"$cluster_id\",exported_namespace=\"$namespace\",owner=\"GameDeployment|$gamedeployment\",phase=\"Successful\"} < 60) or vector(0))- (count(bkbcs_hook_hookrun_survive_time_seconds{cluster_id=\"$cluster_id\",exported_namespace=\"$namespace\",owner=\"GameDeployment|$gamedeployment\",phase=\"Successful\"} < 30) or vector(0))",
     "legendFormat": "30~60s"
    },
    {
     "expr": "(count(bkbcs_hook_hookrun_survive_time_seconds{cluster_id=\"$cluster_id\",exported_namespace=\"$namespace\",owner=\"GameDeployment|$gamedeployment\",phase=\"Successful\"} < 300) or vector(0)) - (count(bkbcs_hook_hookrun_survive_time_seconds{cluster_id=\"$cluster_id\",exported_namespace=\"$namespace\",owner=\"GameDeployment|$gamedeployment\",phase=\"Successful\"} < 60) or vector(0))",
     "legendFormat": "60~300s"
    },
    {
     "expr": "(count(bkbcs_hook_hookrun_survive_time_seconds{cluster_id=\"$cluster_id\",exported_namespace=\"$namespace\",owner=\"GameDeployment|$gamedeployment\",phase=\"Successful\"} < 600) or vector(0)) - (count(bkbcs_hook_hookrun_survive_time_seconds{cluster_id=\"$cluster_id\",exported_namespace=\"$namespace\",owner=\"GameDeployment|$gamedeployment\",phase=\"Successful\"} < 300) or vector(0))",
     "legendFormat": "300~600s"
    },
    {
     "expr": "(count(bkbcs_hook_hookrun_survive_time_seconds{cluster_id=\"$cluster_id\",exported_namespace=\"$namespace\",owner=\"GameDeployment|$gamedeployment\",phase=\"Successful\"} >= 600) or vector(0))",
     "legendFormat": ">600s"
    }
   ]
  },
  { "title": "Operator 调谐监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Operator 调谐情况",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bkbcs_gamedeployment_reconcile_duration_seconds_count{status=\"success\",cluster_id=\"$cluster_id\",gd=\"$namespace/$gamedeployment\"}",
     "legendFormat": "成功总次数"
    },
    {
     "expr": "bkbcs_gamedeployment_reconcile_duration_seconds_count{status=\"failure\",cluster_id=\"$cluster_id\",gd=\"$namespace/$gamedeployment\"}",
     "legendFormat": "失败总次数"
    }
   ]
  },
  {
   "title": "Operator 调谐时间分布",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "bkbcs_gamedeployment_reconcile_duration_seconds_bucket{cluster_id=\"$cluster_id\",status=\"success\",gd=\"$namespace/$gamedeployment\",le=\"0.001\"}",
     "legendFormat": "0.001 s"
    },
    {
     "expr": "bkbcs_gamedeployment_reconcile_duration_seconds_bucket{cluster_id=\"$cluster_id\",status=\"success\",gd=\"$namespace/$gamedeployment\",le=\"0.01\"} - bkbcs_gamedeployment_reconcile_duration_seconds_bucket{cluster_id=\"$cluster_id\",status=\"success\",gd=\"$namespace/$gamedeployment\",le=\"0.001\"}",
     "legendFormat": "0.01 s"
    },
    {
     "expr": "bkbcs_gamedeployment_reconcile_duration_seconds_bucket{cluster_id=\"$cluster_id\",status=\"success\",gd=\"$namespace/$gamedeployment\",le=\"0.1\"} - ignoring (le) bkbcs_gamedeployment_reconcile_duration_seconds_bucket{cluster_id=\"$cluster_id\",status=\"success\",gd=\"$namespace/$gamedeployment\",le=\"0.01\"} ",
     "legendFormat": "0.1 s"
    },
    {
     "expr": "bkbcs_gamedeployment_reconcile_duration_seconds_bucket{cluster_id=\"$cluster_id\",status=\"success\",gd=\"$namespace/$gamedeployment\",le=\"0.5\"} - ignoring (le) bkbcs_gamedeployment_reconcile_duration_seconds_bucket{cluster_id=\"$cluster_id\",status=\"success\",gd=\"$namespace/$gamedeployment\",le=\"0.1\"} ",
     "legendFormat": "0.5 s"
    },
    {
     "expr": "bkbcs_gamedeployment_reconcile_duration_seconds_bucket{cluster_id=\"$cluster_id\",status=\"success\",gd=\"$namespace/$gamedeployment\",le=\"1\"} - ignoring (le) bkbcs_gamedeployment_reconcile_duration_seconds_bucket{cluster_id=\"$cluster_id\",status=\"success\",gd=\"$namespace/$gamedeployment\",le=\"0.5\"} ",
     "legendFormat": "1 s"
    },
    {
     "expr": "bkbcs_gamedeployment_reconcile_duration_seconds_bucket{cluster_id=\"$cluster_id\",status=\"success\",gd=\"$namespace/$gamedeployment\",le=\"+inf\"} - ignoring (le) bkbcs_gamedeployment_reconcile_duration_seconds_bucket{cluster_id=\"$cluster_id\",status=\"success\",gd=\"$namespace/$gamedeployment\",le=\"1\"} ",
     "legendFormat": "+inf s"
    }
   ]
  }
 ]
}