{
 "title": "bcs-user-manager",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster_id",
    "query": "label_values(bkbcs_usermanager_api_request_total_num{job=\"bcs-user-manager\"},cluster_id)"
   },
   {
    "name": "instance",
    "query": "label_values(bkbcs_usermanager_api_request_total_num{cluster_id=\"$cluster_id\", job=\"bcs-user-manager\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "usermanager接口维度请求总数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_usermanager_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by(handler,instance)"
    }
   ]
  },
  {
   "title": "usermanager接口方法维度请求总数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_usermanager_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by(handler,method, instance)"
    }
   ]
  },
  {
   "title": "usermanager接口维度qps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bkbcs_usermanager_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}[5m])) by (handler, instance)"
    },
    {
     "expr": "sum(irate(bkbcs_usermanager_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}[5m])) by (handler, instance)"
    }
   ]
  },
  {
   "title": "usermanager接口方法维度qps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bkbcs_usermanager_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}[5m])) by (handler, method, instance)"
    },
    {
     "expr": "sum(irate(bkbcs_usermanager_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}[5m])) by (handler, method, instance)"
    }
   ]
  },
  {
   "title": "usermanager接口维度时延",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum(bkbcs_usermanager_api_request_latency_time_sum{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by (handler, instance)) / (sum(bkbcs_usermanager_api_request_latency_time_count{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by (handler, instance))"
    }
   ]
  },
  {
   "title": "usermanager接口方法维度时延",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum(bkbcs_usermanager_api_request_latency_time_sum{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by (handler, method, instance)) / (sum(bkbcs_usermanager_api_request_latency_time_count{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by (handler, method, instance))"
    }
   ]
  },
  {
   "title": "usermanager接口维度成功率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_usermanager_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\",status=\"success\"}) by(handler,instance) / sum(bkbcs_usermanager_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by(handler, instance)"
    }
   ]
  },
  {
   "title": "usermanager接口方法维度成功率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_usermanager_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\",status=\"success\"}) by(handler, method, instance) / sum(bkbcs_usermanager_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by(handler, method, instance)"
    }
   ]
  }
 ]
}