{
 "title": "bcs-hook-operator",
 "time": { "from": "2021-12-10T05:34:01.462Z", "to": "2021-12-11T04:31:46.034Z" },
 "templating": {
  "list": [
   {
    "name": "cluster_id",
    "query": "label_values(bkbcs_hook_reconcile_duration_seconds_count{}, cluster_id)"
   }
  ]
 },
 "panels": [
  { "title": "hook controller调协情况", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "调协成功总次数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_hook_reconcile_duration_seconds_count{status=\"success\"})"
    }
   ]
  },
  {
   "title": "调协失败总次数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_hook_reconcile_duration_seconds_count{status=\"failure\"})"
    }
   ]
  },
  {
   "title": "调协成功耗时(s)分布",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(bkbcs_hook_reconcile_duration_seconds_bucket{status=\"success\"}) by(le)",
     "legendFormat": "le={{le}}"
    }
   ]
  },
  {
   "title": "调协失败耗时(s)分布",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "bkbcs_hook_reconcile_duration_seconds_bucket{status=\"failure\"}",
     "legendFormat": "le={{le}}"
    }
   ]
  },
  {
   "title": "调协成功耗时top10的ownerRef",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(bkbcs_hook_reconcile_duration_seconds_sum{status=\"success\"}) by(namespace, owner)/sum(bkbcs_hook_reconcile_duration_seconds_count{status=\"success\"}) by(namespace, owner))",
     "legendFormat": "{{namespace}}/{{owner}}"
    }
   ]
  },
  {
   "title": "调协失败耗时top10的ownerRef",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(bkbcs_hook_reconcile_duration_seconds_sum{status=\"failure\"}) by(namespace, owner)/sum(bkbcs_hook_reconcile_duration_seconds_count{status=\"failure\"}) by(namespace, owner))",
     "legendFormat": "{{namespace}}/{{owner}}"
    }
   ]
  },
  {
   "title": "各ownerRef调协成功次数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_hook_reconcile_duration_seconds_count{status=\"success\"}) by(namespace, owner)",
     "legendFormat": "{{namespace}}/{{owner}}"
    }
   ]
  },
  {
   "title": "各ownerRef调协失败次数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_hook_reconcile_duration_seconds_count{status=\"failure\"}) by(namespace, owner)",
     "legendFormat": "{{namespace}}/{{owner}}"
    }
   ]
  },
  { "title": "hookrun执行情况", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "hookrun执行成功总次数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_hook_hookrun_exec_duration_seconds_count{status=\"success\"})"
    }
   ]
  },
  {
   "title": "hookrun执行失败总次数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_hook_hookrun_exec_duration_seconds_count{status=\"failure\"})"
    }
   ]
  },
  {
   "title": "hookrun执行成功耗时(s)分布",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum(bkbcs_hook_hookrun_exec_duration_seconds_bucket{status=\"success\"}) by(le)",
     "legendFormat": "le={{le}}"
    }
   ]
  },
  {
   "title": "hookrun执行失败耗时(s)分布",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum(bkbcs_hook_hookrun_exec_duration_seconds_bucket{status=\"failure\"}) by(le)",
     "legendFormat": "le={{le}}"
    }
   ]
  },
  {
   "title": "hookrun执行成功耗时top10的ownerRef",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(bkbcs_hook_hookrun_exec_duration_seconds_sum{status=\"success\"}) by(namespace, owner)/sum(bkbcs_hook_hookrun_exec_duration_seconds_count{status=\"success\"}) by(namespace, owner))",
     "legendFormat": "{{namespace}}/{{owner}}"
    }
   ]
  },
  {
   "title": "hookrun执行失败耗时top10的ownerRef",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(bkbcs_hook_hookrun_exec_duration_seconds_sum{status=\"failure\"}) by(namespace, owner)/sum(bkbcs_hook_hookrun_exec_duration_seconds_count{status=\"failure\"}) by(namespace, owner))",
     "legendFormat": "{{namespace}}/{{owner}}"
    }
   ]
  },
  {
   "title": "各ownerRef调协成功次数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_hook_hookrun_exec_duration_seconds_count{status=\"success\"}) by(namespace, owner)",
     "legendFormat": "{{namespace}}/{{owner}}"
    }
   ]
  },
  {
   "title": "各ownerRef调协失败次数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_hook_hookrun_exec_duration_seconds_count{status=\"failure\"}) by(namespace, owner)",
     "legendFormat": "{{namespace}}/{{owner}}"
    }
   ]
  },
  {
   "title": "正在运行的hookrun存活时间",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "bkbcs_hook_hookrun_survive_time_seconds{phase=\"Running\"}",
     "legendFormat": "{{namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "hookrun执行耗时极值情况",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(bkbcs_hook_hookrun_exec_duration_seconds_max) by(status)",
     "legendFormat": "{{status}}_max"
    },
    {
     "expr": "min(bkbcs_hook_hookrun_exec_duration_seconds_max) by(status)",
     "legendFormat": "{{status}}_min"
    }
   ]
  },
  {
   "title": "hookrun下的metric任务执行情况",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "collapsed": true,
   "panels": [
    {
     "title": "hookrun下的metric任务执行成功总次数",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 39 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(bkbcs_hook_metric_exec_duration_seconds_count{phase=\"Successful\"})"
      }
     ]
    },
    {
     "title": "hookrun下的metric任务执行失败总次数",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 39 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(bkbcs_hook_metric_exec_duration_seconds_count{phase=~\"Error|Failed\"} )"
      }
     ]
    },
    {
     "title": "hookrun下的metric任务执行成功耗时(s)分布",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(bkbcs_hook_metric_exec_duration_seconds_bucket{phase=\"Successful\"}) by(le)",
       "legendFormat": "le={{le}}"
      }
     ]
    },
    {
     "title": "hookrun下的metric任务执行失败耗时(s)分布",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(bkbcs_hook_metric_exec_duration_seconds_bucket{phase=~\"Error|Failed\"}) by(le)",
       "legendFormat": "le={{le}}"
      }
     ]
    },
    {
     "title": "hookrun下的metric任务执行成功耗时top10的metric",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk(10, sum(bkbcs_hook_metric_exec_duration_seconds_sum{phase=\"Successful\"}) by(namespace, owner, metric)/sum(bkbcs_hook_metric_exec_duration_seconds_count{phase=\"Successful\"}) by(namespace, owner, metric))",
       "legendFormat": "{{namespace}}/{{owner}}:{{metric}}"
      }
     ]
    },
    {
     "title": "hookrun下的metric任务执行失败耗时top10的metric",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk(10, sum(bkbcs_hook_metric_exec_duration_seconds_sum{phase=~\"Error|Failed\"}) by(namespace, owner, metric)/sum(bkbcs_hook_metric_exec_duration_seconds_count{phase=~\"Error|Failed\"}) by(namespace, owner, metric))",
       "legendFormat": "{{namespace}}/{{owner}}:{{metric}}"
      }
     ]
    },
    {
     "title": "各metric执行成功次数",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(bkbcs_hook_metric_exec_duration_seconds_count{phase=\"Successful\"}) by(namespace, owner, metric)",
       "legendFormat": "{{namespace}}/{{owner}}:{{metric}}"
      }
     ]
    },
    {
     "title": "各metric执行失败次数",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(bkbcs_hook_metric_exec_duration_seconds_count{phase=~\"Error|Failed\"}) by(namespace, owner, metric)",
       "legendFormat": "{{namespace}}/{{owner}}:{{metric}}"
      }
     ]
    },
    {
     "title": "hookrun下的metric任务执行耗时极值情况",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max(bkbcs_hook_metric_exec_duration_seconds_max) by(phase)",
       "legendFormat": "{{phase}}_max"
      },
      {
       "expr": "min(bkbcs_hook_metric_exec_duration_seconds_min) by(phase)",
       "legendFormat": "{{phase}}_min"
      }
     ]
    }
   ]
  }
 ]
}