{
 "title": "GPA Dashboard",
 "time": { "from": "now-2m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(keda_metrics_adapter_scaler_target_metrics_value{namespace=~\".*\"},namespace)"
   },
   {
    "name": "name",
    "query": "label_values({__name__ =~ \"keda_metrics_adapter_scaler_target_metrics_value|keda_metrics_adapter_scaler_errors\", namespace=~\"$namespace\"},name)\n"
   },
   {
    "name": "scaledObject",
    "query": "label_values(keda_metrics_adapter_scaler_target_metrics_value{namespace=~\"$namespace\",name=~\"$name\",scaledObject=~\".*\"},scaledObject)"
   },
   {
    "name": "instance",
    "query": "label_values(keda_metrics_adapter_scaler_errors_total,instance)"
   },
   {
    "name": "endpoint",
    "query": "label_values(keda_metrics_adapter_scaler_errors_total{endpoint=~\".*\"},endpoint)"
   }
  ]
 },
 "panels": [
  { "title": "报错相关", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "3分钟报错率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(keda_metrics_adapter_scaler_errors_total{instance=~\"$instance\"}[3m]) "
    }
   ]
  },
  {
   "title": "GPA获取metric报错总数",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "keda_metrics_adapter_scaler_errors_total{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "被缩放对象的报错数量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "keda_metrics_adapter_scaled_object_errors{namespace=~\"$namespace\",name=~\"$name\",instance=~\"$instance\"}",
     "legendFormat": "{{scaledObject}}"
    }
   ]
  },
  { "title": "副本数、CPU & memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "GPA副本数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "keda_metrics_adapter_scaler_desired_replicas_value{namespace=~\"$namespace\",name=~\"$name\",instance=~\"$instance\"}",
     "legendFormat": "scalerDesired - {{namespace}}/{{name}}"
    },
    {
     "expr": "keda_metrics_adapter_gpa_max_replicas_value{namespace=~\"$namespace\",name=~\"$name\",instance=~\"$instance\"}",
     "legendFormat": "Max - {{namespace}}/{{name}}"
    },
    {
     "expr": "keda_metrics_adapter_gpa_min_replicas_value{namespace=~\"$namespace\",name=~\"$name\",instance=~\"$instance\"}",
     "legendFormat": "Min - {{namespace}}/{{name}}"
    },
    {
     "expr": "keda_metrics_adapter_gpa_desired_replicas_value{namespace=~\"$namespace\",name=~\"$name\",instance=~\"$instance\"}",
     "legendFormat": "gpaDesired - {{namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "memory指标",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "keda_metrics_adapter_scaler_current_metrics_value{namespace=~\"$namespace\",name=~\"$name\",metric=\"memory\",instance=~\"$instance\"}",
     "legendFormat": "Current - {{namespace}}/{{name}}"
    },
    {
     "expr": "keda_metrics_adapter_scaler_target_metrics_value{namespace=~\"$namespace\",name=~\"$name\",metric=\"memory\",instance=~\"$instance\"}",
     "legendFormat": "Target - {{namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "CPU指标",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "CPU使用率" }
   ],
   "targets": [
    {
     "expr": "keda_metrics_adapter_scaler_current_metrics_value{namespace=~\"$namespace\",name=~\"$name\",metric=\"cpu\",instance=~\"$instance\"}",
     "legendFormat": "current - {{namespace}}/{{name}}"
    },
    {
     "expr": "keda_metrics_adapter_scaler_target_metrics_value{namespace=~\"$namespace\",name=~\"$name\",metric=\"cpu\",instance=~\"$instance\"}",
     "legendFormat": "target - {{namespace}}/{{name}}"
    }
   ]
  }
 ]
}