{
 "title": "BCS Cluster Autoscaler",
 "description": "Super simple dashboard showing an overview of kubernetes cluster autoscaling activity and status, using metrics reported by the autoscaler to prometheus.\r\n\r\nhttps://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler",
 "tags": [ "prometheus" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster_id",
    "label": "cluster_id",
    "query": "label_values(cluster_autoscaler_nodes_count, cluster_id)"
   },
   {
    "name": "node_group",
    "label": "node_group",
    "query": "label_values(cluster_autoscaler_node_group_max_count, node_group)"
   }
  ]
 },
 "panels": [
  { "title": "节点池状态", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "节点池状态",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cluster_autoscaler_node_group_max_count{cluster_id=\"$cluster_id\",node_group=\"$node_group\"}",
     "legendFormat": "最大节点数"
    },
    {
     "expr": "cluster_autoscaler_node_group_min_count{cluster_id=\"$cluster_id\",node_group=\"$node_group\"}",
     "legendFormat": "最小节点数"
    },
    {
     "expr": "cluster_autoscaler_node_group_current_count{cluster_id=\"$cluster_id\",node_group=\"$node_group\"}",
     "legendFormat": "期望节点数"
    },
    {
     "expr": "cluster_autoscaler_node_group_upcoming_count{cluster_id=\"$cluster_id\",node_group=\"$node_group\"}",
     "legendFormat": "过渡状态节点数"
    }
   ]
  },
  { "title": "集群状态", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "节点总数",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_nodes_count{cluster_id=\"$cluster_id\"})\n"
    }
   ]
  },
  {
   "title": "节点可用比例",
   "type": "singlestat",
   "description": "Shows the nodes which are ready as a percent of the total nodes",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 10 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_nodes_count{state=\"ready\",cluster_id=\"$cluster_id\"})/sum(cluster_autoscaler_nodes_count{cluster_id=\"$cluster_id\"})*100"
    }
   ]
  },
  {
   "title": "集群是否可安全扩缩?",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_cluster_safe_to_autoscale{cluster_id=\"$cluster_id\"})"
    }
   ]
  },
  {
   "title": "不可调度 pod 数量",
   "type": "singlestat",
   "description": "Tells you if there are unscheduled pods",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_unschedulable_pods_count{cluster_id=\"$cluster_id\"})",
     "legendFormat": " pods"
    }
   ]
  },
  {
   "title": "Pod 状态",
   "type": "graph",
   "description": "Shows the evicted and unscheduled pods",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none", "label": "Num Nodes" }
   ],
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_evicted_pods_total{cluster_id=\"$cluster_id\"})",
     "legendFormat": "evicted pods"
    },
    {
     "expr": "sum(cluster_autoscaler_unschedulable_pods_count{cluster_id=\"$cluster_id\"})",
     "legendFormat": "unscheduled pods"
    }
   ]
  },
  {
   "title": "节点状态",
   "type": "graph",
   "description": "Shows the state of the nodes as scaling happens",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "none", "label": "Num Nodes" }
   ],
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_nodes_count{state=\"ready\",cluster_id=\"$cluster_id\"})",
     "legendFormat": "ready"
    },
    {
     "expr": "sum(cluster_autoscaler_nodes_count{state=\"unready\",cluster_id=\"$cluster_id\"})",
     "legendFormat": "unready"
    },
    {
     "expr": "sum(cluster_autoscaler_nodes_count{state=\"notStarted\",cluster_id=\"$cluster_id\"})\n",
     "legendFormat": "not started"
    }
   ]
  },
  { "title": "CA 控制器状态", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "最近一次扩容判断",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 22 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(time()-cluster_autoscaler_last_activity{activity=\"scaleUp\",cluster_id=\"$cluster_id\"})"
    }
   ]
  },
  {
   "title": "最近一次缩容判断",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 22 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(time()-cluster_autoscaler_last_activity{activity=\"scaleDown\",cluster_id=\"$cluster_id\"})"
    }
   ]
  },
  {
   "title": "CA 最近一次活动时间",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 22 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(time()-cluster_autoscaler_last_activity{activity=\"autoscaling\",cluster_id=\"$cluster_id\"})"
    }
   ]
  },
  {
   "title": "最近一次扩缩方向",
   "type": "singlestat",
   "description": "Is the cluster scaling up, down or ticking along okay?",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cluster_autoscaler_scaled_up_nodes_total)-sum(cluster_autoscaler_scaled_down_nodes_total{cluster_id=\"$cluster_id\"})"
    }
   ]
  },
  {
   "title": "扩缩容活动",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "none", "label": "Num nodes" }
   ],
   "targets": [
    {
     "expr": "irate(cluster_autoscaler_scaled_up_nodes_total{cluster_id=\"$cluster_id\"}[1m]) * 30",
     "legendFormat": "扩容节点数"
    },
    {
     "expr": "sum(cluster_autoscaler_unneeded_nodes_count{cluster_id=\"$cluster_id\"})",
     "legendFormat": "unneeded 节点数"
    },
    {
     "expr": "sum(cluster_autoscaler_nodes_count{cluster_id=\"$cluster_id\"})\n",
     "legendFormat": "集群节点数"
    }
   ]
  },
  {
   "title": "扩缩容事件",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum_over_time(kube_event_count{cluster_id=\"$cluster_id\",source=\"/cluster-autoscaler\"}[$__range])"
    }
   ]
  },
  {
   "title": "节点不可缩容原因",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "repeat": "node_group",
   "targets": [
    {
     "expr": "sum_over_time(cluster_autoscaler_unremovable_nodes{cluster_id=\"$cluster_id\"}[$__range])"
    }
   ]
  }
 ]
}