{
 "title": "GameDeployment SLA",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(bkbcs_gamedeployment_reconcile_duration_seconds_count, namespace)"
   },
   {
    "name": "name",
    "query": "label_values(bkbcs_gamedeployment_reconcile_duration_seconds_count{namespace=~\"$namespace\"}, name)"
   }
  ]
 },
 "panels": [
  { "title": "创建/删除GameDeployment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GamestatefulSet变更成功率",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_gamedeployment_pod_create_duration_seconds_count{status=\"success\"} or bkbcs_gamedeployment_pod_delete_duration_seconds_count{action=\"deletePod\",status=\"success\"})/sum(bkbcs_gamedeployment_pod_create_duration_seconds_count{} or  bkbcs_gamedeployment_pod_delete_duration_seconds_count{action=\"deletePod\"})",
     "legendFormat": "{{namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "创建Pod成功率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_gamedeployment_pod_create_duration_seconds_count{status=\"success\",namespace=~\"$namespace\",name=~\"$name\"}) by (namespace,name)/sum(bkbcs_gamedeployment_pod_create_duration_seconds_count{namespace=~\"$namespace\",name=~\"$name\"}) by (namespace,name)",
     "legendFormat": " {{namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "删除Pod成功率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_gamedeployment_pod_delete_duration_seconds_count{action=\"deletePod\",status=\"success\",namespace=~\"$namespace\",name=~\"$name\"}) by (namespace,name)/ sum(bkbcs_gamedeployment_pod_delete_duration_seconds_count{action=\"deletePod\",namespace=~\"$namespace\",name=~\"$name\"}) by (namespace,name)",
     "legendFormat": "{{namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "GamestatefulSet变更生效时间<10s",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_gamedeployment_pod_create_duration_seconds_bucket{status=\"success\",le=\"10\"} or bkbcs_gamedeployment_pod_delete_duration_seconds_bucket{action=\"deletePod\",status=\"success\",le=\"10\"}) /sum(bkbcs_gamedeployment_pod_create_duration_seconds_count{} or bkbcs_gamedeployment_pod_delete_duration_seconds_count{action=\"deletePod\"})",
     "legendFormat": "{{namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "创建pod生效时间<10s",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_gamedeployment_pod_create_duration_seconds_bucket{status=\"success\",namespace=~\"$namespace\",name=~\"$name\",le=\"10\"}) by (namespace,name)/sum(bkbcs_gamedeployment_pod_create_duration_seconds_count{namespace=~\"$namespace\",name=~\"$name\"}) by (namespace,name) ",
     "legendFormat": "{{namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "删除pod生效时间<10s",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_gamedeployment_pod_delete_duration_seconds_bucket{action=\"deletePod\",status=\"success\",namespace=~\"$namespace\",name=~\"$name\",le=\"10\"}) by (namespace,name)/sum(bkbcs_gamedeployment_pod_delete_duration_seconds_count{action=\"deletePod\",status=\"success\",namespace=~\"$namespace\",name=~\"$name\"}) by (namespace,name)",
     "legendFormat": "{{namespace}}/{{name}}"
    }
   ]
  },
  { "title": "原地更新", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "原地更新的成功率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_gamedeployment_pod_update_duration_seconds_count{status=\"success\",action=\"inplaceUpdate\"})/sum(bkbcs_gamedeployment_pod_update_duration_seconds_count{action=\"inplaceUpdate\"})",
     "legendFormat": "{{namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "容器被kill或create的成功率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(bkbcs_gamedeployment_pod_update_duration_seconds_count{status=\"success\",namespace=~\"$namespace\",name=~\"$name\",action=\"inplaceUpdate\"}) by (namespace,name))/(sum(bkbcs_gamedeployment_pod_update_duration_seconds_count{action=\"inplaceUpdate\"}) by (namespace,name))",
     "legendFormat": "{{namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "更新对象的生效时间<10s",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_gamedeployment_pod_update_duration_seconds_bucket{status=\"success\",action=\"inplaceUpdate\",le=\"10\"})/sum(bkbcs_gamedeployment_pod_update_duration_seconds_count{status=\"success\",action=\"inplaceUpdate\"})",
     "legendFormat": "{{namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "容器被kill或create的延迟<10s",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(bkbcs_gamedeployment_pod_update_duration_seconds_bucket{status=\"success\",namespace=~\"$namespace\",name=~\"$name\",action=\"inplaceUpdate\",le=\"10\"}) by (namespace,name))/(sum(bkbcs_gamedeployment_pod_update_duration_seconds_count{status=\"success\",namespace=~\"$namespace\",name=~\"$name\",action=\"inplaceUpdate\"}) by (namespace,name))",
     "legendFormat": "{{namespace}}/{{name}}"
    }
   ]
  },
  { "title": "Pod优雅删除/更新", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "优雅删除或更新的成功率",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_gamedeployment_pod_delete_duration_seconds_count{action=\"rollingUpdate\",grace=\"true\",status=\"success\"} or bkbcs_gamedeployment_pod_update_duration_seconds_count{action=\"inplaceUpdate\",grace=\"true\",status=\"success\"} or bkbcs_gameworkload_hookrun_create_duration_seconds_count{status=\"success\",objectKind=\"GameDeployment\"})/ sum(bkbcs_gamedeployment_pod_delete_duration_seconds_count{action=\"rollingUpdate\",grace=\"true\"} or bkbcs_gamedeployment_pod_update_duration_seconds_count{action=\"inplaceUpdate\",grace=\"true\"} or bkbcs_gameworkload_hookrun_create_duration_seconds_count{objectKind=\"GameDeployment\"})",
     "legendFormat": "{{namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "hookrun创建成功率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_gameworkload_hookrun_create_duration_seconds_count{status=\"success\",namespace=~\"$namespace\",name=~\"$name\",action=~\"predelete|preinplace\",objectKind=\"GameDeployment\"}) by (namespace,name)/ sum(bkbcs_gameworkload_hookrun_create_duration_seconds_count{namespace=~\"$namespace\",name=~\"$name\",objectKind=\"GameDeployment\"}) by (namespace,name)",
     "legendFormat": "{{namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "优雅删除pod的成功率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_gamedeployment_pod_delete_duration_seconds_count{grace=\"true\",status=\"success\",namespace=~\"$namespace\",name=~\"$name\"}) by (namespace,name)/ sum(bkbcs_gamedeployment_pod_delete_duration_seconds_count{grace=\"true\",namespace=~\"$namespace\",name=~\"$name\"}) by (namespace,name)",
     "legendFormat": " {{namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "优雅更新容器重建的成功率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_gamedeployment_pod_update_duration_seconds_count{grace=\"true\",status=\"success\",namespace=~\"$namespace\",name=~\"$name\"}) by (namespace,name)/ sum(bkbcs_gamedeployment_pod_update_duration_seconds_count{grace=\"true\",namespace=~\"$namespace\",name=~\"$name\"}) by (namespace,name)",
     "legendFormat": "{{namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "优雅删除或更新的延迟<10s",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_gamedeployment_pod_delete_duration_seconds_bucket{grace=\"true\",status=\"success\",le=\"10\"} or bkbcs_gamedeployment_pod_update_duration_seconds_bucket{action=\"inplaceUpdate\",grace=\"true\",status=\"success\",le=\"10\"} or bkbcs_gameworkload_hookrun_create_duration_seconds_bucket{action=~\"preinplace|predelete\",status=\"success\",le=\"10\",objectKind=\"GameDeployment\"})/ sum(bkbcs_gamedeployment_pod_delete_duration_seconds_count{grace=\"true\"} or bkbcs_gamedeployment_pod_update_duration_seconds_count{action=\"inplaceUpdate\",grace=\"true\"} or bkbcs_gameworkload_hookrun_create_duration_seconds_count{action=~\"preinplace|predelete\",objectKind=\"GameDeployment\"})",
     "legendFormat": " {{namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "hookrun创建的延迟<10s",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_gameworkload_hookrun_create_duration_seconds_bucket{action=~\"preinplace|predelete\",status=\"success\",namespace=~\"$namespace\",name=~\"$name\",le=\"10\",objectKind=\"GameDeployment\"}) by (namespace,name)/ sum(bkbcs_gameworkload_hookrun_create_duration_seconds_count{action=~\"preinplace|predelete\",namespace=~\"$namespace\",name=~\"$name\",objectKind=\"GameDeployment\"}) by (namespace,name)",
     "legendFormat": " {{namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "删除pod的延迟<10s",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_gamedeployment_pod_delete_duration_seconds_bucket{grace=\"true\",status=\"success\",namespace=~\"$namespace\",name=~\"$name\",le=\"10\"}) by (namespace,name) / sum(bkbcs_gamedeployment_pod_delete_duration_seconds_count{grace=\"true\",namespace=~\"$namespace\",name=~\"$name\"}) by (namespace,name)",
     "legendFormat": " {{namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "容器重建的延迟<10s",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_gamedeployment_pod_update_duration_seconds_bucket{action=\"inplaceUpdate\",grace=\"true\",status=\"success\",namespace=~\"$namespace\",name=~\"$name\",le=\"10\"}) by (namespace,name)/ sum(bkbcs_gamedeployment_pod_update_duration_seconds_count{action=\"inplaceUpdate\",grace=\"true\",namespace=~\"$namespace\",name=~\"$name\"}) by (namespace,name)",
     "legendFormat": " {{namespace}}/{{name}}"
    }
   ]
  }
 ]
}