{
 "title": "GameStatefulSet SLA",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "创建/删除GameStatefulSet", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GamestatefulSet变更成功率",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_gamestatefulset_pod_create_duration_seconds_count{status=\"success\"} or bkbcs_gamestatefulset_pod_delete_duration_seconds_count{action=\"deletePod\",status=\"success\"})/sum(bkbcs_gamestatefulset_pod_create_duration_seconds_count{} or  bkbcs_gamestatefulset_pod_delete_duration_seconds_count{action=\"deletePod\"})"
    }
   ]
  },
  {
   "title": "创建Pod成功率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_gamestatefulset_pod_create_duration_seconds_count{status=\"success\"})/sum(bkbcs_gamestatefulset_pod_create_duration_seconds_count{})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "删除Pod成功率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_gamestatefulset_pod_delete_duration_seconds_count{action=\"deletePod\",status=\"success\"})/sum(bkbcs_gamestatefulset_pod_delete_duration_seconds_count{action=\"deletePod\"})"
    }
   ]
  },
  {
   "title": "GamestatefulSet变更生效时间<10s",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_gamestatefulset_pod_create_duration_seconds_bucket{status=\"success\",le=\"10\"} or bkbcs_gamestatefulset_pod_delete_duration_seconds_bucket{action=\"deletePod\",status=\"success\",le=\"10\"}) /sum(bkbcs_gamestatefulset_pod_create_duration_seconds_count{} or bkbcs_gamestatefulset_pod_delete_duration_seconds_count{action=\"deletePod\"})"
    }
   ]
  },
  {
   "title": "创建pod生效时间<10s",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_gamestatefulset_pod_create_duration_seconds_bucket{status=\"success\",le=\"10\"})/sum(bkbcs_gamestatefulset_pod_create_duration_seconds_count{})"
    }
   ]
  },
  {
   "title": "删除pod生效时间<10s",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_gamestatefulset_pod_delete_duration_seconds_bucket{action=\"deletePod\",status=\"success\",le=\"10\"})/sum(bkbcs_gamestatefulset_pod_delete_duration_seconds_count{action=\"deletePod\",status=\"success\"})"
    }
   ]
  },
  { "title": "原地更新", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "原地更新的成功率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_gamestatefulset_pod_update_duration_seconds_count{status=\"success\",action=\"inplaceUpdate\"})/sum(bkbcs_gamestatefulset_pod_update_duration_seconds_count{action=\"inplaceUpdate\"})"
    }
   ]
  },
  {
   "title": "更新对象的生效时间<10s",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_gamestatefulset_pod_update_duration_seconds_bucket{status=\"success\",action=\"inplaceUpdate\",le=\"10\"})/sum(bkbcs_gamestatefulset_pod_update_duration_seconds_count{status=\"success\",action=\"inplaceUpdate\"})"
    }
   ]
  },
  { "title": "Pod优雅删除/更新", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "优雅删除或更新的成功率",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_gamestatefulset_pod_delete_duration_seconds_count{action=\"rollingUpdate\",grace=\"true\",status=\"success\"} or bkbcs_gamestatefulset_pod_update_duration_seconds_count{action=\"inplaceUpdate\",grace=\"true\",status=\"success\"} or bkbcs_gamestatefulset_hookrun_create_duration_seconds_count{status=\"success\",objectKind=\"GameStatefulSet\"})/ sum(bkbcs_gamestatefulset_pod_delete_duration_seconds_count{action=\"rollingUpdate\",grace=\"true\"} or bkbcs_gamestatefulset_pod_update_duration_seconds_count{action=\"inplaceUpdate\",grace=\"true\"} or bkbcs_gamestatefulset_hookrun_create_duration_seconds_count{objectKind=\"GameStatefulSet\"})"
    }
   ]
  },
  {
   "title": "hookrun创建成功率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_gameworkload_hookrun_create_duration_seconds_count{status=\"success\",action=~\"predelete|preinplace\",objectKind=\"GameStatefulSet\"})/ sum(bkbcs_gameworkload_hookrun_create_duration_seconds_count{objectKind=\"GameStatefulSet\"})"
    }
   ]
  },
  {
   "title": "优雅删除pod的成功率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_gamestatefulset_pod_delete_duration_seconds_count{grace=\"true\",status=\"success\"})/ sum(bkbcs_gamestatefulset_pod_delete_duration_seconds_count{grace=\"true\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "优雅更新容器重建的成功率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_gamestatefulset_pod_update_duration_seconds_count{grace=\"true\",status=\"success\"})/sum(bkbcs_gamestatefulset_pod_update_duration_seconds_count{grace=\"true\"})"
    }
   ]
  },
  {
   "title": "优雅删除或更新的延迟<10s",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_gamestatefulset_pod_delete_duration_seconds_bucket{grace=\"true\",status=\"success\",le=\"10\"} or bkbcs_gamestatefulset_pod_update_duration_seconds_bucket{action=\"inplaceUpdate\",grace=\"true\",status=\"success\",le=\"10\"} or bkbcs_gamestatefulset_hookrun_create_duration_seconds_bucket{action=~\"preinplace|predelete\",status=\"success\",le=\"10\",objectKind=\"GameStatefulSet\"})/ sum(bkbcs_gamestatefulset_pod_delete_duration_seconds_count{grace=\"true\"} or bkbcs_gamestatefulset_pod_update_duration_seconds_count{action=\"inplaceUpdate\",grace=\"true\"} or bkbcs_gamestatefulset_hookrun_create_duration_seconds_count{action=~\"preinplace|predelete\",objectKind=\"GameStatefulSet\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "hookrun创建的延迟<10s",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_gameworkload_hookrun_create_duration_seconds_bucket{action=~\"preinplace|predelete\",status=\"success\",le=\"10\",objectKind=\"GameStatefulSet\"})/sum(bkbcs_gameworkload_hookrun_create_duration_seconds_count{action=~\"preinplace|predelete\",objectKind=\"GameStatefulSet\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "删除pod的延迟<10s",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_gamestatefulset_pod_delete_duration_seconds_bucket{grace=\"true\",status=\"success\",le=\"10\"})/sum(bkbcs_gamestatefulset_pod_delete_duration_seconds_count{grace=\"true\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "容器重建的延迟<10s",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_gamestatefulset_pod_update_duration_seconds_bucket{action=\"inplaceUpdate\",grace=\"true\",status=\"success\",le=\"10\"})/sum(bkbcs_gamestatefulset_pod_update_duration_seconds_count{action=\"inplaceUpdate\",grace=\"true\"})",
     "legendFormat": " "
    }
   ]
  }
 ]
}