{
 "title": "bcs-k8s-custom-scheduler",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster_id",
    "query": "label_values(bkbcs_k8scustomscheduler_api_request_total_num{job=\"bcs-k8s-custom-scheduler\"},cluster_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "可访问node数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_k8s_customscheduler_filter_node_total_num{cluster_id=~\"cluster_id\"}) by(version, scheduler)"
    }
   ]
  },
  {
   "title": "接口维度时延",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(bkbcs_k8scustomscheduler_api_request_latency_time_sum{cluster_id=~\"$cluster_id\"}) by (version, handler)) / (sum(bkbcs_k8scustomscheduler_api_request_latency_time_count{cluster_id=~\"$cluster_id\"}) by (version, handler))"
    }
   ]
  },
  {
   "title": "接口维度请求总数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_k8scustomscheduler_api_request_total_num{cluster_id=~\"cluster_id\"}) by(version, handler)"
    }
   ]
  },
  {
   "title": "接口维度成功率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_k8scustomscheduler_api_request_total_num{cluster_id=~\"$cluster_id\", status=\"success\"}) by(version, handler) / sum(bkbcs_k8scustomscheduler_api_request_total_num{cluster_id=~\"$cluster_id\"}) by(version, handler)"
    }
   ]
  },
  {
   "title": "接口维度qps",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bkbcs_k8scustomscheduler_api_request_total_num{cluster_id=~\"$cluster_id\"}[5m])) by (version, handler)",
     "legendFormat": "rate-{{version}}-{{handler}}"
    },
    {
     "expr": "sum(irate(bkbcs_k8scustomscheduler_api_request_total_num{cluster_id=~\"$cluster_id\"}[5m])) by (version, handler)",
     "legendFormat": "irate-{{version}}-{{handler}}"
    }
   ]
  }
 ]
}