{
 "title": "bcs-alert-manager",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster_id",
    "query": "label_values(bkbcs_alertmanager_lib_request_total_num{job=\"bcs-alert-manager\"},cluster_id)"
   },
   {
    "name": "instance",
    "query": "label_values(bkbcs_alertmanager_lib_request_total_num{cluster_id=\"$cluster_id\", job=\"bcs-alert-manager\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "handler队列长度",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_alertmanager_handler_queue_total_num{cluster_id=~\"$cluster_id\",instance=~\"$instance\"}) by(instance, handler)",
     "legendFormat": "{{handler}}-{{instance}}"
    }
   ]
  },
  {
   "title": "instance实例event事件处理平均时延",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum(bkbcs_alertmanager_handler_request_latency_time_sum{cluster_id=~\"$cluster_id\",instance=~\"$instance\"}) by(instance, handler, name, status)) / (sum(bkbcs_alertmanager_handler_request_latency_time_count{cluster_id=~\"$cluster_id\",instance=~\"$instance\"}) by(instance, handler, name, status))"
    }
   ]
  },
  {
   "title": "alertmanager接口维度请求总数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_alertmanager_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by(handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "alertmanager接口方法维度请求总数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_alertmanager_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by(handler, method)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "alertmanager接口维度qps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bkbcs_alertmanager_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}[5m])) by (handler)",
     "legendFormat": "rate-{{handler}}"
    },
    {
     "expr": "sum(irate(bkbcs_alertmanager_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}[5m])) by (handler)",
     "legendFormat": "irate-{{handler}}"
    }
   ]
  },
  {
   "title": "alertmanager接口方法维度qps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bkbcs_alertmanager_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}[5m])) by (handler,method)",
     "legendFormat": "rate-{{handler}}"
    },
    {
     "expr": "sum(irate(bkbcs_alertmanager_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}[5m])) by (handler,method)",
     "legendFormat": "irate-{{handler}}"
    }
   ]
  },
  {
   "title": "alertmanager接口维度时延",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(bkbcs_alertmanager_api_request_latency_time_sum{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by (handler)) / (sum(bkbcs_alertmanager_api_request_latency_time_count{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by (handler))"
    }
   ]
  },
  {
   "title": "alertmanager接口方法维度时延",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(bkbcs_alertmanager_api_request_latency_time_sum{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by (handler,method)) / (sum(bkbcs_alertmanager_api_request_latency_time_count{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by (handler,method))"
    }
   ]
  },
  {
   "title": "alertmanager接口维度成功率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_alertmanager_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\", status=\"0\"}) by(handler) / sum(bkbcs_alertmanager_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by(handler)"
    }
   ]
  },
  {
   "title": "alertmanager接口方法维度成功率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_alertmanager_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\", status=\"0\"}) by(handler,method) / sum(bkbcs_alertmanager_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by(handler,method)"
    }
   ]
  },
  {
   "title": "外部接口维度请求总数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_alertmanager_lib_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by(handler, instance)",
     "legendFormat": "{{handler}}-{{instance}}"
    }
   ]
  },
  {
   "title": "外部接口维度时延",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum(bkbcs_alertmanager_lib_request_latency_time_sum{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by (handler,instance)) / (sum(bkbcs_alertmanager_lib_request_latency_time_count{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by (handler,instance))",
     "legendFormat": "{{handler}}-{{instance}}"
    }
   ]
  },
  {
   "title": "外部接口时延",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bkbcs_alertmanager_lib_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}[2m])) by (handler,instance)",
     "legendFormat": "{{handler}}-{{instance}}"
    }
   ]
  },
  {
   "title": "外部接口成功率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_alertmanager_lib_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\", status=\"200\"}) by(handler,instance) / sum(bkbcs_alertmanager_lib_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by(handler,instance)",
     "legendFormat": "{{handler}}-{{instance}}"
    }
   ]
  }
 ]
}