{
 "title": "bcs-cluster-manager",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster_id",
    "query": "label_values(bkbcs_clustermanager_api_request_total_num{job=\"bcs-cluster-manager\"},cluster_id)"
   },
   {
    "name": "instance",
    "query": "label_values(bkbcs_clustermanager_api_request_total_num{cluster_id=\"$cluster_id\", job=\"bcs-cluster-manager\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "mongo访问请求总数",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_storage_driver_mongdb_total{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by(method, instance)",
     "legendFormat": "{{method}}-{{instance}}"
    }
   ]
  },
  {
   "title": "mongo请求时延",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum(bkbcs_storage_driver_mongodb_latency_seconds_sum{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by (method, instance)) / (sum(bkbcs_storage_driver_mongodb_latency_seconds_count{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by (method, instance))"
    }
   ]
  },
  {
   "title": "mongo请求qps",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bkbcs_storage_driver_mongdb_total{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}[2m])) by (method,instance)",
     "legendFormat": "rate-{{method}}-{{instance}}"
    },
    {
     "expr": "sum(irate(bkbcs_storage_driver_mongdb_total{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}[2m])) by (method,instance)",
     "legendFormat": "irate-{{method}}-{{instance}}"
    }
   ]
  },
  {
   "title": "mongo请求成功率",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_storage_driver_mongdb_total{cluster_id=~\"$cluster_id\", instance=~\"$instance\", status=~\"SUCCESS\"}) by(method,instance) / sum(bkbcs_storage_driver_mongdb_total{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by(method,instance)",
     "legendFormat": "{{handler}}-{{instance}}"
    }
   ]
  },
  {
   "title": "clustermanager接口请求总数",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_clustermanager_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by(handler, instance)"
    }
   ]
  },
  {
   "title": "clustermanager接口时延",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum(bkbcs_clustermanager_api_request_latency_time_sum{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by (handler, instance)) / (sum(bkbcs_clustermanager_api_request_latency_time_count{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by (handler, instance))"
    }
   ]
  },
  {
   "title": "clustermanager接口qps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bkbcs_clustermanager_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}[2m])) by (handler,instance)",
     "legendFormat": "rate-{{handler}}-{{instance}}"
    },
    {
     "expr": "sum(irate(bkbcs_clustermanager_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}[2m])) by (handler,instance)",
     "legendFormat": "irate-{{handler}}-{{instance}}"
    }
   ]
  },
  {
   "title": "cluster-manager接口成功率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_clustermanager_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\", status=~\"0\"}) by(handler,instance) / sum(bkbcs_clustermanager_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by(handler,instance)",
     "legendFormat": "{{handler}}-{{instance}}"
    }
   ]
  }
 ]
}