{
 "title": "bcs-kube-agent",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster_id",
    "query": "label_values(bkbcs_kubeagent_clustermanager_request_total_num{job=\"bcs-kube-agent\"},cluster_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "接口维度qps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bkbcs_kubeagent_clustermanager_request_total_num{cluster_id=~\"$cluster_id\"}[5m])) by (handler)",
     "legendFormat": "rate-{{handler}}"
    },
    {
     "expr": "sum(irate(bkbcs_kubeagent_clustermanager_request_total_num{cluster_id=~\"$cluster_id\"}[5m])) by (handler)",
     "legendFormat": "irate-{{handler}}"
    }
   ]
  },
  {
   "title": "接口维度的平均时延",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(bkbcs_kubeagent_clustermanager_request_latency_time_sum{cluster_id=~\"$cluster_id\"}) by (handler)) / (sum(bkbcs_kubeagent_clustermanager_request_latency_time_count{cluster_id=~\"$cluster_id\"}) by (handler))"
    }
   ]
  },
  {
   "title": "接口维度请求总数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_kubeagent_clustermanager_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by(handler,instance)",
     "legendFormat": "{{handler}}-{{instance}}"
    }
   ]
  },
  {
   "title": "接口维度成功率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_kubeagent_clustermanager_request_total_num{cluster_id=~\"$cluster_id\", code=\"0\"}) by(handler) / sum(bkbcs_kubeagent_clustermanager_request_total_num{cluster_id=~\"$cluster_id\"}) by(handler)"
    }
   ]
  },
  {
   "title": "websocket接口断开重连次数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_kubeagent_clustermanager_ws_connection_num{cluster_id=~\"$cluster_id\"}) by(handler)"
    }
   ]
  }
 ]
}