{
 "title": "bcs-storage",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "cluster_id",
    "query": "label_values(bkbcs_storage_api_request_total_num{job=\"bcs-storage\"}, cluster_id)"
   },
   {
    "name": "instance",
    "query": "label_values(bkbcs_storage_api_request_total_num{cluster_id=\"$cluster_id\", job=\"bcs-storage\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "mongo访问指标",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "mongo访问请求总数",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(bkbcs_storage_driver_mongdb_total{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by(method, instance)",
       "legendFormat": "{{method}}-{{instance}}"
      }
     ]
    },
    {
     "title": "mongo请求qps",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(bkbcs_storage_driver_mongdb_total{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}[2m])) by (method,instance)",
       "legendFormat": "rate-{{method}}={{instance}}"
      },
      {
       "expr": "sum(irate(bkbcs_storage_driver_mongdb_total{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}[2m])) by (method,instance)",
       "legendFormat": "irate-{{method}}={{instance}}"
      }
     ]
    },
    {
     "title": "mongo请求时延",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(sum(bkbcs_storage_driver_mongodb_latency_seconds_sum{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by (method, instance)) / (sum(bkbcs_storage_driver_mongodb_latency_seconds_count{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by (method, instance))",
       "legendFormat": "{{method}}-{{instance}}"
      }
     ]
    },
    {
     "title": "mongo请求成功率",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(bkbcs_storage_driver_mongdb_total{cluster_id=~\"$cluster_id\", instance=~\"$instance\", status=~\"SUCCESS\"}) by(method,instance) / sum(bkbcs_storage_driver_mongdb_total{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by(method,instance)"
      }
     ]
    }
   ]
  },
  {
   "title": "bcs-storage队列指标",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "队列推送数据统计",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(bkbcs_storage_queue_push_total{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by(name)"
      }
     ]
    },
    {
     "title": "推送数据至队列平均时延",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(sum(bkbcs_storage_queue_latency_seconds_sum) by(name, status)) / (sum(bkbcs_storage_queue_latency_seconds_count) by(name, status))"
      }
     ]
    },
    {
     "title": "推动数据至队列的成功率",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(bkbcs_storage_queue_push_total{cluster_id=~\"$cluster_id\", instance=~\"$instance\", status=\"succeed\"}) by(name) / sum(bkbcs_storage_queue_push_total{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by(name)"
      }
     ]
    },
    {
     "title": "推送数据至队列qps",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(bkbcs_storage_queue_push_total{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}[5m])) by(name)",
       "legendFormat": "rate-{{name}}"
      },
      {
       "expr": "sum(irate(bkbcs_storage_queue_push_total{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}[5m])) by(name)",
       "legendFormat": "irate-{{name}}"
      }
     ]
    }
   ]
  },
  { "title": "storage总请求指标", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "storage API请求总数",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_storage_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\"})",
     "legendFormat": "request_total"
    }
   ]
  },
  {
   "title": "storage API每秒请求数",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bkbcs_storage_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "rate-5m"
    },
    {
     "expr": "sum(irate(bkbcs_storage_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "irate-5m"
    }
   ]
  },
  {
   "title": "storage API 请求时延",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_storage_api_request_duration_time_sum{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) / sum(bkbcs_storage_api_request_duration_time_count{cluster_id=~\"$cluster_id\", instance=~\"$instance\"})",
     "legendFormat": "latency-instance"
    }
   ]
  },
  {
   "title": "storage API请求成功率",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_storage_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\", status=\"2xx\"}) / sum(bkbcs_storage_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\"})",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "接口维度请求总数",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_storage_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by(handler)"
    }
   ]
  },
  {
   "title": "接口维度qps",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bkbcs_storage_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}[5m])) by (handler)",
     "legendFormat": "rate--{{handler}}"
    },
    {
     "expr": "sum(irate(bkbcs_storage_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}[5m])) by (handler)",
     "legendFormat": "irate--{{handler}}"
    }
   ]
  },
  {
   "title": "接口维度延迟",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum(bkbcs_storage_api_request_duration_time_sum{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by (handler)) / (sum(bkbcs_storage_api_request_duration_time_count{}) by (handler))"
    }
   ]
  },
  {
   "title": "接口维度成功率",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_storage_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\", status=\"2xx\"}) by(handler) / sum(bkbcs_storage_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by(handler)"
    }
   ]
  },
  {
   "title": "接口方法维度请求总数",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_storage_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by(handler,method)"
    }
   ]
  },
  {
   "title": "接口方法维度qps",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bkbcs_storage_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}[5m])) by (handler,method)",
     "legendFormat": "rate-{{handler}}"
    },
    {
     "expr": "sum(irate(bkbcs_storage_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}[5m])) by (handler,method)",
     "legendFormat": "irate-{{handler}}"
    }
   ]
  },
  {
   "title": "接口方法维度时延",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum(bkbcs_storage_api_request_duration_time_sum{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by (handler,method)) / (sum(bkbcs_storage_api_request_duration_time_count{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by (handler,method))"
    }
   ]
  },
  {
   "title": "接口方法维度成功率",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_storage_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\",status=\"2xx\"}) by(handler,method) / sum(bkbcs_storage_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by(handler,method)"
    }
   ]
  },
  {
   "title": "storage API 接口维度并发量",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_storage_api_requests_inflight{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by(handler,method)",
     "legendFormat": "{{method}}--{{handler}}"
    }
   ]
  },
  {
   "title": "http请求response body体大小",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 123 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(bkbcs_storage_api_response_size_bytes_sum{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by (handler,method)) / (sum(bkbcs_storage_api_response_size_bytes_count{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by (handler,method))",
     "legendFormat": "{{method}}-{{handler}}"
    }
   ]
  },
  {
   "title": "watch表链接数统计",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 136 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_storage_watch_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by(handler, table)",
     "legendFormat": "{{table}}-{{handler}}"
    }
   ]
  }
 ]
}