{
 "title": "bcs-gamedeployment-operator",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "gd controller调协情况",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "调协成功总次数",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(bkbcs_gamedeployment_reconcile_duration_seconds_count{status=\"success\"})"
      }
     ]
    },
    {
     "title": "调协失败总次数",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(bkbcs_gamedeployment_reconcile_duration_seconds_count{status=\"failure\"}>0)"
      }
     ]
    },
    {
     "title": "调协成功耗时(s)分布",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(bkbcs_gamedeployment_reconcile_duration_seconds_bucket{status=\"success\"}) by(le)",
       "legendFormat": "le={{le}}"
      }
     ]
    },
    {
     "title": "调协失败耗时(s)分布",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "bkbcs_gamedeployment_reconcile_duration_seconds_bucket{status=\"failure\"}",
       "legendFormat": "le={{le}}"
      }
     ]
    },
    {
     "title": "调协成功耗时top10的gd资源",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk(10, sum(bkbcs_gamedeployment_reconcile_duration_seconds_sum{status=\"success\"}) by(gd)/sum(bkbcs_gamedeployment_reconcile_duration_seconds_count{status=\"success\"}) by(gd))",
       "legendFormat": "{{gd}}"
      }
     ]
    },
    {
     "title": "调协失败耗时top10的gd资源",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk(10, sum(bkbcs_gamedeployment_reconcile_duration_seconds_sum{status=\"failure\"}) by(gd)/sum(bkbcs_gamedeployment_reconcile_duration_seconds_count{status=\"failure\"}) by(gd))",
       "legendFormat": "{{gd}}"
      }
     ]
    },
    {
     "title": "各gd调协成功次数",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(bkbcs_gamedeployment_reconcile_duration_seconds_count{status=\"success\"}) by(gd)",
       "legendFormat": "{{gd}}"
      }
     ]
    },
    {
     "title": "各gd调协失败次数",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(bkbcs_gamedeployment_reconcile_duration_seconds_count{status=\"failure\"}) by(gd)",
       "legendFormat": "{{gd}}"
      }
     ]
    }
   ]
  },
  { "title": "副本情况", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "各状态下的副本总数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_gamedeployment_replicas)",
     "legendFormat": "DESIRED"
    },
    {
     "expr": "sum(bkbcs_gamedeployment_ready_replicas)",
     "legendFormat": "READY"
    },
    {
     "expr": "sum(bkbcs_gamedeployment_available_replicas)",
     "legendFormat": "AVAILABLE"
    },
    {
     "expr": "sum(bkbcs_gamedeployment_updated_replicas)",
     "legendFormat": "UPDATED"
    },
    {
     "expr": "sum(bkbcs_gamedeployment_updated_ready_replicas)",
     "legendFormat": "UPDATED_READY"
    }
   ]
  },
  {
   "title": "DESIRED副本数top10的gd资源",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum(bkbcs_gamedeployment_replicas) by(gd))",
     "legendFormat": "{{gd}}"
    }
   ]
  },
  {
   "title": "UNREADY副本数top10的gd资源",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum(abs(bkbcs_gamedeployment_replicas-bkbcs_gamedeployment_ready_replicas)) by(gd))",
     "legendFormat": "{{gd}}"
    }
   ]
  },
  {
   "title": "pod创建情况",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "pod创建成功总次数",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(bkbcs_gamedeployment_pod_create_duration_seconds_count{status=\"success\"})"
      }
     ]
    },
    {
     "title": "pod创建失败总次数",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(bkbcs_gamedeployment_pod_create_duration_seconds_count{status=\"failure\"})"
      }
     ]
    },
    {
     "title": "pod创建成功耗时(s)分布",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(bkbcs_gamedeployment_pod_create_duration_seconds_bucket{status=\"success\"}) by(le)",
       "legendFormat": "le={{le}}"
      }
     ]
    },
    {
     "title": "pod创建失败耗时(s)分布",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(bkbcs_gamedeployment_pod_create_duration_seconds_bucket{status=\"failure\"}) by(le)",
       "legendFormat": "le={{le}}"
      }
     ]
    },
    {
     "title": "pod创建成功耗时top10的gd资源",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk(10, sum(bkbcs_gamedeployment_pod_create_duration_seconds_sum{status=\"success\"}) by(gd)/sum(bkbcs_gamedeployment_pod_create_duration_seconds_count{status=\"success\"}) by(gd))",
       "legendFormat": "{{gd}}"
      }
     ]
    },
    {
     "title": "pod创建失败耗时top10的gd资源",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk(10, sum(bkbcs_gamedeployment_pod_create_duration_seconds_sum{status=\"failure\"}) by(gd)/sum(bkbcs_gamedeployment_pod_create_duration_seconds_count{status=\"failure\"}) by(gd))",
       "legendFormat": "{{gd}}"
      }
     ]
    },
    {
     "title": "各gd创建pod成功次数",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(bkbcs_gamedeployment_pod_create_duration_seconds_count{status=\"success\"}) by(gd)",
       "legendFormat": "{{gd}}"
      }
     ]
    },
    {
     "title": "各gd创建pod失败次数",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(bkbcs_gamedeployment_pod_create_duration_seconds_count{status=\"failure\"}) by(gd)",
       "legendFormat": "{{gd}}"
      }
     ]
    },
    {
     "title": "pod创建耗时极值情况",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max(bkbcs_gamedeployment_pod_create_duration_seconds_max) by(status)",
       "legendFormat": "{{status}}_max"
      },
      {
       "expr": "min(bkbcs_gamedeployment_pod_create_duration_seconds_min) by(status)",
       "legendFormat": "{{status}}_min"
      }
     ]
    }
   ]
  },
  {
   "title": "pod删除情况",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "pod删除成功总次数",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(bkbcs_gamedeployment_pod_delete_duration_seconds_count{status=\"success\"})"
      }
     ]
    },
    {
     "title": "pod删除失败总次数",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(bkbcs_gamedeployment_pod_delete_duration_seconds_count{status=\"failure\"})"
      }
     ]
    },
    {
     "title": "pod删除成功耗时(s)分布",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(bkbcs_gamedeployment_pod_delete_duration_seconds_bucket{status=\"success\"}) by(le)",
       "legendFormat": "le={{le}}"
      }
     ]
    },
    {
     "title": "pod删除失败耗时(s)分布",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(bkbcs_gamedeployment_pod_delete_duration_seconds_bucket{status=\"failure\"}) by(le)",
       "legendFormat": "le={{le}}"
      }
     ]
    },
    {
     "title": "pod删除成功耗时top10的gd资源",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk(10, sum(bkbcs_gamedeployment_pod_delete_duration_seconds_sum{status=\"success\"}) by(gd)/sum(bkbcs_gamedeployment_pod_delete_duration_seconds_count{status=\"success\"}) by(gd))",
       "legendFormat": "{{gd}}"
      }
     ]
    },
    {
     "title": "pod删除失败耗时top10的gd资源",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk(10, sum(bkbcs_gamedeployment_pod_delete_duration_seconds_sum{status=\"failure\"}) by(gd)/sum(bkbcs_gamedeployment_pod_delete_duration_seconds_count{status=\"failure\"}) by(gd))",
       "legendFormat": "{{gd}}"
      }
     ]
    },
    {
     "title": "各gd删除pod成功次数",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(bkbcs_gamedeployment_pod_delete_duration_seconds_count{status=\"success\"}) by(gd)",
       "legendFormat": "{{gd}}"
      }
     ]
    },
    {
     "title": "各gd删除pod失败次数",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(bkbcs_gamedeployment_pod_delete_duration_seconds_count{status=\"failure\"}) by(gd)",
       "legendFormat": "gd={{gd}}"
      }
     ]
    },
    {
     "title": "pod删除耗时极值情况",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max(bkbcs_gamedeployment_pod_delete_duration_seconds_max) by(status)",
       "legendFormat": "{{status}}_max"
      },
      {
       "expr": "min(bkbcs_gamedeployment_pod_delete_duration_seconds_min) by(status)",
       "legendFormat": "{{status}}_min"
      }
     ]
    }
   ]
  },
  {
   "title": "pod更新情况",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "pod更新成功总次数",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(bkbcs_gamedeployment_pod_update_duration_seconds_count{status=\"success\"})"
      }
     ]
    },
    {
     "title": "pod更新失败总次数",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(bkbcs_gamedeployment_pod_update_duration_seconds_count{status=\"failure\"})"
      }
     ]
    },
    {
     "title": "pod更新成功耗时(s)分布",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(bkbcs_gamedeployment_pod_update_duration_seconds_bucket{status=\"success\"}) by(le)",
       "legendFormat": "le={{le}}"
      }
     ]
    },
    {
     "title": "pod更新失败耗时(s)分布",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(bkbcs_gamedeployment_pod_update_duration_seconds_bucket{status=\"failure\"}) by(le)",
       "legendFormat": "le={{le}}"
      }
     ]
    },
    {
     "title": "pod更新成功耗时top10的gd资源",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk(10, sum(bkbcs_gamedeployment_pod_update_duration_seconds_sum{status=\"success\"}) by(gd)/sum(bkbcs_gamedeployment_pod_update_duration_seconds_count{status=\"success\"}) by(gd))",
       "legendFormat": "{{gd}}"
      }
     ]
    },
    {
     "title": "pod更新失败耗时top10的gd资源",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk(10, sum(bkbcs_gamedeployment_pod_update_duration_seconds_sum{status=\"failure\"}) by(gd)/sum(bkbcs_gamedeployment_pod_update_duration_seconds_count{status=\"failure\"}) by(gd))",
       "legendFormat": "{{gd}}"
      }
     ]
    },
    {
     "title": "各gd更新pod成功次数",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(bkbcs_gamedeployment_pod_update_duration_seconds_count{status=\"success\"}) by(gd)",
       "legendFormat": "{{gd}}"
      }
     ]
    },
    {
     "title": "各gd更新pod失败次数",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(bkbcs_gamedeployment_pod_update_duration_seconds_count{status=\"failure\"}) by(gd)",
       "legendFormat": "{{gd}}"
      }
     ]
    },
    {
     "title": "pod更新耗时极值情况",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max(bkbcs_gamedeployment_pod_update_duration_seconds_max) by(status)",
       "legendFormat": "{{status}}_max"
      },
      {
       "expr": "min(bkbcs_gamedeployment_pod_update_duration_seconds_min) by(status)",
       "legendFormat": "{{status}}_min"
      }
     ]
    }
   ]
  }
 ]
}