{
 "title": "bcs-webhook-server",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster_id",
    "query": "label_values(promhttp_metric_handler_requests_total{job=\"bcs-webhook-server\"}, cluster_id)"
   },
   {
    "name": "instance",
    "query": "label_values(promhttp_metric_handler_requests_total{cluster_id=\"$cluster_id\", job=\"bcs-webhook-server\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "webhook api接口维度请求总数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_webhookserver_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by(handler, instance)"
    }
   ]
  },
  {
   "title": "webhook api接口维度请求qps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bkbcs_webhookserver_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}[5m])) by (handler,instance)"
    },
    {
     "expr": "sum(irate(bkbcs_webhookserver_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}[5m])) by (handler,instance)"
    }
   ]
  },
  {
   "title": "webhook api接口维度请求时延",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(bkbcs_webhookserver_api_request_latency_time_sum{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by (handler,instance)) / (sum(bkbcs_webhookserver_api_request_latency_time_count{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by (handler,instance))"
    }
   ]
  },
  {
   "title": "webhook api接口维度请求成功率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_webhookserver_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\", status=\"success\"}) by(handler) / sum(bkbcs_webhookserver_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by(handler)"
    }
   ]
  },
  {
   "title": "webhook plugin运行时延",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(bkbcs_webhookserver_plugin_request_latency_time_sum{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by (pluginName, instance)) / (sum(bkbcs_webhookserver_plugin_request_latency_time_count{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by (pluginName, instance))"
    }
   ]
  }
 ]
}