{
 "title": "bcs-storage SLA",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "查询请求", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "数据查询请求成功率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_storage_api_request_total_num{handler=~\".*/dynamic.*\",method=~\"GET|POST\",status=\"2xx\"} or bkbcs_storage_api_request_total_num{handler=~\".*/metric/clusters.*\",method=\"GET\",status=\"2xx\"} or bkbcs_storage_api_request_total_num{handler=~\".*/alarms.*\",method=\"GET\",status=\"2xx\"} or bkbcs_storage_api_request_total_num{handler=~\".*/events.*\",method=\"GET\",status=\"2xx\"} or bkbcs_storage_api_request_total_num{handler=~\".*/cluster_config.*\",method=\"GET\",status=\"2xx\"} or bkbcs_storage_api_request_total_num{handler=~\".*/host.*\",method=\"GET\",status=\"2xx\"}) by (instance) / sum(bkbcs_storage_api_request_total_num{handler=~\".*/dynamic.*\",method=~\"GET|POST\"} or bkbcs_storage_api_request_total_num{handler=~\".*/metric/clusters.*\",method=\"GET\"} or bkbcs_storage_api_request_total_num{handler=~\".*/alarms.*\",method=\"GET\"} or bkbcs_storage_api_request_total_num{handler=~\".*/events.*\",method=\"GET\"} or bkbcs_storage_api_request_total_num{handler=~\".*/cluster_config.*\",method=\"GET\"} or bkbcs_storage_api_request_total_num{handler=~\".*/host.*\",method=\"GET\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "动态数据查询成功率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_storage_api_request_total_num{handler=~\".*/dynamic.*\",method=~\"GET|POST\",status=\"2xx\"})/sum(bkbcs_storage_api_request_total_num{handler=~\".*/dynamic.*\",method=~\"GET|POST\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "metric数据查询成功率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_storage_api_request_total_num{handler=~\".*/metric/clusters.*\",method=\"GET\",status=\"2xx\"})/sum(bkbcs_storage_api_request_total_num{handler=~\".*/metric/clusters.*\",method=\"GET\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "event查询成功率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_storage_api_request_total_num{handler=~\".*/events.*\",method=\"GET\",status=\"2xx\"})/sum(bkbcs_storage_api_request_total_num{handler=~\".*/events.*\",method=\"GET\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "alarm查询成功率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_storage_api_request_total_num{handler=~\".*/alarms.*\",method=\"GET\",status=\"2xx\"})/sum(bkbcs_storage_api_request_total_num{handler=~\".*/alarms.*\",method=\"GET\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "集群配置查询成功率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_storage_api_request_total_num{handler=~\".*/cluster_config.*\",method=\"GET\",status=\"2xx\"})/sum(bkbcs_storage_api_request_total_num{handler=~\".*/cluster_config.*\",method=\"GET\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "host配置查询成功率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_storage_api_request_total_num{handler=~\".*/host.*\",method=\"GET\",status=\"2xx\"})/sum(bkbcs_storage_api_request_total_num{handler=~\".*/host.*\",method=\"GET\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "数据查询请求延时<50ms",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_storage_api_request_duration_time_bucket{handler=~\".*/dynamic.*\",method=~\"GET|POST\",status=\"2xx\",le=\"0.05\"} or bkbcs_storage_api_request_duration_time_bucket{handler=~\"/metric/clusters.*\",method=\"GET\",status=\"2xx\",le=\"0.05\"} or bkbcs_storage_api_request_duration_time_bucket{handler=~\"/alarms.*\",method=\"GET\",status=\"2xx\",le=\"0.05\"} or bkbcs_storage_api_request_duration_time_bucket{handler=~\"/events.*\",method=\"GET\",status=\"2xx\",le=\"0.05\"} or bkbcs_storage_api_request_duration_time_bucket{handler=~\"/cluster_config.*\",method=\"GET\",status=\"2xx\",le=\"0.05\"} or bkbcs_storage_api_request_duration_time_bucket{handler=~\"/host.*\",method=\"GET\",status=\"2xx\",le=\"0.05\"}) by (instance) / sum(bkbcs_storage_api_request_duration_time_count{status=\"2xx\",handler=~\".*/dynamic.*\",method=~\"GET|POST\"} or bkbcs_storage_api_request_duration_time_count{status=\"2xx\",handler=~\"/metric/clusters.*\",method=\"GET\"} or bkbcs_storage_api_request_duration_time_count{status=\"2xx\",handler=~\"/alarms.*\",method=\"GET\"} or bkbcs_storage_api_request_duration_time_count{status=\"2xx\",handler=~\"/events.*\",method=\"GET\"} or bkbcs_storage_api_request_duration_time_count{status=\"2xx\",handler=~\"/cluster_config.*\",method=\"GET\"} or bkbcs_storage_api_request_duration_time_count{status=\"2xx\",handler=~\"/host.*\",method=\"GET\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "动态数据查询延时<50ms",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_storage_api_request_duration_time_bucket{handler=~\".*/dynamic.*\",method=~\"GET|POST\",status=\"2xx\",le=\"0.05\"})/sum(bkbcs_storage_api_request_duration_time_count{status=\"2xx\",handler=~\".*/dynamic.*\",method=~\"GET|POST\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "metric数据查询延时<50ms",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_storage_api_request_duration_time_bucket{handler=~\".*/metric/clusters.*\",method=\"GET\",status=\"2xx\",le=\"0.05\"})/sum(bkbcs_storage_api_request_duration_time_count{status=\"2xx\",handler=~\".*/metric/clusters.*\",method=\"GET\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "event查询延时<50ms",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_storage_api_request_duration_time_bucket{handler=~\".*/event.*\",method=\"GET\",status=\"2xx\",le=\"0.05\"})/sum(bkbcs_storage_api_request_duration_time_count{status=\"2xx\",handler=~\".*/mevent.*\",method=\"GET\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "alarm查询延时<50ms",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_storage_api_request_duration_time_bucket{handler=~\".*/alarms.*\",method=\"GET\",status=\"2xx\",le=\"0.05\"})/sum(bkbcs_storage_api_request_duration_time_count{status=\"2xx\",handler=~\".*/alarms.*\",method=\"GET\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "集群配置查询延时<50ms",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_storage_api_request_duration_time_bucket{handler=~\".*/cluster_config.*\",method=\"GET\",status=\"2xx\",le=\"0.05\"})/sum(bkbcs_storage_api_request_duration_time_count{status=\"2xx\",handler=~\".*/cluster_config.*\",method=\"GET\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "host配置查询延时<50ms",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_storage_api_request_duration_time_bucket{handler=~\".*/host.*\",method=\"GET\",status=\"2xx\",le=\"0.05\"})/sum(bkbcs_storage_api_request_duration_time_count{status=\"2xx\",handler=~\".*/host.*\",method=\"GET\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  { "title": "上报/更新请求", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "数据上报/更新请求成功率",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_storage_api_request_total_num{handler=~\".*/dynamic.*\",method=\"PUT\",status=\"2xx\"} or bkbcs_storage_api_request_total_num{handler=~\".*/metric/clusters.*\",method=\"PUT\",status=\"2xx\"} or bkbcs_storage_api_request_total_num{handler=~\".*/alarms.*\",method=\"POST\",status=\"2xx\"} or bkbcs_storage_api_request_total_num{handler=~\".*/events.*\",method=\"PUT\",status=\"2xx\"} or bkbcs_storage_api_request_total_num{handler=~\".*/cluster_config.*\",method=\"PUT\",status=\"2xx\"} or bkbcs_storage_api_request_total_num{handler=~\".*/host.*\",method=\"PUT\",status=\"2xx\"}) by (instance) / sum(bkbcs_storage_api_request_total_num{handler=~\".*/dynamic.*\",method=\"PUT\"} or bkbcs_storage_api_request_total_num{handler=~\".*/metric/clusters.*\",method=\"PUT\"} or bkbcs_storage_api_request_total_num{handler=~\".*/alarms.*\",method=\"POST\"} or bkbcs_storage_api_request_total_num{handler=~\".*/events.*\",method=\"PUT\"} or bkbcs_storage_api_request_total_num{handler=~\".*/cluster_config.*\",method=\"PUT\"} or bkbcs_storage_api_request_total_num{handler=~\".*/host.*\",method=\"PUT\"}) by (instance)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "动态数据上报/更新成功率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_storage_api_request_total_num{handler=~\".*/dynamic.*\",method=\"PUT\",status=\"2xx\"})/sum(bkbcs_storage_api_request_total_num{handler=~\".*/dynamic.*\",method=\"PUT\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "metric数据上报/更新成功率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_storage_api_request_total_num{handler=~\".*/metric/clusters.*\",method=\"PUT\",status=\"2xx\"})/sum(bkbcs_storage_api_request_total_num{handler=~\".*/metric/clusters.*\",method=\"PUT\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "event上报/更新成功率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_storage_api_request_total_num{handler=~\".*/events.*\",method=\"PUT\",status=\"2xx\"})/sum(bkbcs_storage_api_request_total_num{handler=~\".*/events.*\",method=\"PUT\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "alarm上报/更新成功率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_storage_api_request_total_num{handler=~\".*/alarms.*\",method=\"POST\",status=\"2xx\"})/sum(bkbcs_storage_api_request_total_num{handler=~\".*/alarms.*\",method=\"POST\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "集群配置上报/更新成功率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_storage_api_request_total_num{handler=~\".*/cluster_config.*\",method=\"GET\",status=\"2xx\"})/sum(bkbcs_storage_api_request_total_num{handler=~\".*/cluster_config.*\",method=\"GET\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "host配置上报/更新成功率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_storage_api_request_total_num{handler=~\".*/host.*\",method=\"PUT\",status=\"2xx\"})/sum(bkbcs_storage_api_request_total_num{handler=~\".*/host.*\",method=\"PUT\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "数据上报/更新请求延时<250ms",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_storage_api_request_duration_time_bucket{handler=~\".*/dynamic.*\",method=~\"PUT\",status=\"2xx\",le=\"0.25\"} or bkbcs_storage_api_request_duration_time_bucket{handler=~\"/metric/clusters.*\",method=\"PUT\",status=\"2xx\",le=\"0.25\"} or bkbcs_storage_api_request_duration_time_bucket{handler=~\"/alarms.*\",method=\"POST\",status=\"2xx\",le=\"0.25\"} or bkbcs_storage_api_request_duration_time_bucket{handler=~\"/events.*\",method=\"PUT\",status=\"2xx\",le=\"0.25\"} or bkbcs_storage_api_request_duration_time_bucket{handler=~\"/cluster_config.*\",method=\"PUT\",status=\"2xx\",le=\"0.25\"} or bkbcs_storage_api_request_duration_time_bucket{handler=~\"/host.*\",method=\"PUT\",status=\"2xx\",le=\"0.25\"}) by (instance) / sum(bkbcs_storage_api_request_duration_time_count{status=\"2xx\",handler=~\".*/dynamic.*\",method=~\"PUT\"} or bkbcs_storage_api_request_duration_time_count{status=\"2xx\",handler=~\"/metric/clusters.*\",method=\"PUT\"} or bkbcs_storage_api_request_duration_time_count{status=\"2xx\",handler=~\"/alarms.*\",method=\"POST\"} or bkbcs_storage_api_request_duration_time_count{status=\"2xx\",handler=~\"/events.*\",method=\"PUT\"} or bkbcs_storage_api_request_duration_time_count{status=\"2xx\",handler=~\"/cluster_config.*\",method=\"PUT\"} or bkbcs_storage_api_request_duration_time_count{status=\"2xx\",handler=~\"/host.*\",method=\"PUT\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "动态数据上报/更新延时<250ms",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_storage_api_request_duration_time_bucket{handler=~\".*/dynamic.*\",method=\"PUT\",status=\"2xx\",le=\"0.25\"})/ sum(bkbcs_storage_api_request_duration_time_count{status=\"2xx\",handler=~\".*/dynamic.*\",method=\"PUT\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "metric数据上报/更新延时<250ms",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_storage_api_request_duration_time_bucket{handler=~\".*/metric/clusters.*\",method=\"PUT\",status=\"2xx\",le=\"0.25\"})/ sum(bkbcs_storage_api_request_duration_time_count{status=\"2xx\",handler=~\".*/metric/clusters.*\",method=\"PUT\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "event上报/更新延时<250ms",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_storage_api_request_duration_time_bucket{handler=~\".*/event.*\",method=\"PUT\",status=\"2xx\",le=\"0.25\"})/sum(bkbcs_storage_api_request_duration_time_count{status=\"2xx\",handler=~\".*/event.*\",method=\"PUT\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "alarm上报/更新延时<250ms",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_storage_api_request_duration_time_bucket{handler=~\".*/alarms.*\",method=\"POST\",status=\"2xx\",le=\"0.25\"})/ sum(bkbcs_storage_api_request_duration_time_count{status=\"2xx\",handler=~\".*/alarms.*\",method=\"POST\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "集群配置上报/更新延时<250ms",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_storage_api_request_duration_time_bucket{handler=~\".*/cluster_config.*\",method=\"PUT\",status=\"2xx\",le=\"0.25\"})/sum(bkbcs_storage_api_request_duration_time_count{status=\"2xx\",handler=~\".*/cluster_config.*\",method=\"PUT\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "host配置上报/更新延时<250ms",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_storage_api_request_duration_time_bucket{handler=~\".*/host.*\",method=\"PUT\",status=\"2xx\",le=\"0.25\"})/sum(bkbcs_storage_api_request_duration_time_count{status=\"2xx\",handler=~\".*/host.*\",method=\"PUT\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  { "title": "删除请求", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 130 } },
  {
   "title": "数据删除请求成功率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_storage_api_request_total_num{handler=~\".*/dynamic.*\",method=\"DELETE\",status=\"2xx\"} or bkbcs_storage_api_request_total_num{handler=~\".*/metric/clusters.*\",method=\"DELETE\",status=\"2xx\"} or bkbcs_storage_api_request_total_num{handler=~\".*/host.*\",method=\"PUT\",status=\"2xx\"}) by (instance) / sum(bkbcs_storage_api_request_total_num{handler=~\".*/dynamic.*\",method=\"DELETE\"} or bkbcs_storage_api_request_total_num{handler=~\".*/metric/clusters.*\",method=\"DELETE\"} or bkbcs_storage_api_request_total_num{handler=~\".*/host.*\",method=\"DELETE\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "动态数据删除成功率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_storage_api_request_total_num{handler=~\".*/dynamic.*\",method=\"DELETE\",status=\"2xx\"})/sum(bkbcs_storage_api_request_total_num{handler=~\".*/dynamic.*\",method=\"DELETE\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "metric数据删除成功率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_storage_api_request_total_num{handler=~\".*/metric/clusters.*\",method=\"DELETE\",status=\"2xx\"})/sum(bkbcs_storage_api_request_total_num{handler=~\".*/metric/clusters.*\",method=\"DELETE\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "host配置删除成功率",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_storage_api_request_total_num{handler=~\".*/host.*\",method=\"DELETE\",status=\"2xx\"})/sum(bkbcs_storage_api_request_total_num{handler=~\".*/host.*\",method=\"DELETE\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "数据删除请求延时<250ms",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_storage_api_request_duration_time_bucket{handler=~\".*/dynamic.*\",method=~\"DELETE\",status=\"2xx\",le=\"0.25\"} or bkbcs_storage_api_request_duration_time_bucket{handler=~\"/metric/clusters.*\",method=\"DELETE\",status=\"2xx\",le=\"0.25\"} or bkbcs_storage_api_request_duration_time_bucket{handler=~\"/host.*\",method=\"DELETE\",status=\"2xx\",le=\"0.25\"}) by (instance) / sum(bkbcs_storage_api_request_duration_time_count{status=\"2xx\",handler=~\".*/dynamic.*\",method=~\"DELETE\"} or bkbcs_storage_api_request_duration_time_count{status=\"2xx\",handler=~\"/metric/clusters.*\",method=\"DELETE\"} or bkbcs_storage_api_request_duration_time_count{status=\"2xx\",handler=~\"/alarms.*\",method=\"POST\"} or bkbcs_storage_api_request_duration_time_count{status=\"2xx\",handler=~\"/host.*\",method=\"DELETE\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "动态数据删除延时<250ms",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 162 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_storage_api_request_duration_time_bucket{handler=~\".*/dynamic.*\",method=\"DELETE\",status=\"2xx\",le=\"0.25\"})/sum(bkbcs_storage_api_request_duration_time_count{status=\"2xx\",handler=~\".*/dynamic.*\",method=\"DELETE\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "metric数据删除延时<250ms",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 162 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_storage_api_request_duration_time_bucket{handler=~\".*/metric/clusters.*\",method=\"DELETE\",status=\"2xx\",le=\"0.25\"})/sum(bkbcs_storage_api_request_duration_time_count{status=\"2xx\",handler=~\".*/metric/clusters.*\",method=\"DELETE\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "host配置删除延时<250ms",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 170 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_storage_api_request_duration_time_bucket{handler=~\".*/host.*\",method=\"DELETE\",status=\"2xx\",le=\"0.25\"})/sum(bkbcs_storage_api_request_duration_time_count{status=\"2xx\",handler=~\".*/host.*\",method=\"DELETE\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  }
 ]
}