{
 "title": "bcs-gateway-discovery",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster_id",
    "query": "label_values(bkbcs_gatewaydiscovery_api_request_total_num{job=\"bcs-api-gateway\"},cluster_id)"
   },
   {
    "name": "instance",
    "query": "label_values(bkbcs_gatewaydiscovery_api_request_total_num{cluster_id=\"$cluster_id\", job=\"bcs-api-gateway\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "外部接口维度请求总数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_gatewaydiscovery_api_request_total_num{cluster_id=~\"$cluster_id\",instance=~\"$instance\"}) by(system, handler, instance)"
    }
   ]
  },
  {
   "title": "外部接口方法维度请求总数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_gatewaydiscovery_api_request_total_num{cluster_id=~\"$cluster_id\",instance=~\"$instance\"}) by(system, handler, method, instance)"
    }
   ]
  },
  {
   "title": "外部系统接口维度访问qps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bkbcs_gatewaydiscovery_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}[5m])) by (system, handler, instance)"
    },
    {
     "expr": "sum(irate(bkbcs_gatewaydiscovery_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}[5m])) by (system, handler, instance)"
    }
   ]
  },
  {
   "title": "外部系统接口方法维度访问qps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bkbcs_gatewaydiscovery_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}[5m])) by (system, handler, method, instance)"
    },
    {
     "expr": "sum(irate(bkbcs_gatewaydiscovery_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}[5m])) by (system, handler, method, instance)"
    }
   ]
  },
  {
   "title": "外部接口维度请求时延",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum(bkbcs_gatewaydiscovery_api_request_latency_time_sum{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by (system, handler, instance)) / (sum(bkbcs_gatewaydiscovery_api_request_latency_time_count{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by (system, handler, instance))"
    }
   ]
  },
  {
   "title": "外部接口方法维度请求时延",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum(bkbcs_gatewaydiscovery_api_request_latency_time_sum{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by (system, handler, method, instance)) / (sum(bkbcs_gatewaydiscovery_api_request_latency_time_count{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by (system, handler, method, instance))"
    }
   ]
  },
  {
   "title": "外部系统接口维度成功率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_gatewaydiscovery_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\", status=\"success\"}) by(system, handler, instance) / sum(bkbcs_gatewaydiscovery_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by(system, handler, instance)"
    }
   ]
  },
  {
   "title": "外部系统接口方法维度成功率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_gatewaydiscovery_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\", status=\"success\"}) by(system, handler, method, instance) / sum(bkbcs_gatewaydiscovery_api_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by(system, handler, method, instance)"
    }
   ]
  },
  {
   "title": "register接口handler请求总数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_gatewaydiscovery_register_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by(system, handler, instance)"
    }
   ]
  },
  {
   "title": "register接口handler请求时延",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(bkbcs_gatewaydiscovery_register_request_latency_time_sum{cluster_id=~\"$cluster_id\",instance=~\"$instance\"}) by (system, handler, instance)) / (sum(bkbcs_gatewaydiscovery_register_request_latency_time_count{cluster_id=~\"$cluster_id\",instance=~\"$instance\"}) by (system, handler, instance))"
    }
   ]
  },
  {
   "title": "register接口handler请求qps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bkbcs_gatewaydiscovery_register_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}[5m])) by (system, handler, instance)"
    },
    {
     "expr": "sum(irate(bkbcs_gatewaydiscovery_register_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}[5m])) by (system, handler, instance)"
    }
   ]
  },
  {
   "title": "register接口handler请求成功率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_gatewaydiscovery_register_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\", status=\"success\"}) by(system, handler, instance) / sum(bkbcs_gatewaydiscovery_register_request_total_num{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}) by(system, handler, instance)"
    }
   ]
  },
  {
   "title": "服务发现模块队列长度",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bkbcs_gatewaydiscovery_eventchan_length{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}",
     "legendFormat": "eventchan_handler"
    }
   ]
  }
 ]
}