{
 "title": "bcs-gamestatefulset-operator",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster_id",
    "query": "label_values(bkbcs_gamestatefulset_reconcile_duration_seconds_count{}, cluster_id)"
   }
  ]
 },
 "panels": [
  { "title": "gsts controller调协情况", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "调协成功总次数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_gamestatefulset_reconcile_duration_seconds_count{cluster_id=\"$cluster_id\",status=\"success\"})"
    }
   ]
  },
  {
   "title": "调协失败总次数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_gamestatefulset_reconcile_duration_seconds_count{cluster_id=\"$cluster_id\",status=\"failure\"})"
    }
   ]
  },
  {
   "title": "调协成功耗时(s)分布",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(bkbcs_gamestatefulset_reconcile_duration_seconds_bucket{cluster_id=\"$cluster_id\",status=\"success\"}) by (le)",
     "legendFormat": "le={{le}}"
    }
   ]
  },
  {
   "title": "调协失败耗时(s)分布",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(bkbcs_gamestatefulset_reconcile_duration_seconds_bucket{cluster_id=\"$cluster_id\",status=\"failure\"}) by (le)",
     "legendFormat": "le={{le}}"
    }
   ]
  },
  {
   "title": "调协成功耗时top10的gsts资源",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(bkbcs_gamestatefulset_reconcile_duration_seconds_sum{cluster_id=\"$cluster_id\",status=\"success\"}) by(exported_namespace,name)/sum(bkbcs_gamestatefulset_reconcile_duration_seconds_count{status=\"success\"}) by(exported_namespace,name))",
     "legendFormat": "{{exported_namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "调协失败耗时top10的gsts资源",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(bkbcs_gamestatefulset_reconcile_duration_seconds_sum{cluster_id=\"$cluster_id\",status=\"failure\"}) by(exported_namespace,name)/sum(bkbcs_gamestatefulset_reconcile_duration_seconds_count{status=\"failure\"}) by(exported_namespace,name))",
     "legendFormat": "{{exported_namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "各gsts调协成功次数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_gamestatefulset_reconcile_duration_seconds_count{cluster_id=\"$cluster_id\",status=\"success\"}) by(exported_namespace,name)",
     "legendFormat": "{{exported_namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "各gsts调协失败次数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_gamestatefulset_reconcile_duration_seconds_count{cluster_id=\"$cluster_id\",status=\"failure\"}) by(exported_namespace,name)",
     "legendFormat": "{{exported_namespace}}/{{name}}"
    }
   ]
  },
  { "title": "副本情况", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "各状态下的副本总数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_gamestatefulset_replicas{cluster_id=\"$cluster_id\"})",
     "legendFormat": "DESIRED"
    },
    {
     "expr": "sum(bkbcs_gamestatefulset_ready_replicas{cluster_id=\"$cluster_id\"})",
     "legendFormat": "READY"
    },
    {
     "expr": "sum(bkbcs_gamestatefulset_current_replicas{cluster_id=\"$cluster_id\"})",
     "legendFormat": "CRRENT"
    },
    {
     "expr": "sum(bkbcs_gamestatefulset_updated_replicas{cluster_id=\"$cluster_id\"})",
     "legendFormat": "UPDATED"
    },
    {
     "expr": "sum(bkbcs_gamestatefulset_updated_ready_replicas{cluster_id=\"$cluster_id\"})",
     "legendFormat": "UPDATED_READY"
    }
   ]
  },
  {
   "title": "DESIRED副本数top10的gsts资源",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum(bkbcs_gamestatefulset_replicas{cluster_id=\"$cluster_id\"}) by(exported_namespace,name))",
     "legendFormat": "{{exported_namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "UNREADY副本数top10的gsts资源",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum(abs(bkbcs_gamestatefulset_replicas{cluster_id=\"$cluster_id\"} - bkbcs_gamestatefulset_ready_replicas{cluster_id=\"$cluster_id\"})) by(exported_namespace,name))",
     "legendFormat": "{{exported_namespace}}/{{name}}"
    }
   ]
  },
  { "title": "pod创建情况", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "pod创建成功总次数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_gamestatefulset_pod_create_duration_seconds_count{cluster_id=\"$cluster_id\",status=\"success\"})"
    }
   ]
  },
  {
   "title": "pod创建失败总次数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_gamestatefulset_pod_create_duration_seconds_count{cluster_id=\"$cluster_id\",status=\"failure\"})"
    }
   ]
  },
  {
   "title": "pod创建成功耗时(s)分布",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "sum(bkbcs_gamestatefulset_pod_create_duration_seconds_bucket{cluster_id=\"$cluster_id\",status=\"success\"}) by (le)",
     "legendFormat": "le={{le}}"
    }
   ]
  },
  {
   "title": "pod创建失败耗时(s)分布",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "sum(bkbcs_gamestatefulset_pod_create_duration_seconds_bucket{cluster_id=\"$cluster_id\",status=\"failure\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "pod创建成功耗时top10的gsts资源",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(bkbcs_gamestatefulset_pod_create_duration_seconds_sum{cluster_id=\"$cluster_id\",status=\"success\"}) by(exported_namespace,name)/sum(bkbcs_gamestatefulset_pod_create_duration_seconds_count{status=\"success\"}) by(exported_namespace,name))",
     "legendFormat": "{{exported_namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "pod创建失败耗时top10的gsts资源",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(bkbcs_gamestatefulset_pod_create_duration_seconds_sum{cluster_id=\"$cluster_id\",status=\"failure\"}) by(exported_namespace,name)/sum(bkbcs_gamestatefulset_pod_create_duration_seconds_count{status=\"failure\"}) by(exported_namespace,name))",
     "legendFormat": "{{exported_namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "各gsts创建pod成功次数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_gamestatefulset_pod_create_duration_seconds_count{cluster_id=\"$cluster_id\",status=\"success\"}) by(exported_namespace,name)",
     "legendFormat": "{{exported_namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "各gsts创建pod失败次数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_gamestatefulset_pod_create_duration_seconds_count{cluster_id=\"$cluster_id\",status=\"failure\"}) by(exported_namespace,name)",
     "legendFormat": "{{exported_namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "pod创建耗时极值情况",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(bkbcs_gamestatefulset_pod_create_duration_seconds_max{cluster_id=\"$cluster_id\"}) by(status)",
     "legendFormat": "{{status}}_max"
    },
    {
     "expr": "min(bkbcs_gamestatefulset_pod_create_duration_seconds_min{cluster_id=\"$cluster_id\"}) by(status)",
     "legendFormat": "{{status}}_min"
    }
   ]
  },
  { "title": "pod删除情况", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "pod删除成功总次数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 76 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_gamestatefulset_pod_delete_duration_seconds_count{cluster_id=\"$cluster_id\",status=\"success\"})"
    }
   ]
  },
  {
   "title": "pod删除失败总次数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 76 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_gamestatefulset_pod_delete_duration_seconds_count{cluster_id=\"$cluster_id\",status=\"failure\"})"
    }
   ]
  },
  {
   "title": "pod删除成功耗时(s)分布",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "sum(bkbcs_gamestatefulset_pod_delete_duration_seconds_bucket{cluster_id=\"$cluster_id\",status=\"success\"}) by(le)",
     "legendFormat": "le={{le}}"
    }
   ]
  },
  {
   "title": "pod删除失败耗时(s)分布",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "targets": [
    {
     "expr": "sum(bkbcs_gamestatefulset_pod_delete_duration_seconds_bucket{cluster_id=\"$cluster_id\",status=\"failure\"}) by(le)",
     "legendFormat": "le={{le}}"
    }
   ]
  },
  {
   "title": "pod删除成功耗时top10的gsts资源",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(bkbcs_gamestatefulset_pod_delete_duration_seconds_sum{cluster_id=\"$cluster_id\",status=\"success\"}) by(exported_namespace,name)/sum(bkbcs_gamestatefulset_pod_delete_duration_seconds_count{status=\"success\"}) by(exported_namespace,name))",
     "legendFormat": "{{exported_namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "pod删除失败耗时top10的gsts资源",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(bkbcs_gamesatefulset_pod_delete_duration_seconds_sum{cluster_id=\"$cluster_id\",status=\"failure\"}) by(exported_namespace,name)/sum(bkbcs_gamesatefulset_pod_delete_duration_seconds_count{status=\"failure\"}) by(exported_namespace,name))",
     "legendFormat": "{{exported_namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "各gsts删除pod成功次数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_gamestatefulset_pod_delete_duration_seconds_count{cluster_id=\"$cluster_id\",status=\"success\"}) by(exported_namespace,name)",
     "legendFormat": "{{exported_namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "各gsts删除pod失败次数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_gamestatefulset_pod_delete_duration_seconds_count{cluster_id=\"$cluster_id\",status=\"failure\"}) by(exported_namespace,name)",
     "legendFormat": "{{namespce}}/{{name}}"
    }
   ]
  },
  {
   "title": "pod删除耗时极值情况",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(bkbcs_gamestatefulset_pod_delete_duration_seconds_max{cluster_id=\"$cluster_id\"}) by(status)",
     "legendFormat": "{{status}}_max"
    },
    {
     "expr": "min(bkbcs_gamestatefulset_pod_delete_duration_seconds_min{cluster_id=\"$cluster_id\"}) by(status)",
     "legendFormat": "{{status}}_min"
    }
   ]
  },
  { "title": "pod更新情况", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 } },
  {
   "title": "pod更新成功总次数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 113 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_gamestatefulset_pod_update_duration_seconds_count{cluster_id=\"$cluster_id\",status=\"success\"})"
    }
   ]
  },
  {
   "title": "pod更新失败总次数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 113 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bkbcs_gamestatefulset_pod_update_duration_seconds_count{cluster_id=\"$cluster_id\",status=\"failure\"})"
    }
   ]
  },
  {
   "title": "pod更新成功耗时(s)分布",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 118 },
   "targets": [
    {
     "expr": "sum(bkbcs_gamestatefulset_pod_update_duration_seconds_bucket{cluster_id=\"$cluster_id\",status=\"success\"}) by(le)",
     "legendFormat": "le={{le}}"
    }
   ]
  },
  {
   "title": "pod更新失败耗时(s)分布",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 118 },
   "targets": [
    {
     "expr": "sum(bkbcs_gamestatefulset_pod_update_duration_seconds_bucket{cluster_id=\"$cluster_id\",status=\"failure\"}) by(le)",
     "legendFormat": "le={{le}}"
    }
   ]
  },
  {
   "title": "pod更新成功耗时top10的gd资源",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 126 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(bkbcs_gamestatefulset_pod_update_duration_seconds_sum{cluster_id=\"$cluster_id\",status=\"success\"}) by(exported_namespace,name)/sum(bkbcs_gamestatefulset_pod_update_duration_seconds_count{status=\"success\"}) by(exported_namespace,name))",
     "legendFormat": "{{exported_namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "pod更新失败耗时top10的gets资源",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 126 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(bkbcs_gamestatefulset_pod_update_duration_seconds_sum{cluster_id=\"$cluster_id\",status=\"failure\"}) by(exported_namespace,name)/sum(bkbcs_gamestatefulset_pod_update_duration_seconds_count{status=\"failure\"}) by(exported_namespace,name))",
     "legendFormat": "{{exported_namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "各gsts更新pod成功次数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 134 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_gamestatefulset_pod_update_duration_seconds_count{cluster_id=\"$cluster_id\",status=\"success\"}) by(exported_namespace,name)",
     "legendFormat": "{{exported_namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "各gsts更新pod失败次数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 134 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_gamestatefulset_pod_update_duration_seconds_count{cluster_id=\"$cluster_id\",status=\"failure\"}) by(exported_namespace,name)",
     "legendFormat": "{{exported_namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "pod更新耗时极值情况",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 141 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(bkbcs_gamestatefulset_pod_update_duration_seconds_max{cluster_id=\"$cluster_id\"}) by(status)",
     "legendFormat": "{{status}}_max"
    },
    {
     "expr": "min(bkbcs_gamestatefulset_pod_update_duration_seconds_min{cluster_id=\"$cluster_id\"}) by(status)",
     "legendFormat": "{{status}}_min"
    }
   ]
  }
 ]
}