{
 "title": "operator monitor",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster_id",
    "query": "label_values(bkbcs_rest_client_requests_total{},cluster_id)"
   },
   {
    "name": "instance",
    "query": "label_values(bkbcs_workqueue_adds_total{cluster_id=\"$cluster_id\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "队列元素增长速率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bkbcs_workqueue_adds_total{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}[5m])) by (instance, name)",
     "legendFormat": "{{instance}}-{{name}}"
    }
   ]
  },
  {
   "title": "队列长度增长速率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bkbcs_workqueue_depth{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}[5m])) by (instance, name)"
    }
   ]
  },
  {
   "title": "队列处理元素到处理完成耗时",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(bkbcs_workqueue_work_duration_seconds_bucket{cluster_id=~\"$cluster_id\", instance=~\"$instance\"}[5m])) by (instance, name, le))",
     "legendFormat": "{{instance}}-{{name}}"
    }
   ]
  },
  {
   "title": "队列长度",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bkbcs_workqueue_depth{cluster_id=~\"$cluster_id\"}) by(instance, name)"
    }
   ]
  },
  {
   "title": "队列添加元素到处理耗时",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(bkbcs_workqueue_queue_duration_seconds_bucket{cluster_id=~\"$cluster_id\",instance=~\"$instance\"}[5m])) by (instance, name, le))",
     "legendFormat": "{{instance}}-{{name}}"
    }
   ]
  },
  {
   "title": "Kube API Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bkbcs_rest_client_requests_total{cluster_id=~\"$cluster_id\", instance=~\"$instance\",code=~\"2..\"}[5m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(bkbcs_rest_client_requests_total{cluster_id=~\"$cluster_id\",instance=~\"$instance\",code=~\"3..\"}[5m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(bkbcs_rest_client_requests_total{cluster_id=~\"$cluster_id\",instance=~\"$instance\",code=~\"4..\"}[5m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(bkbcs_rest_client_requests_total{cluster_id=~\"$cluster_id\",instance=~\"$instance\",code=~\"5..\"}[5m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Request Latency 99th Quantile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(bkbcs_rest_client_request_duration_seconds_bucket{cluster_id=~\"$cluster_id\", instance=~\"$instance\", verb=\"POST\"}[5m])) by (verb, url, le))",
     "legendFormat": "{{verb}} {{url}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(bkbcs_rest_client_request_duration_seconds_bucket{cluster_id=~\"$cluster_id\", instance=~\"$instance\", verb=\"GET\"}[5m])) by (verb, url, le))",
     "legendFormat": "{{verb}} {{url}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(bkbcs_rest_client_request_duration_seconds_bucket{cluster_id=~\"$cluster_id\", instance=~\"$instance\", verb=\"PUT\"}[5m])) by (verb, url, le))",
     "legendFormat": "{{verb}} {{url}}"
    }
   ]
  }
 ]
}