# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸智云PaaS平台社区版 (BlueKing PaaS Community
Edition) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://opensource.org/licenses/MIT

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""
# Generated by Django 1.11.23 on 2021-04-21 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=32, verbose_name='创建者')),
                ('updator', models.CharField(max_length=32, verbose_name='修改着')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_time', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=256)),
                ('project_id', models.CharField(max_length=32)),
                ('cluster_id', models.CharField(max_length=32)),
                ('namespace', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('deployed', 'deployed'), ('failed', 'failed'), ('unknown', 'unknown')], default='pending', max_length=32)),
                ('message', models.TextField(default='')),
                ('template_id', models.IntegerField(verbose_name='关联model Template')),
            ],
            options={
                'db_table': 'templatesets_app_release',
            },
        ),
        migrations.CreateModel(
            name='ResourceInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=32, verbose_name='创建者')),
                ('updator', models.CharField(max_length=32, verbose_name='修改着')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_time', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('namespace', models.CharField(max_length=64)),
                ('manifest', jsonfield.fields.JSONField()),
                ('version', models.CharField(max_length=255, verbose_name='模板集版本名')),
                ('revision', models.CharField(max_length=32, verbose_name='模板集版本名的修订版号')),
                ('edited', models.BooleanField(default=False, verbose_name='是否在线编辑过')),
                ('app_release', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='templatesets.AppRelease')),
            ],
            options={
                'db_table': 'templatesets_resource_instance',
            },
        ),
    ]
