#!/bin/bash

#######################################
# Tencent is pleased to support the open source community by making Blueking Container Service available.
# Copyright (C) 2019 THL A29 Limited, a Tencent company. All rights reserved.
# Licensed under the MIT License (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
# http://opensource.org/licenses/MIT
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific language governing permissions and
# limitations under the License.
#######################################

set -euo pipefail

SELF_DIR=$(dirname "$(readlink -f "$0")")
ROOT_DIR="${SELF_DIR}/.."

safe_source() {
  local source_file=$1
  if [[ -f ${source_file} ]]; then
    #shellcheck source=/dev/null
    source "${source_file}"
  else
    echo "[ERROR]: FAIL to source, missing ${source_file}"
    exit 1
  fi
  return 0
}

_yum_containerd() {
  trap "utils::on_ERR;" ERR

  local yum_repo repo_file
  repo_file="${ROOT_DIR}/docker-ce.repo"
  if [[ -n "${MIRROR_URL:-}" ]]; then
    yum_repo="${MIRROR_URL}/docker-ce/linux/centos/docker-ce.repo"
    curl -fsSL "$yum_repo" \
      | sed "s#https://download.docker.com#${MIRROR_URL}/docker-ce#g" \
      | tee "${repo_file}"
    [[ ! -f /etc/tlinux-release ]] \
      || sed -i "s/\$releasever/7/g" "$ROOT_DIR/docker-ce.repo"
  else
    yum_repo="https://download.docker.com/linux/centos/docker-ce.repo"
    curl -fsSL "$yum_repo" -O "${repo_file}"
  fi
  utils::log "DEBUG" "containerd yum repo: ${yum_repo}"

  [[ ! -f /etc/yum.repos.d/tlinux-docker-ce.repo ]] \
    || mv /etc/yum.repos.d/tlinux-docker-ce.repo /etc/yum.repos.d/tlinux-docker-ce.repo.bak

  yum install -y -q yum-utils
  yum-config-manager --add-repo "${repo_file}"
  yum clean all
  yum makecache fast

  local pkg_pat pkg_ver
  pkg_pat="${CONTAINERD_VER//-/.*}.*el"
  pkg_ver="$(yum list containerd.io --showduplicates \
    | awk '/'"$pkg_pat"'/{last=$2} END{sub(/.*:/,"",last);print last}')"
  [[ -n $pkg_ver ]] \
    || utils::log "ERROR" "${CONTAINERD_VER} not found amongst yum list results"

  yum -y install containerd.io-"$pkg_ver" \
    || utils::log "ERROR" "fail to yum install docker"
  "${ROOT_DIR}"/k8s/operate_completion ctr
  return 0
}

# ToDo: config separte
render_containerd() {
  trap "utils::on_ERR;" ERR

  local config_path img_mirrors_path
  config_path="/etc/containerd/config.toml"
  img_mirrors_path="/etc/containerd/certs.d/docker.io/hosts.yaml"

  install -dv "${CONTAINERD_LIB}" "/etc/containerd/certs.d/docker.io"

  if [[ -s "${config_path}" ]] \
    && [[ ! -f "${config_path}.bcs.bak" ]]; then
    utils::log "WARN" "${config_path} exist, backing up"
    cp -av "${config_path}"{,.bcs.bak} || utils::log "ERROR" "fail to backup ${config_path}"
  fi
  utils::log "INFO" "init containerd config:"

  local sandbox_img_url
  if [[ -n ${BK_PUBLIC_REPO:-} ]]; then
    sandbox_img_url="${BK_PUBLIC_REPO}/k8s.gcr.io/pause:3.6"
  else
    sandbox_img_url="registry.k8s.io/pause:3.6"
  fi

  cat <<EOF | tee ${config_path}
version = 2
# persistent data location
root = "${CONTAINERD_LIB}"
# set lower OOM score, make containerd can be killable
oom_score = -999
# debug config
[debug]
level = "info"

# sandbox image
[plugins."io.containerd.grpc.v1.cri"]
sandbox_image = "${sandbox_img_url}"

# set storage-driver
[plugins."io.containerd.grpc.v1.cri".containerd]
  snapshotter = "overlayfs"
  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
    runtime_type = "io.containerd.runc.v2"
    [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
      SystemdCgroup = true
# set registry root dir
[plugins."io.containerd.grpc.v1.cri".registry]
  config_path = "/etc/containerd/certs.d"
EOF

  if [[ -s ${img_mirrors_path} ]] && [[ ! -f ${img_mirrors_path}.bcs.bak ]]; then
    utils::log "WARN" "${img_mirrors_path} exist, backing up"
    cp -av "${img_mirrors_path}"{,.bcs.bak} \
      || utils::log "ERROR" "fail to backup ${img_mirrors_path}"
  fi
  cat <<EOF >/etc/containerd/certs.d/docker.io/hosts.toml
server = "https://docker.io"
[host."${REPO_MIRRORS}"]
  capabilities = ["pull", "resolve"]
EOF

  utils::log "INFO" "Render containerd config complete"
}

main() {
  trap "utils::on_ERR;" ERR

  local source_files
  source_files=("${ROOT_DIR}/functions/utils.sh" "${ROOT_DIR}/env/bcs.env")
  for file in "${source_files[@]}"; do
    safe_source "$file"
  done

  if ctr version &>/dev/null; then
    utils::log "WARN" "containerd installed, $(ctr -v)"
  else
    if [[ -n ${BCS_OFFLINE:-} ]]; then
      # ToDo offline install containerd
      true
    else
      _yum_containerd
    fi
  fi

  render_containerd
  systemctl daemon-reload
  systemctl enable --now containerd
  systemctl restart containerd

  # install testing
  if ! ctr --version; then
    utils::log "ERROR" "Did containerd get installed?"
  fi

  # function testing
  local test_img_url
  test_img_url=${BK_PUBLIC_REPO:-"docker.io"}/library/hello-world:latest
  utils::log "DEBUG" "hello-world: ${test_img_url}"

  if [[ -n ${BCS_OFFLINE:-} ]]; then
    # ToDo hello world image offline install
    true
  fi

  if ! (ctr i pull --hosts-dir "/etc/containerd/certs.d" "$test_img_url" \
    && ctr run --rm "$test_img_url" hello-world."$(date +%s)"); then
    utils::log "ERROR" "Could not get containerd to run ${test_img_url}"
  fi
  return 0
}
main
