#!/bin/bash

#######################################
# Tencent is pleased to support the open source community by making Blueking Container Service available.
# Copyright (C) 2019 THL A29 Limited, a Tencent company. All rights reserved.
# Licensed under the MIT License (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
# http://opensource.org/licenses/MIT
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific language governing permissions and
# limitations under the License.
#######################################

set -euo pipefail

# install k8s bin tool: kubeadm\kubelet\kubectl
SELF_DIR=$(dirname "$(readlink -f "$0")")
ROOT_DIR="${SELF_DIR}/.."
readonly SELF_DIR ROOT_DIR

add_yum_repo() {
  local repo_url basearch
  basearch="$(uname -m)"
  if [[ -z ${MIRROR_URL:-} ]]; then
    repo_url="https://packages.cloud.google.com/yum/repos/kubernetes-el7-${basearch}"
  else
    repo_url="${MIRROR_URL}/kubernetes/yum/repos/kubernetes-el7-${basearch}"
  fi
  utils::log "DEBUG" "kubernete yum repo url: ${repo_url}"

  cat >"$ROOT_DIR/kubernetes.repo" <<EOF
[kubernetes]
name=Kubernetes
baseurl=${repo_url}
enabled=1
gpgcheck=0
EOF
  yum install -y -q yum-utils
  yum-config-manager --add-repo "$ROOT_DIR/kubernetes.repo"
  yum clean all
  yum makecache fast || yum makecache
}

#######################################
# check file and source
# Arguments:
# $1: source_file
# Return:
# if file exists, source return 0; else exit 1
#######################################
safe_source() {
  local source_file=$1
  if [[ -f ${source_file} ]]; then
    #shellcheck source=/dev/null
    source "${source_file}"
  else
    echo "[ERROR]: FAIL to source, missing ${source_file}" >&2
    exit 1
  fi
}

_yum_k8s() {
  add_yum_repo

  local pkg_pat pkg_ver
  pkg_pat="${K8S_VER:-}"
  pkg_ver="$(yum list kubeadm --showduplicates \
    | awk '/'"$pkg_pat"'/{last=$2} END{sub(/.*:/,"",last);print last}')"
  [[ -n $pkg_ver ]] \
    || utils::log "ERROR" "${K8S_VER:-} not found amongst yum list results"
  local crictl_pat crictl_ver
  crictl_pat=$(awk '/crictl:/{gsub("\"","",$2);print $2;exit}' "${ROOT_DIR}"/env/offline-manifest.yaml)

  crictl_ver=$(yum list cri-tools --showduplicates \
    | awk '/'"${crictl_pat}"'/{last=$2} END{sub(/.*:/,"",last);print last}')

  yum install -y "kubeadm-${pkg_ver}" "kubelet-${pkg_ver}" "kubectl-${pkg_ver}" "cri-tools-${crictl_ver}"
}

_curl_k8s() {
  local bin_path name ver file url
  bin_path=${ROOT_DIR}/version-${K8S_VER}/bin-tools/
  mkdir -p "$bin_path"

  name="k8s"
  ver=$(awk \
    '/version: \"'"${K8S_VER}"'\"/{f=1;next} f && /'"${name}"':/{gsub("\"","",$2);print $2;exit}' \
    "${ROOT_DIR}"/env/offline-manifest.yaml)
  file="${name}-${ver}.tgz"
  url=${REPO_URL:-}/${file}
  if curl -sSfL "${url}" -o "${bin_path}/${file}" -m "360"; then
    utils::log "INFO" "Downloaded ${url}"
  else
    utils::log "ERROR" "fail to download ${url}"
  fi

  name="crictl"
  ver=$(awk \
    '/version: \"'"${K8S_VER}"'\"/{f=1;next} f && /'"${name}"':/{gsub("\"","",$2);print $2;exit}' \
    "${ROOT_DIR}"/env/offline-manifest.yaml)
  file="${name}-${ver}.tgz"
  url="${REPO_URL}/${file}"
  if curl -sSfL "${url}" -o "${bin_path}/${file}" -m "360"; then
    utils::log "INFO" "Downloaded ${url}"
  else
    utils::log "ERROR" "fail to download ${url}"
  fi

  name="cni-plugins"
  ver=$(awk \
    '/version: \"'"${K8S_VER}"'\"/{f=1;next} f && /'"${name}"':/{gsub("\"","",$2);print $2;exit}' \
    "${ROOT_DIR}"/env/offline-manifest.yaml)
  file="${name}-${ver}.tgz"
  url="${REPO_URL}/${file}"
  if curl -sSfL "${url}" -o "${bin_path}/${file}" -m "360"; then
    utils::log "INFO" "Downloaded ${url}"
  else
    utils::log "ERROR" "fail to download ${url}"
  fi

  _offline_k8s
}

_offline_k8s() {
  local bin_path tar_name
  bin_path=${ROOT_DIR}/version-${K8S_VER}/bin-tools/

  tar_name=$(find "$bin_path" -iname "k8s-*.tgz" -type f | head -1)
  if [[ -z ${tar_name} ]]; then
    utils::log "FATAL" "can't find docker installation package in ${bin_path}"
  else
    tar xvzf "${tar_name}" -C /usr/bin/ --strip-components=1 bin/
    tar xvzf "${tar_name}" -C /etc/systemd/system/ --strip-components=1 systemd/
    mkdir -pv /etc/systemd/system/kubelet.service.d/
    tar xvzf "${tar_name}" -C /etc/systemd/system/kubelet.service.d/ \
      --strip-components=1 systemd/10-kubeadm.conf
  fi

  tar_name=$(find "$bin_path" -iname "crictl-*.tgz" -type f | head -1)
  if [[ -z ${tar_name} ]]; then
    utils::log "FATAL" "can't find docker installation package in ${bin_path}"
  else
    tar xvzf "${tar_name}" -C /usr/bin/ --strip-components=1 bin/
  fi

  tar_name=$(find "$bin_path" -iname "cni-plugins-*.tgz" -type f | head -1)
  if [[ -z ${tar_name} ]]; then
    utils::log "FATAL" "can't find docker installation package in ${bin_path}"
  else
    mkdir -pv /opt/cni/bin
    tar xvzf "${tar_name}" -C /opt/cni/bin --strip-components=1 bin/
  fi
}

config_crictl() {
  local sock config_file
  config_file="/etc/crictl.yaml"
  [[ -f $config_file ]] || touch $config_file
  case "${CRI_TYPE,,}" in
    "docker")
      sock="unix:///var/run/dockershim.sock"
      ;;
    "containerd")
      sock="unix:///run/containerd/containerd.sock"
      ;;
    *)
      # ToDo: Unified standard error code
      export ERR_CODE=1
      utils::log FATAL "unkown CRI_TYPE:$CRI_TYPE"
      ;;
  esac
  crictl config runtime-endpoint $sock
  crictl config image-endpoint $sock
  "${ROOT_DIR}"/k8s/operate_completion crictl
}

main() {
  local source_files
  source_files=("${ROOT_DIR}/functions/utils.sh" "${ROOT_DIR}/env/bcs.env")
  for file in "${source_files[@]}"; do
    safe_source "$file"
  done

  if [[ -n ${BCS_OFFLINE:-} ]]; then
    _offline_k8s
  else
    case ${INSTALL_METHOD} in
      "yum")
        _yum_k8s
        ;;
      "curl")
        _curl_k8s
        ;;
      *)
        utils::log "ERROR" "unkown ${INSTALL_METHOD} to exec download k8s tools"
        ;;
    esac
  fi

  config_crictl

  utils::log "INFO" "check kubeadm status"
  if kubeadm version -o short; then
    utils::log "OK" "kubeadm install success"
  else
    utils::log "ERROR" "Did kubeadm get installed?"
  fi
  "${ROOT_DIR}"/k8s/operate_completion kubeadm

  utils::log "INFO" "check kubelet status"
  if kubelet --version; then
    utils::log "OK" "kubeadm install success"
  else
    utils::log "ERROR" "Did kubelet get installed?"
  fi

  utils::log "INFO" "check kubectl status"
  if kubectl version --client --short; then
    utils::log "OK" "kubelet install success"
  else
    utils::log "ERROR" "Did kubectl get installed?"
  fi
  "${ROOT_DIR}"/k8s/operate_completion kubectl

  return 0
}

main
