#!/bin/bash

#######################################
# Tencent is pleased to support the open source community by making Blueking Container Service available.
# Copyright (C) 2019 THL A29 Limited, a Tencent company. All rights reserved.
# Licensed under the MIT License (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
# http://opensource.org/licenses/MIT
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific language governing permissions and
# limitations under the License.
#######################################

set -euo pipefail

#######################################
# install localpv chart
# Arguments:
# $1: mount_dir, default /mnt/blueking
#######################################

LOCALPV_VER="v2.4.0"
PROGRAM="$(basename "$0")"

SELF_DIR=$(dirname "$(readlink -f "$0")")
ROOT_DIR="${SELF_DIR}/.."

readonly LOCALPV_VER PROGRAM SELF_DIR ROOT_DIR

usage_and_exit() {
  cat <<EOF
Usage:
    $PROGRAM
      [ -h --help -?  show usage ]
      [ -v -V --version show script version]
EOF
  exit "$1"
}

version() {
  echo "$PROGRAM version $LOCALPV_VER"
}

safe_source() {
  local source_file=$1
  if [[ -f ${source_file} ]]; then
    #shellcheck source=/dev/null
    source "${source_file}"
  else
    echo "[ERROR]: FAIL to source, missing ${source_file}" >&2
    exit 1
  fi
}

install_localpv() {
  local namespace="bk-system"
  kubectl get ns "$namespace" || kubectl create ns $namespace

  if [[ -n ${BCS_OFFLINE:-} ]]; then
    chart_path="$(find "${ROOT_DIR}/charts/" -name "provisioner-${LOCALPV_VER}.tgz" -type f)"
    if [[ -z $chart_path ]]; then
      utils::log "FATAL" "can't find provisioner chart in ${ROOT_DIR}/version-${K8S_VER}/charts/"
    fi
  fi

  local image
  if [[ -n ${BK_PUBLIC_REPO:-} ]]; then
    image="${BK_PUBLIC_REPO}/k8s.gcr.io/sig-storage/local-volume-provisioner:${LOCALPV_VER}"
  else
    image="registry.k8s.io/sig-storage/local-volume-provisioner:${LOCALPV_VER}"
  fi

  utils::log "INFO" "installing localpv"
  cat <<EOF | helm upgrade --install provisioner blueking/provisioner -n $namespace --version ${LOCALPV_VER} --debug -f - || utils::log "FATAL" "helm upgrade localpv failed"
daemonset:
  image: ${image}
classes:
- name: local-storage
  hostDir: "${LOCALPV_DST_DIR:-"/mnt/blueking"}"
  volumeMode: Filesystem
  storageClass:
    # create and set storage class as default
    isDefaultClass: true
    reclaimPolicy: "${LOCALPV_reclaimPolicy:-"Delete"}"
EOF
  kubectl -n $namespace get daemonset -l app.kubernetes.io/instance=localpv --output name \
    | xargs -I{} kubectl -n $namespace rollout status --timeout=600s {}
  utils::log "OK" "localpv installed"
}

main() {
  local source_files
  source_files=("${ROOT_DIR}/functions/utils.sh" "${ROOT_DIR}/functions/k8s.sh" "${ROOT_DIR}/env/bcs.env")
  for file in "${source_files[@]}"; do
    safe_source "$file"
  done
  install_localpv
}
main
