all:
	@cd middle-services && make
	@cd atomic-services && make

server:
	@cd middle-services && make server
	@cd atomic-services && make server

clean:
	@cd middle-services && make clean
	@cd atomic-services && make clean
