// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/meshmanager/meshmanager.proto

package meshmanager

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ErrCode error code
type ErrCode int32

const (
	// 0 Sunccess
	ErrCode_ERROR_OK ErrCode = 0
	// 91000 mesh cluster failed
	ErrCode_ERROR_MESH_CLUSTER_FAILED ErrCode = 91000
)

var ErrCode_name = map[int32]string{
	0:     "ERROR_OK",
	91000: "ERROR_MESH_CLUSTER_FAILED",
}

var ErrCode_value = map[string]int32{
	"ERROR_OK":                  0,
	"ERROR_MESH_CLUSTER_FAILED": 91000,
}

func (x ErrCode) String() string {
	return proto.EnumName(ErrCode_name, int32(x))
}

func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6ddc37088f698422, []int{0}
}

type CreateMeshClusterReq struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Clusterid            string   `protobuf:"bytes,2,opt,name=clusterid,proto3" json:"clusterid,omitempty"`
	Meshtype             string   `protobuf:"bytes,3,opt,name=meshtype,proto3" json:"meshtype,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Namespace            string   `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMeshClusterReq) Reset()         { *m = CreateMeshClusterReq{} }
func (m *CreateMeshClusterReq) String() string { return proto.CompactTextString(m) }
func (*CreateMeshClusterReq) ProtoMessage()    {}
func (*CreateMeshClusterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ddc37088f698422, []int{0}
}

func (m *CreateMeshClusterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMeshClusterReq.Unmarshal(m, b)
}
func (m *CreateMeshClusterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMeshClusterReq.Marshal(b, m, deterministic)
}
func (m *CreateMeshClusterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMeshClusterReq.Merge(m, src)
}
func (m *CreateMeshClusterReq) XXX_Size() int {
	return xxx_messageInfo_CreateMeshClusterReq.Size(m)
}
func (m *CreateMeshClusterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMeshClusterReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMeshClusterReq proto.InternalMessageInfo

func (m *CreateMeshClusterReq) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *CreateMeshClusterReq) GetClusterid() string {
	if m != nil {
		return m.Clusterid
	}
	return ""
}

func (m *CreateMeshClusterReq) GetMeshtype() string {
	if m != nil {
		return m.Meshtype
	}
	return ""
}

func (m *CreateMeshClusterReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateMeshClusterReq) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type CreateMeshClusterResp struct {
	Seq                  uint64   `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	ErrCode              ErrCode  `protobuf:"varint,2,opt,name=errCode,proto3,enum=meshmanager.ErrCode" json:"errCode,omitempty"`
	ErrMsg               string   `protobuf:"bytes,3,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMeshClusterResp) Reset()         { *m = CreateMeshClusterResp{} }
func (m *CreateMeshClusterResp) String() string { return proto.CompactTextString(m) }
func (*CreateMeshClusterResp) ProtoMessage()    {}
func (*CreateMeshClusterResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ddc37088f698422, []int{1}
}

func (m *CreateMeshClusterResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMeshClusterResp.Unmarshal(m, b)
}
func (m *CreateMeshClusterResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMeshClusterResp.Marshal(b, m, deterministic)
}
func (m *CreateMeshClusterResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMeshClusterResp.Merge(m, src)
}
func (m *CreateMeshClusterResp) XXX_Size() int {
	return xxx_messageInfo_CreateMeshClusterResp.Size(m)
}
func (m *CreateMeshClusterResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMeshClusterResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMeshClusterResp proto.InternalMessageInfo

func (m *CreateMeshClusterResp) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *CreateMeshClusterResp) GetErrCode() ErrCode {
	if m != nil {
		return m.ErrCode
	}
	return ErrCode_ERROR_OK
}

func (m *CreateMeshClusterResp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

type DeleteMeshClusterReq struct {
	Clusterid            string   `protobuf:"bytes,2,opt,name=clusterid,proto3" json:"clusterid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMeshClusterReq) Reset()         { *m = DeleteMeshClusterReq{} }
func (m *DeleteMeshClusterReq) String() string { return proto.CompactTextString(m) }
func (*DeleteMeshClusterReq) ProtoMessage()    {}
func (*DeleteMeshClusterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ddc37088f698422, []int{2}
}

func (m *DeleteMeshClusterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMeshClusterReq.Unmarshal(m, b)
}
func (m *DeleteMeshClusterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMeshClusterReq.Marshal(b, m, deterministic)
}
func (m *DeleteMeshClusterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMeshClusterReq.Merge(m, src)
}
func (m *DeleteMeshClusterReq) XXX_Size() int {
	return xxx_messageInfo_DeleteMeshClusterReq.Size(m)
}
func (m *DeleteMeshClusterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMeshClusterReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMeshClusterReq proto.InternalMessageInfo

func (m *DeleteMeshClusterReq) GetClusterid() string {
	if m != nil {
		return m.Clusterid
	}
	return ""
}

type DeleteMeshClusterResp struct {
	Seq                  uint64   `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	ErrCode              ErrCode  `protobuf:"varint,2,opt,name=errCode,proto3,enum=meshmanager.ErrCode" json:"errCode,omitempty"`
	ErrMsg               string   `protobuf:"bytes,3,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMeshClusterResp) Reset()         { *m = DeleteMeshClusterResp{} }
func (m *DeleteMeshClusterResp) String() string { return proto.CompactTextString(m) }
func (*DeleteMeshClusterResp) ProtoMessage()    {}
func (*DeleteMeshClusterResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ddc37088f698422, []int{3}
}

func (m *DeleteMeshClusterResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMeshClusterResp.Unmarshal(m, b)
}
func (m *DeleteMeshClusterResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMeshClusterResp.Marshal(b, m, deterministic)
}
func (m *DeleteMeshClusterResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMeshClusterResp.Merge(m, src)
}
func (m *DeleteMeshClusterResp) XXX_Size() int {
	return xxx_messageInfo_DeleteMeshClusterResp.Size(m)
}
func (m *DeleteMeshClusterResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMeshClusterResp.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMeshClusterResp proto.InternalMessageInfo

func (m *DeleteMeshClusterResp) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *DeleteMeshClusterResp) GetErrCode() ErrCode {
	if m != nil {
		return m.ErrCode
	}
	return ErrCode_ERROR_OK
}

func (m *DeleteMeshClusterResp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

type ListMeshClusterReq struct {
	Clusterid            string   `protobuf:"bytes,2,opt,name=clusterid,proto3" json:"clusterid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListMeshClusterReq) Reset()         { *m = ListMeshClusterReq{} }
func (m *ListMeshClusterReq) String() string { return proto.CompactTextString(m) }
func (*ListMeshClusterReq) ProtoMessage()    {}
func (*ListMeshClusterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ddc37088f698422, []int{4}
}

func (m *ListMeshClusterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMeshClusterReq.Unmarshal(m, b)
}
func (m *ListMeshClusterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMeshClusterReq.Marshal(b, m, deterministic)
}
func (m *ListMeshClusterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMeshClusterReq.Merge(m, src)
}
func (m *ListMeshClusterReq) XXX_Size() int {
	return xxx_messageInfo_ListMeshClusterReq.Size(m)
}
func (m *ListMeshClusterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMeshClusterReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListMeshClusterReq proto.InternalMessageInfo

func (m *ListMeshClusterReq) GetClusterid() string {
	if m != nil {
		return m.Clusterid
	}
	return ""
}

type MeshCluster struct {
	Version              string                    `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Clusterid            string                    `protobuf:"bytes,2,opt,name=clusterid,proto3" json:"clusterid,omitempty"`
	Components           map[string]*InstallStatus `protobuf:"bytes,3,rep,name=components,proto3" json:"components,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *MeshCluster) Reset()         { *m = MeshCluster{} }
func (m *MeshCluster) String() string { return proto.CompactTextString(m) }
func (*MeshCluster) ProtoMessage()    {}
func (*MeshCluster) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ddc37088f698422, []int{5}
}

func (m *MeshCluster) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeshCluster.Unmarshal(m, b)
}
func (m *MeshCluster) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeshCluster.Marshal(b, m, deterministic)
}
func (m *MeshCluster) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeshCluster.Merge(m, src)
}
func (m *MeshCluster) XXX_Size() int {
	return xxx_messageInfo_MeshCluster.Size(m)
}
func (m *MeshCluster) XXX_DiscardUnknown() {
	xxx_messageInfo_MeshCluster.DiscardUnknown(m)
}

var xxx_messageInfo_MeshCluster proto.InternalMessageInfo

func (m *MeshCluster) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *MeshCluster) GetClusterid() string {
	if m != nil {
		return m.Clusterid
	}
	return ""
}

func (m *MeshCluster) GetComponents() map[string]*InstallStatus {
	if m != nil {
		return m.Components
	}
	return nil
}

type InstallStatus struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace            string   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstallStatus) Reset()         { *m = InstallStatus{} }
func (m *InstallStatus) String() string { return proto.CompactTextString(m) }
func (*InstallStatus) ProtoMessage()    {}
func (*InstallStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ddc37088f698422, []int{6}
}

func (m *InstallStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstallStatus.Unmarshal(m, b)
}
func (m *InstallStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstallStatus.Marshal(b, m, deterministic)
}
func (m *InstallStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstallStatus.Merge(m, src)
}
func (m *InstallStatus) XXX_Size() int {
	return xxx_messageInfo_InstallStatus.Size(m)
}
func (m *InstallStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_InstallStatus.DiscardUnknown(m)
}

var xxx_messageInfo_InstallStatus proto.InternalMessageInfo

func (m *InstallStatus) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InstallStatus) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *InstallStatus) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *InstallStatus) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ListMeshClusterResp struct {
	Seq                  uint64         `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	ErrCode              ErrCode        `protobuf:"varint,2,opt,name=errCode,proto3,enum=meshmanager.ErrCode" json:"errCode,omitempty"`
	ErrMsg               string         `protobuf:"bytes,3,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	MeshClusters         []*MeshCluster `protobuf:"bytes,4,rep,name=meshClusters,proto3" json:"meshClusters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListMeshClusterResp) Reset()         { *m = ListMeshClusterResp{} }
func (m *ListMeshClusterResp) String() string { return proto.CompactTextString(m) }
func (*ListMeshClusterResp) ProtoMessage()    {}
func (*ListMeshClusterResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ddc37088f698422, []int{7}
}

func (m *ListMeshClusterResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMeshClusterResp.Unmarshal(m, b)
}
func (m *ListMeshClusterResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMeshClusterResp.Marshal(b, m, deterministic)
}
func (m *ListMeshClusterResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMeshClusterResp.Merge(m, src)
}
func (m *ListMeshClusterResp) XXX_Size() int {
	return xxx_messageInfo_ListMeshClusterResp.Size(m)
}
func (m *ListMeshClusterResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMeshClusterResp.DiscardUnknown(m)
}

var xxx_messageInfo_ListMeshClusterResp proto.InternalMessageInfo

func (m *ListMeshClusterResp) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *ListMeshClusterResp) GetErrCode() ErrCode {
	if m != nil {
		return m.ErrCode
	}
	return ErrCode_ERROR_OK
}

func (m *ListMeshClusterResp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *ListMeshClusterResp) GetMeshClusters() []*MeshCluster {
	if m != nil {
		return m.MeshClusters
	}
	return nil
}

func init() {
	proto.RegisterEnum("meshmanager.ErrCode", ErrCode_name, ErrCode_value)
	proto.RegisterType((*CreateMeshClusterReq)(nil), "meshmanager.CreateMeshClusterReq")
	proto.RegisterType((*CreateMeshClusterResp)(nil), "meshmanager.CreateMeshClusterResp")
	proto.RegisterType((*DeleteMeshClusterReq)(nil), "meshmanager.DeleteMeshClusterReq")
	proto.RegisterType((*DeleteMeshClusterResp)(nil), "meshmanager.DeleteMeshClusterResp")
	proto.RegisterType((*ListMeshClusterReq)(nil), "meshmanager.ListMeshClusterReq")
	proto.RegisterType((*MeshCluster)(nil), "meshmanager.MeshCluster")
	proto.RegisterMapType((map[string]*InstallStatus)(nil), "meshmanager.MeshCluster.ComponentsEntry")
	proto.RegisterType((*InstallStatus)(nil), "meshmanager.InstallStatus")
	proto.RegisterType((*ListMeshClusterResp)(nil), "meshmanager.ListMeshClusterResp")
}

func init() {
	proto.RegisterFile("proto/meshmanager/meshmanager.proto", fileDescriptor_6ddc37088f698422)
}

var fileDescriptor_6ddc37088f698422 = []byte{
	// 1022 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0x4d, 0x6c, 0xdb, 0x54,
	0x1c, 0xe7, 0x35, 0x69, 0xbb, 0xbd, 0x76, 0x34, 0x7b, 0xed, 0x86, 0x1b, 0x3a, 0xc5, 0xf3, 0x84,
	0x54, 0x99, 0xe5, 0xa3, 0x2e, 0x1f, 0x55, 0x10, 0x07, 0x27, 0x0d, 0x5a, 0x47, 0x42, 0xd1, 0x0b,
	0x1c, 0x40, 0xa0, 0xca, 0x73, 0x1f, 0x69, 0x58, 0x62, 0x7b, 0x7e, 0x6e, 0x51, 0x35, 0x21, 0x8d,
	0x1d, 0xd0, 0x3a, 0x31, 0x90, 0x0c, 0x42, 0x9a, 0x5a, 0x4d, 0x80, 0xa6, 0x49, 0x48, 0x9c, 0xd9,
	0x54, 0xa6, 0xc1, 0x89, 0x13, 0xa7, 0x72, 0xe6, 0xb6, 0xa4, 0x1b, 0x17, 0xae, 0x1c, 0x91, 0x9f,
	0x9d, 0xc4, 0x8e, 0x9d, 0x16, 0x21, 0x0e, 0xbb, 0xbc, 0xf7, 0x7b, 0xff, 0x8f, 0xe7, 0xff, 0x57,
	0x7e, 0x79, 0xf0, 0x8c, 0x61, 0xea, 0x96, 0x9e, 0x6d, 0x12, 0xba, 0xd6, 0x54, 0x34, 0xa5, 0x46,
	0x4c, 0x3f, 0xce, 0x30, 0x2d, 0x1a, 0xf3, 0x89, 0x92, 0x33, 0x35, 0x5d, 0xaf, 0x35, 0x48, 0x56,
	0x31, 0xea, 0x59, 0x45, 0xd3, 0x74, 0x4b, 0xb1, 0xea, 0xba, 0x46, 0x5d, 0xd3, 0xe4, 0x59, 0xb6,
	0xa9, 0xe9, 0x1a, 0xd1, 0xd2, 0xf4, 0x23, 0xa5, 0xe6, 0x5c, 0xa8, 0x1b, 0xcc, 0x22, 0x6c, 0x2d,
	0xdc, 0x8f, 0xc1, 0xa9, 0xa2, 0x49, 0x14, 0x8b, 0x54, 0x08, 0x5d, 0x2b, 0x36, 0xd6, 0xa9, 0x45,
	0x4c, 0x4c, 0x2e, 0xa1, 0x2c, 0x1c, 0xdd, 0x20, 0x26, 0xad, 0xeb, 0x1a, 0x07, 0x78, 0x30, 0x7b,
	0xb4, 0x70, 0xc2, 0x96, 0x91, 0xd8, 0x91, 0x49, 0x1d, 0x80, 0x3b, 0x00, 0xbd, 0x0c, 0x8f, 0xaa,
	0xae, 0x7b, 0x7d, 0x95, 0x1b, 0x62, 0x2e, 0xd3, 0xb6, 0x7c, 0x52, 0xec, 0x49, 0xa5, 0x1e, 0xc4,
	0x3d, 0x88, 0xe6, 0xe1, 0x11, 0x27, 0x3b, 0x6b, 0xd3, 0x20, 0x5c, 0x8c, 0xf9, 0x3d, 0x63, 0xcb,
	0x53, 0x62, 0x57, 0x28, 0x75, 0x11, 0xee, 0x22, 0x74, 0x06, 0xc6, 0x35, 0xa5, 0x49, 0xb8, 0x38,
	0x73, 0x98, 0xb0, 0xe5, 0x71, 0x91, 0x09, 0x24, 0xb6, 0x62, 0xb6, 0x3a, 0x21, 0x39, 0x3b, 0x35,
	0x14, 0x95, 0x70, 0xc3, 0xbe, 0x90, 0xba, 0x52, 0xa9, 0x07, 0x71, 0x0f, 0xe6, 0xef, 0x00, 0x5b,
	0xfe, 0x0e, 0x40, 0x2c, 0x46, 0xd6, 0x46, 0x9a, 0x6e, 0x5d, 0xdb, 0x6e, 0xfd, 0xb4, 0x7b, 0x71,
	0x81, 0x3e, 0xde, 0xfe, 0x74, 0xff, 0xc1, 0x6d, 0x27, 0xaa, 0xf6, 0xce, 0x8d, 0xd6, 0xf5, 0x6f,
	0xf7, 0x40, 0xa7, 0x1e, 0x7b, 0xa0, 0x97, 0xe2, 0x1e, 0xe8, 0x25, 0x53, 0x46, 0xe7, 0x2f, 0xf3,
	0x82, 0x67, 0x24, 0xe4, 0x79, 0x61, 0x2e, 0xf3, 0x62, 0xe6, 0x05, 0xe1, 0x2c, 0x2f, 0x74, 0xcd,
	0x1d, 0x69, 0xa1, 0x58, 0x4d, 0x57, 0x4a, 0xd5, 0xe5, 0x6a, 0x7a, 0x2e, 0x97, 0x9b, 0x97, 0x1c,
	0x7d, 0xe7, 0x0a, 0x47, 0x5d, 0xa7, 0x56, 0x5d, 0x17, 0x3e, 0x16, 0x7e, 0x00, 0xf0, 0x44, 0x44,
	0x88, 0xd4, 0x40, 0x29, 0x18, 0xa3, 0xe4, 0x12, 0xeb, 0x5d, 0xbc, 0x70, 0xcc, 0x96, 0xa1, 0xe8,
	0x9c, 0x25, 0x67, 0xc1, 0xce, 0x82, 0x4a, 0x70, 0x94, 0x98, 0x66, 0x51, 0x5f, 0x25, 0xac, 0x5b,
	0x4f, 0x4b, 0x53, 0x19, 0xff, 0xdc, 0x95, 0x5c, 0x9d, 0xd7, 0x76, 0xcf, 0x52, 0xea, 0x00, 0xdc,
	0x01, 0xe8, 0x79, 0x38, 0x42, 0x4c, 0xb3, 0x42, 0x6b, 0x5e, 0xef, 0x26, 0x6d, 0x39, 0x21, 0x7a,
	0x22, 0xc9, 0xdb, 0xb1, 0xb7, 0x0b, 0x77, 0x01, 0x9c, 0x5a, 0x24, 0x0d, 0x12, 0x9a, 0xb6, 0xff,
	0x3a, 0x3c, 0xf9, 0x0f, 0x6c, 0x59, 0x85, 0xaf, 0x8a, 0x91, 0xb7, 0x3a, 0x7d, 0xfa, 0xe6, 0xf1,
	0xcd, 0xdb, 0x91, 0x7d, 0xf2, 0xdd, 0x2c, 0x20, 0xfe, 0xf2, 0xc1, 0xd5, 0x77, 0x0b, 0x1d, 0xf1,
	0x8d, 0x27, 0xb5, 0xd0, 0x7f, 0x00, 0x88, 0xca, 0x75, 0x6a, 0xfd, 0x5f, 0x65, 0xbe, 0x01, 0x6c,
	0x79, 0x0b, 0x40, 0x55, 0x9c, 0xec, 0xbb, 0x95, 0xd5, 0xb9, 0xfc, 0xe8, 0xf3, 0xbb, 0xad, 0x2f,
	0xbe, 0x8e, 0xa8, 0xf3, 0xfe, 0xf5, 0x1f, 0xdb, 0x57, 0x3e, 0xf9, 0xeb, 0xfe, 0x67, 0xad, 0x3b,
	0x57, 0xdb, 0xb7, 0x76, 0xba, 0x17, 0x3e, 0xbc, 0xb7, 0xbb, 0xff, 0xfd, 0x6e, 0xeb, 0xda, 0xcd,
	0x47, 0x3f, 0x7f, 0xd5, 0xda, 0xbe, 0xd5, 0xde, 0xba, 0xd2, 0xde, 0xd9, 0x72, 0x9d, 0xff, 0x55,
	0x3b, 0xfe, 0x04, 0x70, 0xcc, 0x17, 0x05, 0xe2, 0xfa, 0xd8, 0xaa, 0x47, 0x4b, 0x33, 0xa1, 0x94,
	0xfd, 0xdc, 0x73, 0x0e, 0x42, 0x55, 0x6f, 0x1a, 0xba, 0x46, 0x34, 0x8b, 0x72, 0x31, 0x3e, 0x36,
	0x3b, 0x26, 0xcd, 0x06, 0xda, 0xe3, 0xfb, 0x4a, 0xa6, 0xd8, 0x35, 0x2d, 0x69, 0x96, 0xb9, 0x89,
	0x7d, 0xbe, 0xc9, 0x77, 0xe0, 0x44, 0x9f, 0x1a, 0x25, 0x60, 0xec, 0x22, 0xd9, 0xf4, 0x02, 0x72,
	0x20, 0xca, 0xc1, 0xe1, 0x0d, 0xa5, 0xb1, 0xee, 0x0e, 0xc2, 0x98, 0x94, 0x0c, 0x7c, 0x69, 0x49,
	0xa3, 0x96, 0xd2, 0x68, 0x54, 0x2d, 0xc5, 0x5a, 0xa7, 0xd8, 0x35, 0xcc, 0x0f, 0x2d, 0x00, 0x81,
	0xc2, 0x63, 0x01, 0x1d, 0x42, 0x1e, 0xf9, 0xb9, 0x37, 0xbb, 0x5c, 0x37, 0xe3, 0xe7, 0x3a, 0x2f,
	0xcf, 0xae, 0x00, 0x9d, 0x84, 0x23, 0x94, 0xf9, 0xba, 0xc3, 0x83, 0xbd, 0x93, 0x53, 0xb7, 0x26,
	0xa1, 0x54, 0xa9, 0x79, 0x4c, 0x8a, 0x3b, 0x47, 0x61, 0x6b, 0x08, 0x4e, 0x86, 0x26, 0xe8, 0x09,
	0x1d, 0x77, 0xf4, 0x3e, 0x1c, 0x6f, 0xf6, 0xe2, 0xa4, 0x5c, 0x9c, 0x35, 0x92, 0x1b, 0xd4, 0xc8,
	0x42, 0xca, 0x96, 0x67, 0xc4, 0x80, 0x8b, 0x14, 0x38, 0xe1, 0xc0, 0x49, 0x5c, 0x80, 0xa3, 0x5e,
	0xd8, 0x68, 0x1c, 0x1e, 0x29, 0x61, 0xbc, 0x8c, 0x57, 0x96, 0x5f, 0x4f, 0x3c, 0x85, 0x52, 0x70,
	0xda, 0x3d, 0x55, 0x4a, 0xd5, 0x73, 0x2b, 0xc5, 0xf2, 0xdb, 0xd5, 0xb7, 0x4a, 0x78, 0xe5, 0x35,
	0x79, 0xa9, 0x5c, 0x5a, 0x4c, 0xfc, 0xfd, 0xeb, 0xb0, 0xf4, 0x5b, 0xdc, 0x9d, 0xd3, 0x8a, 0x1b,
	0x04, 0xfa, 0x05, 0xc0, 0xe3, 0x21, 0xbe, 0x46, 0xa7, 0x03, 0x81, 0x46, 0xfd, 0xe5, 0x24, 0x85,
	0xc3, 0x4c, 0xa8, 0x21, 0xac, 0xda, 0xf2, 0x4b, 0x68, 0xf0, 0x7f, 0x53, 0x72, 0xb0, 0xea, 0xea,
	0xef, 0x0f, 0xbf, 0x1c, 0x7a, 0x4e, 0xe0, 0xb3, 0x17, 0x54, 0x9a, 0x76, 0xc4, 0xe9, 0xce, 0x53,
	0x64, 0x63, 0x8e, 0xbd, 0x46, 0xbc, 0x5f, 0x4c, 0x1e, 0x88, 0xe8, 0x1e, 0x80, 0xc7, 0x43, 0x4c,
	0xd8, 0x97, 0x42, 0x14, 0x1b, 0xf7, 0xa5, 0x10, 0x49, 0xa6, 0xc2, 0x7b, 0x5e, 0x0a, 0x03, 0x68,
	0x3b, 0x39, 0x58, 0xc5, 0x52, 0x38, 0x25, 0x3e, 0x1b, 0x78, 0x48, 0x05, 0xa3, 0x47, 0x0f, 0x00,
	0x9c, 0xe8, 0x9b, 0x69, 0x94, 0x0a, 0x44, 0x15, 0xe6, 0xcc, 0x24, 0x7f, 0xb0, 0x01, 0x35, 0x84,
	0x35, 0x5b, 0x2e, 0xa0, 0xd4, 0x21, 0x1c, 0x98, 0x3c, 0xcc, 0xc0, 0x4d, 0x00, 0x1d, 0x94, 0x40,
	0xa1, 0x61, 0xcb, 0xe7, 0xd1, 0x69, 0xc8, 0x15, 0x1b, 0xfa, 0xfa, 0x2a, 0xff, 0x06, 0xb1, 0x28,
	0x31, 0x37, 0xea, 0x2a, 0xe1, 0xe5, 0x37, 0x97, 0xf8, 0x45, 0x5d, 0x95, 0x86, 0x73, 0x99, 0x5c,
	0x66, 0x4e, 0x04, 0x40, 0x4a, 0x28, 0x86, 0xd1, 0xa8, 0xab, 0xec, 0xb1, 0x97, 0xfd, 0x90, 0xea,
	0x5a, 0x3e, 0x24, 0x79, 0xf7, 0x54, 0xe8, 0xe9, 0xf9, 0x8a, 0x0f, 0x5f, 0x18, 0x61, 0xea, 0xf9,
	0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x98, 0x23, 0xd7, 0xb6, 0xa2, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MeshManagerClient is the client API for MeshManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MeshManagerClient interface {
	CreateMeshCluster(ctx context.Context, in *CreateMeshClusterReq, opts ...grpc.CallOption) (*CreateMeshClusterResp, error)
	DeleteMeshCluster(ctx context.Context, in *DeleteMeshClusterReq, opts ...grpc.CallOption) (*DeleteMeshClusterResp, error)
	ListMeshCluster(ctx context.Context, in *ListMeshClusterReq, opts ...grpc.CallOption) (*ListMeshClusterResp, error)
}

type meshManagerClient struct {
	cc *grpc.ClientConn
}

func NewMeshManagerClient(cc *grpc.ClientConn) MeshManagerClient {
	return &meshManagerClient{cc}
}

func (c *meshManagerClient) CreateMeshCluster(ctx context.Context, in *CreateMeshClusterReq, opts ...grpc.CallOption) (*CreateMeshClusterResp, error) {
	out := new(CreateMeshClusterResp)
	err := c.cc.Invoke(ctx, "/meshmanager.MeshManager/CreateMeshCluster", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshManagerClient) DeleteMeshCluster(ctx context.Context, in *DeleteMeshClusterReq, opts ...grpc.CallOption) (*DeleteMeshClusterResp, error) {
	out := new(DeleteMeshClusterResp)
	err := c.cc.Invoke(ctx, "/meshmanager.MeshManager/DeleteMeshCluster", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshManagerClient) ListMeshCluster(ctx context.Context, in *ListMeshClusterReq, opts ...grpc.CallOption) (*ListMeshClusterResp, error) {
	out := new(ListMeshClusterResp)
	err := c.cc.Invoke(ctx, "/meshmanager.MeshManager/ListMeshCluster", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MeshManagerServer is the server API for MeshManager service.
type MeshManagerServer interface {
	CreateMeshCluster(context.Context, *CreateMeshClusterReq) (*CreateMeshClusterResp, error)
	DeleteMeshCluster(context.Context, *DeleteMeshClusterReq) (*DeleteMeshClusterResp, error)
	ListMeshCluster(context.Context, *ListMeshClusterReq) (*ListMeshClusterResp, error)
}

// UnimplementedMeshManagerServer can be embedded to have forward compatible implementations.
type UnimplementedMeshManagerServer struct {
}

func (*UnimplementedMeshManagerServer) CreateMeshCluster(ctx context.Context, req *CreateMeshClusterReq) (*CreateMeshClusterResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMeshCluster not implemented")
}
func (*UnimplementedMeshManagerServer) DeleteMeshCluster(ctx context.Context, req *DeleteMeshClusterReq) (*DeleteMeshClusterResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMeshCluster not implemented")
}
func (*UnimplementedMeshManagerServer) ListMeshCluster(ctx context.Context, req *ListMeshClusterReq) (*ListMeshClusterResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMeshCluster not implemented")
}

func RegisterMeshManagerServer(s *grpc.Server, srv MeshManagerServer) {
	s.RegisterService(&_MeshManager_serviceDesc, srv)
}

func _MeshManager_CreateMeshCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMeshClusterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshManagerServer).CreateMeshCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meshmanager.MeshManager/CreateMeshCluster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshManagerServer).CreateMeshCluster(ctx, req.(*CreateMeshClusterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshManager_DeleteMeshCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMeshClusterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshManagerServer).DeleteMeshCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meshmanager.MeshManager/DeleteMeshCluster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshManagerServer).DeleteMeshCluster(ctx, req.(*DeleteMeshClusterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshManager_ListMeshCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMeshClusterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshManagerServer).ListMeshCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meshmanager.MeshManager/ListMeshCluster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshManagerServer).ListMeshCluster(ctx, req.(*ListMeshClusterReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _MeshManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "meshmanager.MeshManager",
	HandlerType: (*MeshManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMeshCluster",
			Handler:    _MeshManager_CreateMeshCluster_Handler,
		},
		{
			MethodName: "DeleteMeshCluster",
			Handler:    _MeshManager_DeleteMeshCluster_Handler,
		},
		{
			MethodName: "ListMeshCluster",
			Handler:    _MeshManager_ListMeshCluster_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/meshmanager/meshmanager.proto",
}
