# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making 蓝鲸智云PaaS平台社区版 (BlueKing PaaS Community
Edition) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://opensource.org/licenses/MIT

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""
# Generated by Django 1.11.5 on 2018-03-12 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0023_auto_20180313_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='k8sdaemonset',
            name='deploy_tag',
            field=models.CharField(
                default='', help_text='每次保存时会生成新的应用记录，用deploy_tag来记录与其他资源的关联关系', max_length=32, verbose_name='pod 标识'),
        ),
        migrations.AddField(
            model_name='k8sjob',
            name='deploy_tag',
            field=models.CharField(
                default='', help_text='每次保存时会生成新的应用记录，用deploy_tag来记录与其他资源的关联关系', max_length=32, verbose_name='pod 标识'),
        ),
        migrations.AddField(
            model_name='k8sstatefulset',
            name='deploy_tag',
            field=models.CharField(
                default='', help_text='每次保存时会生成新的应用记录，用deploy_tag来记录与其他资源的关联关系', max_length=32, verbose_name='pod 标识'),
        ),
        migrations.AlterField(
            model_name='k8sservice',
            name='deploy_tag_list',
            field=models.TextField(
                help_text='可以关联多个Pod,json格式存储，选填', verbose_name='关联的Deployment ID'),
        ),
        migrations.AlterField(
            model_name='k8sstatefulset',
            name='service_tag',
            field=models.CharField(
                max_length=32, verbose_name='关联的K8sService 标识'),
        ),
    ]
