# Generated by Django 3.2.2 on 2022-02-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0037_showversion_version_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='creator',
            field=models.CharField(max_length=64, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='application',
            name='updator',
            field=models.CharField(max_length=64, verbose_name='更新者'),
        ),
        migrations.AlterField(
            model_name='configmap',
            name='creator',
            field=models.CharField(max_length=64, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='configmap',
            name='updator',
            field=models.CharField(max_length=64, verbose_name='更新者'),
        ),
        migrations.AlterField(
            model_name='deplpyment',
            name='creator',
            field=models.CharField(max_length=64, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='deplpyment',
            name='updator',
            field=models.CharField(max_length=64, verbose_name='更新者'),
        ),
        migrations.AlterField(
            model_name='hpa',
            name='creator',
            field=models.CharField(max_length=64, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='hpa',
            name='updator',
            field=models.CharField(max_length=64, verbose_name='更新者'),
        ),
        migrations.AlterField(
            model_name='ingress',
            name='creator',
            field=models.CharField(max_length=64, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='ingress',
            name='updator',
            field=models.CharField(max_length=64, verbose_name='更新者'),
        ),
        migrations.AlterField(
            model_name='k8sconfigmap',
            name='creator',
            field=models.CharField(max_length=64, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='k8sconfigmap',
            name='updator',
            field=models.CharField(max_length=64, verbose_name='更新者'),
        ),
        migrations.AlterField(
            model_name='k8sdaemonset',
            name='creator',
            field=models.CharField(max_length=64, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='k8sdaemonset',
            name='updator',
            field=models.CharField(max_length=64, verbose_name='更新者'),
        ),
        migrations.AlterField(
            model_name='k8sdeployment',
            name='creator',
            field=models.CharField(max_length=64, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='k8sdeployment',
            name='updator',
            field=models.CharField(max_length=64, verbose_name='更新者'),
        ),
        migrations.AlterField(
            model_name='k8shpa',
            name='creator',
            field=models.CharField(max_length=64, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='k8shpa',
            name='updator',
            field=models.CharField(max_length=64, verbose_name='更新者'),
        ),
        migrations.AlterField(
            model_name='k8singress',
            name='creator',
            field=models.CharField(max_length=64, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='k8singress',
            name='updator',
            field=models.CharField(max_length=64, verbose_name='更新者'),
        ),
        migrations.AlterField(
            model_name='k8sjob',
            name='creator',
            field=models.CharField(max_length=64, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='k8sjob',
            name='updator',
            field=models.CharField(max_length=64, verbose_name='更新者'),
        ),
        migrations.AlterField(
            model_name='k8ssecret',
            name='creator',
            field=models.CharField(max_length=64, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='k8ssecret',
            name='updator',
            field=models.CharField(max_length=64, verbose_name='更新者'),
        ),
        migrations.AlterField(
            model_name='k8sservice',
            name='creator',
            field=models.CharField(max_length=64, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='k8sservice',
            name='updator',
            field=models.CharField(max_length=64, verbose_name='更新者'),
        ),
        migrations.AlterField(
            model_name='k8sstatefulset',
            name='creator',
            field=models.CharField(max_length=64, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='k8sstatefulset',
            name='updator',
            field=models.CharField(max_length=64, verbose_name='更新者'),
        ),
        migrations.AlterField(
            model_name='resourcefile',
            name='creator',
            field=models.CharField(max_length=64, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='resourcefile',
            name='updator',
            field=models.CharField(max_length=64, verbose_name='更新者'),
        ),
        migrations.AlterField(
            model_name='secret',
            name='creator',
            field=models.CharField(max_length=64, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='secret',
            name='updator',
            field=models.CharField(max_length=64, verbose_name='更新者'),
        ),
        migrations.AlterField(
            model_name='service',
            name='creator',
            field=models.CharField(max_length=64, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='service',
            name='updator',
            field=models.CharField(max_length=64, verbose_name='更新者'),
        ),
        migrations.AlterField(
            model_name='showversion',
            name='creator',
            field=models.CharField(max_length=64, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='showversion',
            name='updator',
            field=models.CharField(max_length=64, verbose_name='更新者'),
        ),
        migrations.AlterField(
            model_name='template',
            name='creator',
            field=models.CharField(max_length=64, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='template',
            name='draft_updator',
            field=models.CharField(default='', max_length=64, verbose_name='草稿更新者'),
        ),
        migrations.AlterField(
            model_name='template',
            name='updator',
            field=models.CharField(max_length=64, verbose_name='更新者'),
        ),
        migrations.AlterField(
            model_name='versionedentity',
            name='creator',
            field=models.CharField(max_length=64, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='versionedentity',
            name='updator',
            field=models.CharField(max_length=64, verbose_name='更新者'),
        ),
    ]
