create database bscpdb;

use bscpdb;

CREATE TABLE `t_business` (
  `Fid` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `Fbid` varchar(64) NOT NULL,
  `Fname` varchar(64) NOT NULL,
  `Fdepid` varchar(64) NOT NULL,
  `Fcreator` varchar(64) NOT NULL,
  `Flast_modify_by` varchar(64) NOT NULL,
  `Fmemo` varchar(64) NOT NULL,
  `Fauth` varchar(64) NOT NULL default '',
  `Fstate` int(11) DEFAULT NULL,
  `Fcreate_time` timestamp NULL DEFAULT NULL,
  `Fupdate_time` timestamp NULL DEFAULT NULL,
  `Fdelete_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`Fid`),
  UNIQUE KEY `uix_t_business_Fbid` (`Fbid`),
  UNIQUE KEY `uix_t_business_Fname` (`Fname`),
  KEY `idx_utime` (`Fupdate_time`),
  KEY `idx_dtime` (`Fdelete_time`),
  KEY `idx_ctime` (`Fcreate_time`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `t_sharding` (
  `Fid` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `Fkey` varchar(64) NOT NULL,
  `Fdbid` varchar(64) NOT NULL,
  `Fdbname` varchar(64) NOT NULL,
  `Fmemo` varchar(64) NOT NULL,
  `Fstate` int(11) DEFAULT NULL,
  `Fcreate_time` timestamp NULL DEFAULT NULL,
  `Fupdate_time` timestamp NULL DEFAULT NULL,
  `Fdelete_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`Fid`),
  UNIQUE KEY `uix_t_sharding_Fkey` (`Fkey`),
  KEY `idx_utime` (`Fupdate_time`),
  KEY `idx_dtime` (`Fdelete_time`),
  KEY `idx_ctime` (`Fcreate_time`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `t_sharding_db` (
  `Fid` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `Fdbid` varchar(64) NOT NULL,
  `Fhost` varchar(64) NOT NULL,
  `Fport` int(11) DEFAULT NULL,
  `Fuser` varchar(32) NOT NULL,
  `Fpassword` varchar(32) NOT NULL,
  `Fmemo` varchar(64) NOT NULL,
  `Fstate` int(11) DEFAULT NULL,
  `Fcreate_time` timestamp NULL DEFAULT NULL,
  `Fupdate_time` timestamp NULL DEFAULT NULL,
  `Fdelete_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`Fid`),
  UNIQUE KEY `uix_t_sharding_db_Fdbid` (`Fdbid`),
  KEY `idx_ctime` (`Fcreate_time`),
  KEY `idx_utime` (`Fupdate_time`),
  KEY `idx_dtime` (`Fdelete_time`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

create database bscp_test;

use bscp_test;

CREATE TABLE `t_app_instance` (
  `Fid` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `Fbid` varchar(64) NOT NULL,
  `Fappid` varchar(64) NOT NULL,
  `Fclusterid` varchar(64) NOT NULL,
  `Fzoneid` varchar(64) NOT NULL,
  `Fdc` varchar(64) NOT NULL,
  `Fip` varchar(32) NOT NULL,
  `Flabels` longtext NOT NULL,
  `Fstate` int(11) DEFAULT NULL,
  `Fcreate_time` timestamp NULL DEFAULT NULL,
  `Fupdate_time` timestamp NULL DEFAULT NULL,
  `Fdelete_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`Fid`),
  UNIQUE KEY `idx_unionids` (`Fbid`,`Fappid`,`Fclusterid`,`Fzoneid`,`Fdc`,`Fip`),
  KEY `idx_ctime` (`Fcreate_time`),
  KEY `idx_utime` (`Fupdate_time`),
  KEY `idx_dtime` (`Fdelete_time`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `t_app_instance_release` (
  `Fid` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `Finstanceid` bigint(20) NOT NULL,
  `Fbid` varchar(64) NOT NULL,
  `Fappid` varchar(64) NOT NULL,
  `Fclusterid` varchar(64) NOT NULL,
  `Fzoneid` varchar(64) NOT NULL,
  `Fdc` varchar(64) NOT NULL,
  `Fip` varchar(32) NOT NULL,
  `Flabels` longtext NOT NULL,
  `Fcfgsetid` varchar(64) NOT NULL,
  `Freleaseid` varchar(64) NOT NULL,
  `Feffect_time` timestamp NULL DEFAULT NULL,
  `Feffect_code` int(11) DEFAULT '0',
  `Feffect_msg` varchar(128) DEFAULT '',
  `Freload_time` timestamp NULL DEFAULT NULL,
  `Freload_code` int(11) DEFAULT '0',
  `Freload_msg` varchar(128) DEFAULT '',
  `Fcreate_time` timestamp NULL DEFAULT NULL,
  `Fupdate_time` timestamp NULL DEFAULT NULL,
  `Fdelete_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`Fid`),
  UNIQUE KEY `idx_unionids` (`Finstanceid`,`Fcfgsetid`,`Freleaseid`),
  KEY `idx_effected` (`Fcfgsetid`,`Freleaseid`),
  KEY `idx_ctime` (`Fcreate_time`),
  KEY `idx_utime` (`Fupdate_time`),
  KEY `idx_dtime` (`Fdelete_time`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `t_application` (
  `Fid` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `Fappid` varchar(64) NOT NULL,
  `Fbid` varchar(64) NOT NULL,
  `Fname` varchar(64) NOT NULL,
  `Fdeploy_type` int(11) DEFAULT NULL,
  `Fcreator` varchar(64) NOT NULL,
  `Flast_modify_by` varchar(64) NOT NULL,
  `Fmemo` varchar(64) NOT NULL,
  `Fstate` int(11) DEFAULT NULL,
  `Fcreate_time` timestamp NULL DEFAULT NULL,
  `Fupdate_time` timestamp NULL DEFAULT NULL,
  `Fdelete_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`Fid`),
  UNIQUE KEY `uix_t_application_Fappid` (`Fappid`),
  UNIQUE KEY `idx_bidname` (`Fbid`,`Fname`),
  KEY `idx_ctime` (`Fcreate_time`),
  KEY `idx_utime` (`Fupdate_time`),
  KEY `idx_dtime` (`Fdelete_time`),
  KEY `idx_state` (`Fstate`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `t_audit` (
  `Fid` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `Fsource_type` int(11) DEFAULT NULL,
  `Fop_type` int(11) DEFAULT NULL,
  `Fbid` varchar(64) NOT NULL,
  `Fsourceid` varchar(64) NOT NULL,
  `Foperator` varchar(64) NOT NULL,
  `Fmemo` varchar(64) NOT NULL,
  `Fstate` int(11) DEFAULT NULL,
  `Fcreate_time` timestamp NULL DEFAULT NULL,
  `Fupdate_time` timestamp NULL DEFAULT NULL,
  `Fdelete_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`Fid`),
  KEY `idx_sourcetype` (`Fsource_type`),
  KEY `idx_optype` (`Fop_type`),
  KEY `idx_bid` (`Fbid`),
  KEY `idx_sourceid` (`Fsourceid`),
  KEY `idx_operator` (`Foperator`),
  KEY `idx_ctime` (`Fcreate_time`),
  KEY `idx_utime` (`Fupdate_time`),
  KEY `idx_dtime` (`Fdelete_time`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `t_cluster` (
  `Fid` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `Fclusterid` varchar(64) NOT NULL,
  `Fbid` varchar(64) NOT NULL,
  `Fappid` varchar(64) NOT NULL,
  `Fname` varchar(64) NOT NULL,
  `Flabels` varchar(128) NOT NULL DEFAULT '',
  `Frclusterid` varchar(64) NOT NULL,
  `Fcreator` varchar(64) NOT NULL,
  `Flast_modify_by` varchar(64) NOT NULL,
  `Fmemo` varchar(64) NOT NULL,
  `Fstate` int(11) DEFAULT NULL,
  `Fcreate_time` timestamp NULL DEFAULT NULL,
  `Fupdate_time` timestamp NULL DEFAULT NULL,
  `Fdelete_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`Fid`),
  UNIQUE KEY `uix_t_cluster_Fclusterid` (`Fclusterid`),
  UNIQUE KEY `idx_appidnamelabels` (`Fappid`,`Fname`,`Flabels`),
  KEY `idx_bid` (`Fbid`),
  KEY `idx_rclusterid` (`Frclusterid`),
  KEY `idx_ctime` (`Fcreate_time`),
  KEY `idx_utime` (`Fupdate_time`),
  KEY `idx_dtime` (`Fdelete_time`),
  KEY `idx_state` (`Fstate`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `t_commit` (
  `Fid` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `Fcommitid` varchar(64) NOT NULL,
  `Fbid` varchar(64) NOT NULL,
  `Fappid` varchar(64) NOT NULL,
  `Fcfgsetid` varchar(64) NOT NULL,
  `Ftemplateid` varchar(64) NOT NULL,
  `Ftemplate` longtext NOT NULL,
  `Ftemplate_rule` longtext NOT NULL,
  `Fop` int(11) DEFAULT NULL,
  `Foperator` varchar(64) NOT NULL,
  `Fprev_configs` longblob NOT NULL,
  `Fconfigs` longblob NOT NULL,
  `Fchanges` longtext NOT NULL,
  `Freleaseid` varchar(64) NOT NULL,
  `Fmulti_commitid` varchar(64) NOT NULL DEFAULT '',
  `Fmemo` varchar(64) NOT NULL,
  `Fstate` int(11) DEFAULT NULL,
  `Fcreate_time` timestamp NULL DEFAULT NULL,
  `Fupdate_time` timestamp NULL DEFAULT NULL,
  `Fdelete_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`Fid`),
  UNIQUE KEY `uix_t_commit_Fcommitid` (`Fcommitid`),
  UNIQUE KEY `uidx_multi` (`Fcfgsetid`,`Fmulti_commitid`),
  KEY `idx_operator` (`Foperator`),
  KEY `idx_releaseid` (`Freleaseid`),
  KEY `idx_bid` (`Fbid`),
  KEY `idx_appid` (`Fappid`),
  KEY `idx_configsetid` (`Fcfgsetid`),
  KEY `idx_state` (`Fstate`),
  KEY `idx_ctime` (`Fcreate_time`),
  KEY `idx_utime` (`Fupdate_time`),
  KEY `idx_dtime` (`Fdelete_time`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `t_configs` (
  `Fid` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `Fbid` varchar(64) NOT NULL,
  `Fcfgsetid` varchar(64) NOT NULL,
  `Fcommitid` varchar(64) NOT NULL,
  `Fappid` varchar(64) NOT NULL,
  `Fclusterid` varchar(64) NOT NULL,
  `Fzoneid` varchar(64) NOT NULL,
  `Findex` varchar(64) NOT NULL DEFAULT '',
  `Fcid` varchar(64) NOT NULL,
  `Fcfglink` varchar(4096) NOT NULL,
  `Fcontent` longblob NOT NULL,
  `Fcreator` varchar(64) NOT NULL,
  `Flast_modify_by` varchar(64) NOT NULL,
  `Fmemo` varchar(64) NOT NULL,
  `Fstate` int(11) DEFAULT NULL,
  `Fcreate_time` timestamp NULL DEFAULT NULL,
  `Fupdate_time` timestamp NULL DEFAULT NULL,
  `Fdelete_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`Fid`),
  UNIQUE KEY `idx_unionids` (`Fbid`,`Fcfgsetid`,`Fcommitid`,`Fappid`,`Fclusterid`,`Fzoneid`,`Findex`),
  KEY `idx_ctime` (`Fcreate_time`),
  KEY `idx_utime` (`Fupdate_time`),
  KEY `idx_dtime` (`Fdelete_time`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `t_configset` (
  `Fid` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `Fcfgsetid` varchar(64) NOT NULL,
  `Fbid` varchar(64) NOT NULL,
  `Fappid` varchar(64) NOT NULL,
  `Fname` varchar(64) NOT NULL,
  `Ffpath` varchar(128) NOT NULL,
  `Fcreator` varchar(64) NOT NULL,
  `Flast_modify_by` varchar(64) NOT NULL,
  `Fmemo` varchar(64) NOT NULL,
  `Fstate` int(11) DEFAULT NULL,
  `Fcreate_time` timestamp NULL DEFAULT NULL,
  `Fupdate_time` timestamp NULL DEFAULT NULL,
  `Fdelete_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`Fid`),
  UNIQUE KEY `uix_t_configset_Fcfgsetid` (`Fcfgsetid`),
  UNIQUE KEY `idx_appidnamepath` (`Fappid`,`Fname`,`Ffpath`),
  KEY `idx_bid` (`Fbid`),
  KEY `idx_ctime` (`Fcreate_time`),
  KEY `idx_utime` (`Fupdate_time`),
  KEY `idx_dtime` (`Fdelete_time`),
  KEY `idx_state` (`Fstate`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `t_configset_lock` (
  `Fid` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `Fcfgsetid` varchar(64) NOT NULL,
  `Foperator` varchar(64) NOT NULL,
  `Flock_time` timestamp NULL DEFAULT NULL,
  `Funlock_time` timestamp NULL DEFAULT NULL,
  `Fmemo` varchar(64) NOT NULL,
  `Fstate` int(11) DEFAULT NULL,
  `Fcreate_time` timestamp NULL DEFAULT NULL,
  `Fupdate_time` timestamp NULL DEFAULT NULL,
  `Fdelete_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`Fid`),
  UNIQUE KEY `uix_t_configset_lock_Fcfgsetid` (`Fcfgsetid`),
  KEY `idx_ctime` (`Fcreate_time`),
  KEY `idx_utime` (`Fupdate_time`),
  KEY `idx_dtime` (`Fdelete_time`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `t_multi_commit` (
  `Fid` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `Fmulti_commitid` varchar(64) NOT NULL,
  `Fbid` varchar(64) NOT NULL,
  `Fappid` varchar(64) NOT NULL,
  `Foperator` varchar(64) NOT NULL,
  `Fmulti_releaseid` varchar(64) NOT NULL,
  `Fmemo` varchar(64) NOT NULL,
  `Fstate` int(11) DEFAULT NULL,
  `Fcreate_time` timestamp NULL DEFAULT NULL,
  `Fupdate_time` timestamp NULL DEFAULT NULL,
  `Fdelete_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`Fid`),
  UNIQUE KEY `uix_t_multi_commit_Fmulti_commitid` (`Fmulti_commitid`),
  KEY `idx_bid` (`Fbid`),
  KEY `idx_appid` (`Fappid`),
  KEY `idx_operator` (`Foperator`),
  KEY `idx_releaseid` (`Fmulti_releaseid`),
  KEY `idx_state` (`Fstate`),
  KEY `idx_ctime` (`Fcreate_time`),
  KEY `idx_utime` (`Fupdate_time`),
  KEY `idx_dtime` (`Fdelete_time`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `t_multi_release` (
  `Fid` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `Fmulti_releaseid` varchar(64) NOT NULL,
  `Fname` varchar(64) NOT NULL,
  `Fbid` varchar(64) NOT NULL,
  `Fappid` varchar(64) NOT NULL,
  `Fstrategyid` varchar(64) NOT NULL,
  `Fstrategies` longtext NOT NULL,
  `Fcreator` varchar(64) NOT NULL,
  `Fmulti_commitid` varchar(64) NOT NULL,
  `Flast_modify_by` varchar(64) NOT NULL,
  `Fmemo` varchar(64) NOT NULL,
  `Fstate` int(11) DEFAULT NULL,
  `Fcreate_time` timestamp NULL DEFAULT NULL,
  `Fupdate_time` timestamp NULL DEFAULT NULL,
  `Fdelete_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`Fid`),
  UNIQUE KEY `uix_t_multi_release_Fmulti_releaseid` (`Fmulti_releaseid`),
  KEY `idx_name` (`Fname`),
  KEY `idx_bid` (`Fbid`),
  KEY `idx_appid` (`Fappid`),
  KEY `idx_ctime` (`Fcreate_time`),
  KEY `idx_utime` (`Fupdate_time`),
  KEY `idx_dtime` (`Fdelete_time`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `t_release` (
  `Fid` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `Freleaseid` varchar(64) NOT NULL,
  `Fname` varchar(64) NOT NULL,
  `Fbid` varchar(64) NOT NULL,
  `Fappid` varchar(64) NOT NULL,
  `Fcfgsetid` varchar(64) NOT NULL,
  `Fcfgsetname` varchar(64) NOT NULL,
  `Fcfgsetfpath` varchar(128) NOT NULL,
  `Fstrategyid` varchar(64) NOT NULL,
  `Fstrategies` longtext NOT NULL,
  `Fcreator` varchar(64) NOT NULL,
  `Fcommitid` varchar(64) NOT NULL,
  `Fmulti_releaseid` varchar(64) NOT NULL DEFAULT '',
  `Flast_modify_by` varchar(64) NOT NULL,
  `Fmemo` varchar(64) NOT NULL,
  `Fstate` int(11) DEFAULT NULL,
  `Fcreate_time` timestamp NULL DEFAULT NULL,
  `Fupdate_time` timestamp NULL DEFAULT NULL,
  `Fdelete_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`Fid`),
  UNIQUE KEY `uix_t_release_Freleaseid` (`Freleaseid`),
  KEY `idx_appid` (`Fappid`),
  KEY `idx_configsetid` (`Fcfgsetid`),
  KEY `idx_name` (`Fname`),
  KEY `idx_bid` (`Fbid`),
  KEY `idx_ctime` (`Fcreate_time`),
  KEY `idx_utime` (`Fupdate_time`),
  KEY `idx_dtime` (`Fdelete_time`),
  KEY `idx_mreleaseid` (`Fmulti_releaseid`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `t_strategy` (
  `Fid` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `Fstrategyid` varchar(64) NOT NULL,
  `Fappid` varchar(64) NOT NULL,
  `Fname` varchar(64) NOT NULL,
  `Fcontent` longtext NOT NULL,
  `Fcreator` varchar(64) NOT NULL,
  `Flast_modify_by` varchar(64) NOT NULL,
  `Fmemo` varchar(64) NOT NULL,
  `Fstate` int(11) DEFAULT NULL,
  `Fcreate_time` timestamp NULL DEFAULT NULL,
  `Fupdate_time` timestamp NULL DEFAULT NULL,
  `Fdelete_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`Fid`),
  UNIQUE KEY `uix_t_strategy_Fstrategyid` (`Fstrategyid`),
  UNIQUE KEY `uidx_strategy` (`Fappid`,`Fname`),
  KEY `idx_ctime` (`Fcreate_time`),
  KEY `idx_utime` (`Fupdate_time`),
  KEY `idx_dtime` (`Fdelete_time`),
  KEY `idx_state` (`Fstate`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `t_zone` (
  `Fid` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `Fzoneid` varchar(64) NOT NULL,
  `Fbid` varchar(64) NOT NULL,
  `Fappid` varchar(64) NOT NULL,
  `Fname` varchar(64) NOT NULL,
  `Fclusterid` varchar(64) NOT NULL,
  `Fcreator` varchar(64) NOT NULL,
  `Flast_modify_by` varchar(64) NOT NULL,
  `Fmemo` varchar(64) NOT NULL,
  `Fstate` int(11) DEFAULT NULL,
  `Fcreate_time` timestamp NULL DEFAULT NULL,
  `Fupdate_time` timestamp NULL DEFAULT NULL,
  `Fdelete_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`Fid`),
  UNIQUE KEY `uix_t_zone_Fzoneid` (`Fzoneid`),
  UNIQUE KEY `idx_appidname` (`Fappid`,`Fname`),
  KEY `idx_bid` (`Fbid`),
  KEY `idx_clusterid` (`Fclusterid`),
  KEY `idx_ctime` (`Fcreate_time`),
  KEY `idx_utime` (`Fupdate_time`),
  KEY `idx_dtime` (`Fdelete_time`),
  KEY `idx_state` (`Fstate`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `t_template` (
  `Fid` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `Ftemplateid` varchar(64) NOT NULL,
  `Fbid` varchar(64) NOT NULL,
  `Fsetid` varchar(64) NOT NULL,
  `Fname` varchar(64) NOT NULL,
  `Fmemo` varchar(128) DEFAULT NULL,
  `Ffpath` varchar(128) NOT NULL,
  `Fuser` varchar(64) DEFAULT NULL,
  `Fgroup` varchar(64) DEFAULT NULL,
  `Fpermission` int(11) NOT NULL,
  `Ffile_encoding` varchar(16) DEFAULT NULL,
  `Fengine_type` int(11) NOT NULL,
  `Fcreator` varchar(64) NOT NULL,
  `Flast_modify_by` varchar(64) NOT NULL,
  `Fstate` int(11) DEFAULT NULL,
  `Fcreate_time` timestamp NULL DEFAULT NULL,
  `Fupdate_time` timestamp NULL DEFAULT NULL,
  `Fdelete_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`Fid`),
  UNIQUE KEY `uix_t_template_Ftemplateid` (`Ftemplateid`),
  UNIQUE KEY `idx_set_name` (`Fsetid`,`Fname`),
  KEY `idx_bid` (`Fbid`),
  KEY `idx_ctime` (`Fcreate_time`),
  KEY `idx_utime` (`Fupdate_time`),
  KEY `idx_dtime` (`Fdelete_time`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `t_template_binding` (
  `Fid` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `Fbid` varchar(64) NOT NULL,
  `Ftemplateid` varchar(64) NOT NULL,
  `Fappid` varchar(64) NOT NULL,
  `Fversionid` varchar(64) NOT NULL,
  `Fcfgsetid` varchar(64) NOT NULL,
  `Fcommitid` varchar(64) DEFAULT NULL,
  `Fbinding_params` longtext NOT NULL,
  `Fcreator` varchar(64) NOT NULL,
  `Flast_modify_by` varchar(64) NOT NULL,
  `Fstate` int(11) DEFAULT NULL,
  `Fcreate_time` timestamp NULL DEFAULT NULL,
  `Fupdate_time` timestamp NULL DEFAULT NULL,
  `Fdelete_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`Fid`),
  UNIQUE KEY `idx_unionids` (`Fbid`,`Ftemplateid`,`Fappid`),
  KEY `idx_utime` (`Fupdate_time`),
  KEY `idx_dtime` (`Fdelete_time`),
  KEY `idx_cfgset` (`Fcfgsetid`),
  KEY `idx_ctime` (`Fcreate_time`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `t_template_set` (
  `Fid` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `Fsetid` varchar(64) NOT NULL,
  `Fbid` varchar(64) NOT NULL,
  `Fname` varchar(64) NOT NULL,
  `Fmemo` varchar(128) DEFAULT NULL,
  `Ffpath` varchar(128) NOT NULL,
  `Fcreator` varchar(64) NOT NULL,
  `Flast_modify_by` varchar(64) NOT NULL,
  `Fstate` int(11) DEFAULT NULL,
  `Fcreate_time` timestamp NULL DEFAULT NULL,
  `Fupdate_time` timestamp NULL DEFAULT NULL,
  `Fdelete_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`Fid`),
  UNIQUE KEY `uix_t_template_set_Fsetid` (`Fsetid`),
  UNIQUE KEY `idx_bid_name` (`Fbid`,`Fname`),
  KEY `idx_dtime` (`Fdelete_time`),
  KEY `idx_ctime` (`Fcreate_time`),
  KEY `idx_utime` (`Fupdate_time`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `t_template_version` (
  `Fid` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `Fversionid` varchar(64) NOT NULL,
  `Fbid` varchar(64) NOT NULL,
  `Ftemplateid` varchar(64) NOT NULL,
  `Fversion_name` varchar(64) NOT NULL,
  `Fmemo` varchar(128) DEFAULT NULL,
  `Fcontent` longtext,
  `Fcreator` varchar(64) NOT NULL,
  `Flast_modify_by` varchar(64) NOT NULL,
  `Fstate` int(11) DEFAULT NULL,
  `Fcreate_time` timestamp NULL DEFAULT NULL,
  `Fupdate_time` timestamp NULL DEFAULT NULL,
  `Fdelete_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`Fid`),
  UNIQUE KEY `uix_t_template_version_Fversionid` (`Fversionid`),
  UNIQUE KEY `idx_tpl_version` (`Ftemplateid`,`Fversion_name`),
  KEY `idx_utime` (`Fupdate_time`),
  KEY `idx_dtime` (`Fdelete_time`),
  KEY `idx_bid` (`Fbid`),
  KEY `idx_ctime` (`Fcreate_time`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `t_variable_global` (
  `Fid` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `Fvid` varchar(64) NOT NULL,
  `Fbid` varchar(64) NOT NULL,
  `Fkey` varchar(64) NOT NULL,
  `Fvalue` varchar(1024) NOT NULL,
  `Fmemo` varchar(128) DEFAULT NULL,
  `Fcreator` varchar(64) NOT NULL,
  `Flast_modify_by` varchar(64) NOT NULL,
  `Fstate` int(11) DEFAULT NULL,
  `Fcreate_time` timestamp NULL DEFAULT NULL,
  `Fupdate_time` timestamp NULL DEFAULT NULL,
  `Fdelete_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`Fid`),
  UNIQUE KEY `uix_t_variable_global_Fvid` (`Fvid`),
  UNIQUE KEY `idx_unionids` (`Fbid`,`Fkey`),
  KEY `idx_ctime` (`Fcreate_time`),
  KEY `idx_utime` (`Fupdate_time`),
  KEY `idx_dtime` (`Fdelete_time`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `t_variable_cluster` (
  `Fid` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `Fvid` varchar(64) NOT NULL,
  `Fbid` varchar(64) NOT NULL,
  `Fcluster` varchar(64) NOT NULL,
  `Fcluster_labels` varchar(128) NOT NULL,
  `Fkey` varchar(64) NOT NULL,
  `Fvalue` varchar(1024) NOT NULL,
  `Fmemo` varchar(128) DEFAULT NULL,
  `Fcreator` varchar(64) NOT NULL,
  `Flast_modify_by` varchar(64) NOT NULL,
  `Fstate` int(11) DEFAULT NULL,
  `Fcreate_time` timestamp NULL DEFAULT NULL,
  `Fupdate_time` timestamp NULL DEFAULT NULL,
  `Fdelete_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`Fid`),
  UNIQUE KEY `uix_t_variable_cluster_Fvid` (`Fvid`),
  UNIQUE KEY `idx_unionids` (`Fbid`,`Fcluster`,`Fcluster_labels`,`Fkey`),
  KEY `idx_dtime` (`Fdelete_time`),
  KEY `idx_ctime` (`Fcreate_time`),
  KEY `idx_utime` (`Fupdate_time`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `t_variable_zone` (
  `Fid` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `Fvid` varchar(64) NOT NULL,
  `Fbid` varchar(64) NOT NULL,
  `Fcluster` varchar(64) NOT NULL,
  `Fcluster_labels` varchar(128) NOT NULL,
  `Fzone` varchar(64) NOT NULL,
  `Fkey` varchar(64) NOT NULL,
  `Fvalue` varchar(2048) NOT NULL,
  `Fmemo` varchar(128) DEFAULT NULL,
  `Fcreator` varchar(64) NOT NULL,
  `Flast_modify_by` varchar(64) NOT NULL,
  `Fstate` int(11) DEFAULT NULL,
  `Fcreate_time` timestamp NULL DEFAULT NULL,
  `Fupdate_time` timestamp NULL DEFAULT NULL,
  `Fdelete_time` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`Fid`),
  UNIQUE KEY `uix_t_variable_zone_Fvid` (`Fvid`),
  UNIQUE KEY `idx_unionids` (`Fbid`,`Fcluster`,`Fcluster_labels`,`Fzone`,`Fkey`),
  KEY `idx_utime` (`Fupdate_time`),
  KEY `idx_dtime` (`Fdelete_time`),
  KEY `idx_ctime` (`Fcreate_time`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `t_proc_attr` (
 `Fid` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
 `Fcloudid` varchar(64) NOT NULL,
 `Fip` varchar(32) NOT NULL,
 `Fbid` varchar(64) NOT NULL,
 `Fappid` varchar(64) NOT NULL,
 `Fclusterid` varchar(64) NOT NULL,
 `Fzoneid` varchar(64) NOT NULL,
 `Fdc` varchar(64) NOT NULL,
 `Flabels` longtext NOT NULL,
 `Fpath` varchar(128) NOT NULL,
 `Fcreator` varchar(64) NOT NULL,
 `Flast_modify_by` varchar(64) NOT NULL,
 `Fmemo` varchar(64) NOT NULL,
 `Fstate` int(11) DEFAULT NULL,
 `Fcreate_time` datetime DEFAULT NULL,
 `Fupdate_time` datetime DEFAULT NULL,
 `Fdelete_time` datetime DEFAULT NULL,
 PRIMARY KEY (`Fid`),
 UNIQUE KEY `uidx_attr` (`Fcloudid`,`Fip`,`Fbid`,`Fappid`,`Fpath`),
 KEY `idx_state` (`Fstate`),
 KEY `idx_ctime` (`Fcreate_time`),
 KEY `idx_utime` (`Fupdate_time`),
 KEY `idx_dtime` (`Fdelete_time`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;
