#!/bin/bash
#######################################
# Tencent is pleased to support the open source community by making Blueking Container Service available.
# Copyright (C) 2019 THL A29 Limited, a Tencent company. All rights reserved.
# Licensed under the MIT License (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
# http://opensource.org/licenses/MIT
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific language governing permissions and
# limitations under the License.
#######################################

set -euo pipefail

# install jq
SELF_DIR=$(dirname "$(readlink -f "$0")")
ROOT_DIR="${SELF_DIR}/.."
readonly SELF_DIR ROOT_DIR

safe_source() {
  local source_file=$1
  if [[ -f ${source_file} ]]; then
    #shellcheck source=/dev/null
    source "${source_file}"
  else
    echo "[ERROR]: FAIL to source, missing ${source_file}"
    exit 1
  fi
}

_curl_jq() {
  local url save_file version
  version=$1
  url="${REPO_URL}/jq-${version}.xz"
  save_file="/tmp/jq.xz"
  if curl -sSfL "${url}" -o "${save_file}" -m "360"; then
    rm -f /tmp/jq
    unxz -dc ${save_file} >/tmp/jq
    chmod +x /tmp/jq
    mv /tmp/jq /usr/local/bin/jq
    rm -f ${save_file}
  else
    utils::log "ERROR" "fail to download jq"
  fi
}

_offline_jq() {
  # ToDo
  true
}

main() {
  local source_files
  source_files=("${ROOT_DIR}/functions/utils.sh" "${ROOT_DIR}/env/bcs.env")
  for file in "${source_files[@]}"; do
    safe_source "$file"
  done
  jq_ver=$(awk '/jq/{gsub("\"","",$2);print $2;exit}' \
    "${ROOT_DIR}"/env/offline-manifest.yaml)

  if ! command -v jq >/dev/null; then
    if [[ -n ${BCS_OFFLINE:-} ]]; then
      _offline_jq
    else
      _curl_jq "$jq_ver"
    fi
  fi
  utils::log "OK" "installed $(jq -V)"
}

main
