all:
	@cd bscp-apiserver && make
	@cd bscp-authserver && make
	@cd bscp-patcher && make

server:
	@cd bscp-apiserver && make
	@cd bscp-authserver && make
	@cd bscp-patcher && make

clean:
	@cd bscp-apiserver && make clean
	@cd bscp-authserver && make clean
	@cd bscp-patcher && make clean
