all:
	@cd bscp-configserver && make
	@cd bscp-templateserver && make
	@cd bscp-datamanager && make
	@cd bscp-gse-controller && make
	@cd bscp-tunnelserver && make
	@cd bscp-bcs-sidecar && make
	@cd bscp-gse-plugin && make

server:
	@cd bscp-configserver && make
	@cd bscp-templateserver && make
	@cd bscp-datamanager && make
	@cd bscp-gse-controller && make
	@cd bscp-tunnelserver && make

clean:
	@cd bscp-configserver && make clean
	@cd bscp-templateserver && make clean
	@cd bscp-datamanager && make clean
	@cd bscp-gse-controller && make clean
	@cd bscp-tunnelserver && make clean
	@cd bscp-bcs-sidecar && make clean
	@cd bscp-gse-plugin && make clean
