all:
	@cd core && make
	@cd auth-server && make
	@cd data-service && make
	@cd config-server && make
	@cd feed-server && make
	@cd cache-service && make
	@cd vault-server && make

clean:
	@cd core && make clean
	@cd auth-server && make clean
	@cd data-service && make clean
	@cd config-server && make clean
	@cd feed-server && make clean
	@cd cache-service && make clean
