all:
	@cd core && make
	@cd auth-server && make
	@cd data-service && make
	@cd config-server && make
	@cd feed-server && make
	@cd cache-service && make

clean:
	@cd core && make clean
	@cd auth-server && make clean
	@cd data-service && make clean
	@cd config-server && make clean
	@cd feed-server && make clean
	@cd cache-service && make clean

py:
	@cd core && make py
	@cd auth-server && make py
	@cd data-service && make py
	@cd config-server && make py
	@cd feed-server && make py
	@cd cache-service && make py
