# Generated by Django 3.2.2 on 2022-02-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_init_conf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conf',
            name='creator',
            field=models.CharField(max_length=64, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='conf',
            name='updator',
            field=models.CharField(max_length=64, verbose_name='修改者'),
        ),
        migrations.AlterField(
            model_name='dataid',
            name='creator',
            field=models.CharField(max_length=64, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='dataid',
            name='updator',
            field=models.CharField(max_length=64, verbose_name='修改者'),
        ),
        migrations.AlterField(
            model_name='functioncontroller',
            name='creator',
            field=models.CharField(max_length=64, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='functioncontroller',
            name='updator',
            field=models.CharField(max_length=64, verbose_name='修改者'),
        ),
        migrations.AlterField(
            model_name='functioncontroller',
            name='wlist',
            field=models.TextField(blank=True, help_text='白名单，英文分号【;】隔开', null=True, verbose_name='功能测试白名单'),
        ),
    ]
