FROM tencentos/tencentos4-minimal
MAINTAINER xxx xxx<xxx@tencent.com>
WORKDIR /
COPY ./bcs-cluster-reporter .
COPY ./TencentSans-W7.ttf .
COPY ./TencentSans-W3.ttf .
#COPY ./conf ./conf
ENTRYPOINT ["/bcs-cluster-reporter"]
