{
 "title": "BSCP-ConnServer",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values({job=\"bk-bscp-connserver\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": " 可用Access节点数",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "bscp_connserver_access_node_num",
     "legendFormat": "可用Access节点数({{instance}})"
    }
   ]
  },
  {
   "title": "BCS Sidecar会话链接数",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(bscp_connserver_connection_num)",
     "legendFormat": "全局 -- 会话链接数"
    },
    { "expr": "bscp_connserver_connection_num", "legendFormat": "单实例 -- 会话链接数({{instance}})" }
   ]
  },
  {
   "title": "实时Publishing任务数量",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bscp_connserver_publishing_task_num)",
     "legendFormat": "全局 -- Publishing任务数"
    },
    {
     "expr": "bscp_connserver_publishing_task_num",
     "legendFormat": "单实例 -- Publishing任务数({{instance}})"
    }
   ]
  },
  {
   "title": "BCS通道每秒Publishing下发数量",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(bscp_connserver_publishing_total[1m]))",
     "legendFormat": "全局 -- 每秒Publishing下发数量"
    },
    {
     "expr": "irate(bscp_connserver_publishing_total[1m])",
     "legendFormat": "单实例 -- 每秒Publishing下发数量({{instance}})"
    },
    {
     "expr": "sum(irate(bscp_connserver_publishing_err[1m]))",
     "legendFormat": "全局 -- 每秒Publishing下发失败数量"
    },
    {
     "expr": "irate(bscp_connserver_publishing_error[1m])",
     "legendFormat": "单实例 -- 每秒Publishing下发失败数量({{instance}})"
    }
   ]
  },
  {
   "title": "RPC接口成功率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(bscp_connserver_request_total{errcode=\"0\"}[5m]))/sum(rate(bscp_connserver_request_total[5m]))) * 100",
     "legendFormat": "全局 -- 成功率"
    },
    {
     "expr": "(sum(rate(bscp_connserver_request_total{errcode=\"0\",instance=\"$instance\"}[5m]))/sum(rate(bscp_connserver_request_total{instance=\"$instance\"}[5m]))) * 100",
     "legendFormat": "单实例 -- 总成功率($instance)"
    },
    {
     "expr": "(sum(rate(bscp_connserver_request_total{errcode=\"0\"}[5m])) by (rpc) / \nsum(rate(bscp_connserver_request_total[5m])) by (rpc)) * 100",
     "legendFormat": "RPC接口成功率({{rpc}})"
    },
    {
     "expr": "(sum(rate(bscp_connserver_request_total{errcode=\"0\",instance=\"$instance\"}[5m])) by (rpc) / sum(rate(bscp_connserver_request_total{instance=\"$instance\"}[5m])) by(rpc)) * 100",
     "legendFormat": "单实例 -- RPC接口成功率($instance  --  {{rpc}})"
    }
   ]
  },
  {
   "title": "错误码",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bscp_connserver_request_total{errcode=\"0\"}[5m])) by (job)",
     "legendFormat": "整体 -- Success[0]"
    },
    {
     "expr": "sum(rate(bscp_connserver_request_total{errcode!=\"0\"}[5m])) by (job)",
     "legendFormat": "整体 - Failed[!0]"
    },
    {
     "expr": "sum(rate(bscp_connserver_request_total{instance=\"$instance\",errcode=\"0\"}[5m])) by (job)",
     "legendFormat": "单实例 -- 整体Success[0] ($instance)"
    },
    {
     "expr": "sum(rate(bscp_connserver_request_total{instance=\"$instance\",errcode!=\"0\"}[5m])) by (job)",
     "legendFormat": "单实例 -- 整体Failed[!0] ($instance)"
    },
    {
     "expr": "sum(rate(bscp_connserver_request_total[5m])) by (rpc,errcode)",
     "legendFormat": "RPC接口错误码[{{errcode}}] ({{rpc}})"
    },
    {
     "expr": "sum(rate(bscp_connserver_request_total{instance=\"$instance\"}[5m])) by (rpc,errcode)",
     "legendFormat": "单实例 -- RPC接口错误码[{{errcode}}] ($instance -- {{rpc}})"
    }
   ]
  },
  {
   "title": "响应时间",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bscp_connserver_response_time_sum[5m]))/sum(rate(bscp_connserver_response_time_count[5m]))",
     "legendFormat": "整体 -- 平均响应时间"
    },
    {
     "expr": "sum(rate(bscp_connserver_response_time_sum{instance=\"$instance\"}[5m]))/sum(rate(bscp_connserver_response_time_count{instance=\"$instance\"}[5m]))",
     "legendFormat": "单实例 -- 整体平均响应时间($instance)"
    },
    {
     "expr": "sum(rate(bscp_connserver_response_time_sum[5m])) by (rpc) / sum(rate(bscp_connserver_response_time_count[5m])) by (rpc)",
     "legendFormat": "RPC接口响应时间({{rpc}})"
    },
    {
     "expr": "sum(rate(bscp_connserver_response_time_sum{instance=\"$instance\"}[5m])) by (rpc) / sum(rate(bscp_connserver_response_time_count{instance=\"$instance\"}[5m])) by (rpc)",
     "legendFormat": "单实例 -- RPC接口响应时间($instance -- {{rpc}})"
    }
   ]
  },
  {
   "title": "RPC请求",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bscp_connserver_request_total[5m])) by (job)",
     "legendFormat": "整体 -- QPS"
    },
    {
     "expr": "sum(rate(bscp_connserver_request_total{instance=\"$instance\"}[5m])) by (job)",
     "legendFormat": "单实例 -- 整体QPS($instance)"
    },
    {
     "expr": "sum(rate(bscp_connserver_request_total[5m])) by (rpc)",
     "legendFormat": " RPC接口QPS({{rpc}})"
    },
    {
     "expr": "sum(rate(bscp_connserver_request_total{instance=\"$instance\"}[5m])) by (rpc)",
     "legendFormat": "单实例 --  RPC接口QPS($instance -- {{rpc}})"
    }
   ]
  }
 ]
}