{
 "title": "BSCP-SYSTEM-STATS",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "module", "query": "label_values(job)" },
   {
    "name": "instance",
    "query": "label_values({job=\"$module\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "进程运行时长",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{job=\"$module\",instance=\"$instance\"})",
     "legendFormat": "单实例进程运行时长"
    }
   ]
  },
  {
   "title": "FD数量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=\"$module\",instance=\"$instance\"}",
     "legendFormat": "单实例FD数量"
    }
   ]
  },
  {
   "title": "GC耗时",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds_sum{job=\"$module\",instance=\"$instance\"}/go_gc_duration_seconds_count{job=\"$module\",instance=\"$instance\"}",
     "legendFormat": "单实例GC耗时"
    }
   ]
  },
  {
   "title": "内存占用",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$module\",instance=\"$instance\"}",
     "legendFormat": "单实例常驻内存"
    },
    {
     "expr": "process_virtual_memory_bytes{job=\"$module\",instance=\"$instance\"}",
     "legendFormat": "单实例虚拟内存"
    }
   ]
  },
  {
   "title": "协程数量",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"$module\",instance=\"$instance\"}",
     "legendFormat": "单实例协程数量"
    }
   ]
  },
  {
   "title": "系统线程数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_threads{job=\"$module\",instance=\"$instance\"}",
     "legendFormat": "单实例系统线程数"
    }
   ]
  }
 ]
}