{
 "title": "BSCP-AccessServer",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values({job=\"bk-bscp-accessserver\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "RPC接口成功率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(bscp_accessserver_request_total{errcode=\"0\"})/sum(bscp_accessserver_request_total)) * 100",
     "legendFormat": "全局 -- 成功率"
    },
    {
     "expr": "(sum(bscp_accessserver_request_total{errcode=\"0\",instance=\"$instance\"})/sum(bscp_accesssserver_request_total{instance=\"$instance\"})) * 100",
     "legendFormat": "单实例 -- 总成功率($instance)"
    },
    {
     "expr": "(bscp_accessserver_request_total{errcode=\"0\",instance=\"$instance\"}/bscp_accessserver_request_total{instance=\"$instance\"}) * 100",
     "legendFormat": "单实例 -- RPC接口成功率($instance  --  {{rpc}})"
    }
   ]
  },
  {
   "title": "错误码",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bscp_accessserver_request_total{errcode=\"0\"}[1h])) by (job)",
     "legendFormat": "整体 -- Success[0]"
    },
    {
     "expr": "sum(rate(bscp_accessserver_request_total{errcode!=\"0\"}[1h])) by (job)",
     "legendFormat": "整体 - Failed[!0]"
    },
    {
     "expr": "sum(rate(bscp_accessserver_request_total{instance=\"$instance\",errcode=\"0\"}[1h])) by (job)",
     "legendFormat": "单实例 -- 整体Success[0] ($instance)"
    },
    {
     "expr": "sum(rate(bscp_accessserver_request_total{instance=\"$instance\",errcode!=\"0\"}[1h])) by (job)",
     "legendFormat": "单实例 -- 整体Failed[!0] ($instance)"
    },
    {
     "expr": "rate(bscp_accessserver_request_total{instance=\"$instance\"}[1h])",
     "legendFormat": "单实例 -- RPC接口错误码[{{errcode}}] ($instance -- {{rpc}})"
    }
   ]
  },
  {
   "title": "响应时间",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(bscp_accessserver_response_time_sum)/sum(bscp_accessserver_response_time_count)",
     "legendFormat": "整体 -- 平均响应时间"
    },
    {
     "expr": "sum(bscp_accessserver_response_time_sum{instance=\"$instance\"})/sum(bscp_accessserver_response_time_count{instance=\"$instance\"})",
     "legendFormat": "单实例 -- 整体平均响应时间($instance  [$quantile])"
    },
    {
     "expr": "bscp_accessserver_response_time_sum{instance=\"$instance\"}/bscp_accessserver_response_time_count{instance=\"$instance\"}",
     "legendFormat": "单实例 -- RPC接口响应时间($instance -- {{rpc}})"
    }
   ]
  },
  {
   "title": "RPC请求",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bscp_accessserver_request_total[1h])) by (job)",
     "legendFormat": "整体 -- QPS"
    },
    {
     "expr": "sum(rate(bscp_accessserver_request_total{instance=\"$instance\"}[1h])) by (job)",
     "legendFormat": "单实例 -- 整体QPS($instance)"
    },
    {
     "expr": "rate(bscp_accessserver_request_total{instance=\"$instance\"}[1h])",
     "legendFormat": "单实例 --  RPC接口QPS($instance -- {{rpc}})"
    }
   ]
  }
 ]
}