{
 "title": "BSCP-GSE-Controller",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values({job=\"bk-bscp-gse-controller\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "RPC接口成功率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(bscp_gsecontroller_request_total{errcode=\"0\"}[5m]))/sum(rate(bscp_gsecontroller_request_total[5m]))) * 100",
     "legendFormat": "全局 -- 成功率"
    },
    {
     "expr": "(sum(rate(bscp_gsecontroller_request_total{errcode=\"0\",instance=\"$instance\"}[5m]))/sum(rate(bscp_gsecontroller_request_total{instance=\"$instance\"}[5m]))) * 100",
     "legendFormat": "单实例 -- 总成功率($instance)"
    },
    {
     "expr": "(sum(rate(bscp_gsecontroller_request_total{errcode=\"0\"}[5m])) by (rpc) / sum(rate(bscp_gsecontroller_request_total[5m])) by (rpc)) * 100",
     "legendFormat": "RPC接口成功率({{rpc}})"
    },
    {
     "expr": "(sum(rate(bscp_gsecontroller_request_total{errcode=\"0\",instance=\"$instance\"}[5m])) by (rpc) / sum(rate(bscp_gsecontroller_request_total{instance=\"$instance\"}[5m])) by (rpc)) * 100",
     "legendFormat": "单实例 -- RPC接口成功率($instance  --  {{rpc}})"
    }
   ]
  },
  {
   "title": "错误码",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bscp_gsecontroller_request_total{errcode=\"0\"}[5m])) by (job)",
     "legendFormat": "整体 -- Success[0]"
    },
    {
     "expr": "sum(rate(bscp_gsecontroller_request_total{errcode!=\"0\"}[5m])) by (job)",
     "legendFormat": "整体 - Failed[!0]"
    },
    {
     "expr": "sum(rate(bscp_gsecontroller_request_total{instance=\"$instance\",errcode=\"0\"}[5m])) by (job)",
     "legendFormat": "单实例 -- 整体Success[0] ($instance)"
    },
    {
     "expr": "sum(rate(bscp_gsecontroller_request_total{instance=\"$instance\",errcode!=\"0\"}[5m])) by (job)",
     "legendFormat": "单实例 -- 整体Failed[!0] ($instance)"
    },
    {
     "expr": "sum(rate(bscp_gsecontroller_request_total[5m])) by (rpc, errcode)",
     "legendFormat": " RPC接口错误码[{{errcode}}] ({{rpc}})"
    },
    {
     "expr": "sum(rate(bscp_gsecontroller_request_total{instance=\"$instance\"}[5m])) by (rpc, errcode)",
     "legendFormat": "单实例 -- RPC接口错误码[{{errcode}}] ($instance -- {{rpc}})"
    }
   ]
  },
  {
   "title": "响应时间",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bscp_gsecontroller_response_time_sum[5m]))/sum(rate(bscp_gsecontroller_response_time_count[5m]))",
     "legendFormat": "整体 -- 平均响应时间"
    },
    {
     "expr": "sum(rate(bscp_gsecontroller_response_time_sum{instance=\"$instance\"}[5m]))/sum(rate(bscp_gsecontroller_response_time_count{instance=\"$instance\"}[5m]))",
     "legendFormat": "单实例 -- 整体平均响应时间($instance  [$quantile])"
    },
    {
     "expr": "sum(rate(bscp_gsecontroller_response_time_sum[5m])) by (rpc) /sum(rate(bscp_gsecontroller_response_time_count[5m])) by (rpc)",
     "legendFormat": "RPC接口响应时间({{rpc}})"
    },
    {
     "expr": "sum(rate(bscp_gsecontroller_response_time_sum{instance=\"$instance\"}[5m])) by (rpc) /sum(rate(bscp_gsecontroller_response_time_count{instance=\"$instance\"}[5m])) by (rpc)",
     "legendFormat": "单实例 -- RPC接口响应时间($instance -- {{rpc}})"
    }
   ]
  },
  {
   "title": "RPC请求",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bscp_gsecontroller_request_total[5m])) by (job)",
     "legendFormat": "整体 -- QPS"
    },
    {
     "expr": "sum(rate(bscp_gsecontroller_request_total{instance=\"$instance\"}[5m])) by (job)",
     "legendFormat": "单实例 -- 整体QPS($instance)"
    },
    {
     "expr": "sum(rate(bscp_gsecontroller_request_total[5m])) by (rpc)",
     "legendFormat": " RPC接口QPS({{rpc}})"
    },
    {
     "expr": "sum(rate(bscp_gsecontroller_request_total{instance=\"$instance\"}[5m])) by (rpc)",
     "legendFormat": "单实例 --  RPC接口QPS($instance -- {{rpc}})"
    }
   ]
  }
 ]
}