# Generated by Django 3.2.2 on 2022-05-23 11:47

import backend.container_service.cluster_tools.constants
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_name', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=64, verbose_name='组件名')),
                ('default_version', models.CharField(max_length=64, verbose_name='单个组件的默认版本')),
                ('default_values', models.TextField(blank=True, help_text='组件启用时需要额外设置的变量值，文本内容格式为 yaml', null=True)),
                ('extra_options', models.TextField(default='')),
                ('namespace', models.CharField(default='bcs-system', max_length=64)),
                ('description', models.TextField(blank=True, help_text='组件功能介绍', null=True)),
                ('help_link', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.TextField(blank=True, null=True, verbose_name='图片 logo')),
                ('version', models.CharField(max_length=64, verbose_name='组件库的版本')),
            ],
        ),
        migrations.CreateModel(
            name='InstalledTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64, verbose_name='创建者')),
                ('updator', models.CharField(max_length=64, verbose_name='修改者')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_time', models.DateTimeField(blank=True, null=True)),
                ('release_name', models.CharField(max_length=53)),
                ('project_id', models.CharField(max_length=32)),
                ('cluster_id', models.CharField(max_length=32)),
                ('chart_url', models.CharField(max_length=255)),
                ('values', models.TextField(blank=True, help_text='组件启用或更新时设置的变量值，文本内容格式为 yaml', null=True)),
                ('extra_options', models.TextField(default='')),
                ('namespace', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('deployed', 'deployed'), ('failed', 'failed'), ('unknown', 'unknown')], default=backend.container_service.cluster_tools.constants.ToolStatus['PENDING'], max_length=32)),
                ('message', models.TextField(default='', verbose_name='记录错误信息')),
                ('tool', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='cluster_tools.tool')),
            ],
            options={
                'unique_together': {('tool', 'project_id', 'cluster_id')},
            },
        ),
    ]
