# Generated by Django 3.2.2 on 2022-05-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster_tools', '0002_tool_supported_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='default_version',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='单个组件的默认版本'),
        ),
    ]
