// Code generated by protoc-gen-go.
// source: master.proto
// DO NOT EDIT!

/*
Package mesos_master is a generated protocol buffer package.

It is generated from these files:
	master.proto

It has these top-level messages:
	Call
	Response
	Event
*/
package mesos_master

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import mesos "github.com/Tencent/bk-bcs/bcs-common/pkg/scheduler/mesosproto/mesos"
import mesos_maintenance "github.com/Tencent/bk-bcs/bcs-common/pkg/scheduler/mesosproto/mesos/maintenance"
import mesos_quota "github.com/Tencent/bk-bcs/bcs-common/pkg/scheduler/mesosproto/mesos/quota"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Call_Type int32

const (
	// If a call of type `Call::FOO` requires additional parameters they can be
	// included in the corresponding `Call::Foo` message. Similarly, if a call
	// receives a synchronous response it will be returned as a `Response`
	// message of type `Response::FOO`. Currently all calls except
	// `Call::SUBSCRIBE` receive synchronous responses; `Call::SUBSCRIBE` returns
	// a streaming response of `Event`.
	Call_UNKNOWN             Call_Type = 0
	Call_GET_HEALTH          Call_Type = 1
	Call_GET_FLAGS           Call_Type = 2
	Call_GET_VERSION         Call_Type = 3
	Call_GET_METRICS         Call_Type = 4
	Call_GET_LOGGING_LEVEL   Call_Type = 5
	Call_SET_LOGGING_LEVEL   Call_Type = 6
	Call_LIST_FILES          Call_Type = 7
	Call_READ_FILE           Call_Type = 8
	Call_GET_STATE           Call_Type = 9
	Call_GET_AGENTS          Call_Type = 10
	Call_GET_FRAMEWORKS      Call_Type = 11
	Call_GET_EXECUTORS       Call_Type = 12
	Call_GET_TASKS           Call_Type = 13
	Call_GET_ROLES           Call_Type = 14
	Call_GET_WEIGHTS         Call_Type = 15
	Call_UPDATE_WEIGHTS      Call_Type = 16
	Call_GET_MASTER          Call_Type = 17
	Call_SUBSCRIBE           Call_Type = 18
	Call_RESERVE_RESOURCES   Call_Type = 19
	Call_UNRESERVE_RESOURCES Call_Type = 20
	Call_CREATE_VOLUMES      Call_Type = 21
	Call_DESTROY_VOLUMES     Call_Type = 22
	// Retrieves the cluster's maintenance status.
	Call_GET_MAINTENANCE_STATUS Call_Type = 23
	// Retrieves the cluster's maintenance schedule.
	Call_GET_MAINTENANCE_SCHEDULE    Call_Type = 24
	Call_UPDATE_MAINTENANCE_SCHEDULE Call_Type = 25
	Call_START_MAINTENANCE           Call_Type = 26
	Call_STOP_MAINTENANCE            Call_Type = 27
	Call_GET_QUOTA                   Call_Type = 28
	Call_SET_QUOTA                   Call_Type = 29
	Call_REMOVE_QUOTA                Call_Type = 30
)

var Call_Type_name = map[int32]string{
	0:  "UNKNOWN",
	1:  "GET_HEALTH",
	2:  "GET_FLAGS",
	3:  "GET_VERSION",
	4:  "GET_METRICS",
	5:  "GET_LOGGING_LEVEL",
	6:  "SET_LOGGING_LEVEL",
	7:  "LIST_FILES",
	8:  "READ_FILE",
	9:  "GET_STATE",
	10: "GET_AGENTS",
	11: "GET_FRAMEWORKS",
	12: "GET_EXECUTORS",
	13: "GET_TASKS",
	14: "GET_ROLES",
	15: "GET_WEIGHTS",
	16: "UPDATE_WEIGHTS",
	17: "GET_MASTER",
	18: "SUBSCRIBE",
	19: "RESERVE_RESOURCES",
	20: "UNRESERVE_RESOURCES",
	21: "CREATE_VOLUMES",
	22: "DESTROY_VOLUMES",
	23: "GET_MAINTENANCE_STATUS",
	24: "GET_MAINTENANCE_SCHEDULE",
	25: "UPDATE_MAINTENANCE_SCHEDULE",
	26: "START_MAINTENANCE",
	27: "STOP_MAINTENANCE",
	28: "GET_QUOTA",
	29: "SET_QUOTA",
	30: "REMOVE_QUOTA",
}
var Call_Type_value = map[string]int32{
	"UNKNOWN":                     0,
	"GET_HEALTH":                  1,
	"GET_FLAGS":                   2,
	"GET_VERSION":                 3,
	"GET_METRICS":                 4,
	"GET_LOGGING_LEVEL":           5,
	"SET_LOGGING_LEVEL":           6,
	"LIST_FILES":                  7,
	"READ_FILE":                   8,
	"GET_STATE":                   9,
	"GET_AGENTS":                  10,
	"GET_FRAMEWORKS":              11,
	"GET_EXECUTORS":               12,
	"GET_TASKS":                   13,
	"GET_ROLES":                   14,
	"GET_WEIGHTS":                 15,
	"UPDATE_WEIGHTS":              16,
	"GET_MASTER":                  17,
	"SUBSCRIBE":                   18,
	"RESERVE_RESOURCES":           19,
	"UNRESERVE_RESOURCES":         20,
	"CREATE_VOLUMES":              21,
	"DESTROY_VOLUMES":             22,
	"GET_MAINTENANCE_STATUS":      23,
	"GET_MAINTENANCE_SCHEDULE":    24,
	"UPDATE_MAINTENANCE_SCHEDULE": 25,
	"START_MAINTENANCE":           26,
	"STOP_MAINTENANCE":            27,
	"GET_QUOTA":                   28,
	"SET_QUOTA":                   29,
	"REMOVE_QUOTA":                30,
}

func (x Call_Type) Enum() *Call_Type {
	p := new(Call_Type)
	*p = x
	return p
}
func (x Call_Type) String() string {
	return proto.EnumName(Call_Type_name, int32(x))
}
func (x *Call_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Call_Type_value, data, "Call_Type")
	if err != nil {
		return err
	}
	*x = Call_Type(value)
	return nil
}
func (Call_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

// Each of the responses of type `FOO` corresponds to `Foo` message below.
type Response_Type int32

const (
	Response_UNKNOWN                  Response_Type = 0
	Response_GET_HEALTH               Response_Type = 1
	Response_GET_FLAGS                Response_Type = 2
	Response_GET_VERSION              Response_Type = 3
	Response_GET_METRICS              Response_Type = 4
	Response_GET_LOGGING_LEVEL        Response_Type = 5
	Response_LIST_FILES               Response_Type = 6
	Response_READ_FILE                Response_Type = 7
	Response_GET_STATE                Response_Type = 8
	Response_GET_AGENTS               Response_Type = 9
	Response_GET_FRAMEWORKS           Response_Type = 10
	Response_GET_EXECUTORS            Response_Type = 11
	Response_GET_TASKS                Response_Type = 12
	Response_GET_ROLES                Response_Type = 13
	Response_GET_WEIGHTS              Response_Type = 14
	Response_GET_MASTER               Response_Type = 15
	Response_GET_MAINTENANCE_STATUS   Response_Type = 16
	Response_GET_MAINTENANCE_SCHEDULE Response_Type = 17
	Response_GET_QUOTA                Response_Type = 18
)

var Response_Type_name = map[int32]string{
	0:  "UNKNOWN",
	1:  "GET_HEALTH",
	2:  "GET_FLAGS",
	3:  "GET_VERSION",
	4:  "GET_METRICS",
	5:  "GET_LOGGING_LEVEL",
	6:  "LIST_FILES",
	7:  "READ_FILE",
	8:  "GET_STATE",
	9:  "GET_AGENTS",
	10: "GET_FRAMEWORKS",
	11: "GET_EXECUTORS",
	12: "GET_TASKS",
	13: "GET_ROLES",
	14: "GET_WEIGHTS",
	15: "GET_MASTER",
	16: "GET_MAINTENANCE_STATUS",
	17: "GET_MAINTENANCE_SCHEDULE",
	18: "GET_QUOTA",
}
var Response_Type_value = map[string]int32{
	"UNKNOWN":                  0,
	"GET_HEALTH":               1,
	"GET_FLAGS":                2,
	"GET_VERSION":              3,
	"GET_METRICS":              4,
	"GET_LOGGING_LEVEL":        5,
	"LIST_FILES":               6,
	"READ_FILE":                7,
	"GET_STATE":                8,
	"GET_AGENTS":               9,
	"GET_FRAMEWORKS":           10,
	"GET_EXECUTORS":            11,
	"GET_TASKS":                12,
	"GET_ROLES":                13,
	"GET_WEIGHTS":              14,
	"GET_MASTER":               15,
	"GET_MAINTENANCE_STATUS":   16,
	"GET_MAINTENANCE_SCHEDULE": 17,
	"GET_QUOTA":                18,
}

func (x Response_Type) Enum() *Response_Type {
	p := new(Response_Type)
	*p = x
	return p
}
func (x Response_Type) String() string {
	return proto.EnumName(Response_Type_name, int32(x))
}
func (x *Response_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Response_Type_value, data, "Response_Type")
	if err != nil {
		return err
	}
	*x = Response_Type(value)
	return nil
}
func (Response_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type Event_Type int32

const (
	Event_UNKNOWN       Event_Type = 0
	Event_SUBSCRIBED    Event_Type = 1
	Event_TASK_ADDED    Event_Type = 2
	Event_TASK_UPDATED  Event_Type = 3
	Event_AGENT_ADDED   Event_Type = 4
	Event_AGENT_REMOVED Event_Type = 5
)

var Event_Type_name = map[int32]string{
	0: "UNKNOWN",
	1: "SUBSCRIBED",
	2: "TASK_ADDED",
	3: "TASK_UPDATED",
	4: "AGENT_ADDED",
	5: "AGENT_REMOVED",
}
var Event_Type_value = map[string]int32{
	"UNKNOWN":       0,
	"SUBSCRIBED":    1,
	"TASK_ADDED":    2,
	"TASK_UPDATED":  3,
	"AGENT_ADDED":   4,
	"AGENT_REMOVED": 5,
}

func (x Event_Type) Enum() *Event_Type {
	p := new(Event_Type)
	*p = x
	return p
}
func (x Event_Type) String() string {
	return proto.EnumName(Event_Type_name, int32(x))
}
func (x *Event_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Event_Type_value, data, "Event_Type")
	if err != nil {
		return err
	}
	*x = Event_Type(value)
	return nil
}
func (Event_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

// *
// Calls that can be sent to the v1 master API.
//
// A call is described using the standard protocol buffer "union"
// trick, see
// https://developers.google.com/protocol-buffers/docs/techniques#union.
type Call struct {
	Type                      *Call_Type                      `protobuf:"varint,1,opt,name=type,enum=mesos.v1.master.Call_Type" json:"type,omitempty"`
	GetMetrics                *Call_GetMetrics                `protobuf:"bytes,2,opt,name=get_metrics,json=getMetrics" json:"get_metrics,omitempty"`
	SetLoggingLevel           *Call_SetLoggingLevel           `protobuf:"bytes,3,opt,name=set_logging_level,json=setLoggingLevel" json:"set_logging_level,omitempty"`
	ListFiles                 *Call_ListFiles                 `protobuf:"bytes,4,opt,name=list_files,json=listFiles" json:"list_files,omitempty"`
	ReadFile                  *Call_ReadFile                  `protobuf:"bytes,5,opt,name=read_file,json=readFile" json:"read_file,omitempty"`
	UpdateWeights             *Call_UpdateWeights             `protobuf:"bytes,6,opt,name=update_weights,json=updateWeights" json:"update_weights,omitempty"`
	ReserveResources          *Call_ReserveResources          `protobuf:"bytes,7,opt,name=reserve_resources,json=reserveResources" json:"reserve_resources,omitempty"`
	UnreserveResources        *Call_UnreserveResources        `protobuf:"bytes,8,opt,name=unreserve_resources,json=unreserveResources" json:"unreserve_resources,omitempty"`
	CreateVolumes             *Call_CreateVolumes             `protobuf:"bytes,9,opt,name=create_volumes,json=createVolumes" json:"create_volumes,omitempty"`
	DestroyVolumes            *Call_DestroyVolumes            `protobuf:"bytes,10,opt,name=destroy_volumes,json=destroyVolumes" json:"destroy_volumes,omitempty"`
	UpdateMaintenanceSchedule *Call_UpdateMaintenanceSchedule `protobuf:"bytes,11,opt,name=update_maintenance_schedule,json=updateMaintenanceSchedule" json:"update_maintenance_schedule,omitempty"`
	StartMaintenance          *Call_StartMaintenance          `protobuf:"bytes,12,opt,name=start_maintenance,json=startMaintenance" json:"start_maintenance,omitempty"`
	StopMaintenance           *Call_StopMaintenance           `protobuf:"bytes,13,opt,name=stop_maintenance,json=stopMaintenance" json:"stop_maintenance,omitempty"`
	SetQuota                  *Call_SetQuota                  `protobuf:"bytes,14,opt,name=set_quota,json=setQuota" json:"set_quota,omitempty"`
	RemoveQuota               *Call_RemoveQuota               `protobuf:"bytes,15,opt,name=remove_quota,json=removeQuota" json:"remove_quota,omitempty"`
	XXX_unrecognized          []byte                          `json:"-"`
}

func (m *Call) Reset()                    { *m = Call{} }
func (m *Call) String() string            { return proto.CompactTextString(m) }
func (*Call) ProtoMessage()               {}
func (*Call) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Call) GetType() Call_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Call_UNKNOWN
}

func (m *Call) GetGetMetrics() *Call_GetMetrics {
	if m != nil {
		return m.GetMetrics
	}
	return nil
}

func (m *Call) GetSetLoggingLevel() *Call_SetLoggingLevel {
	if m != nil {
		return m.SetLoggingLevel
	}
	return nil
}

func (m *Call) GetListFiles() *Call_ListFiles {
	if m != nil {
		return m.ListFiles
	}
	return nil
}

func (m *Call) GetReadFile() *Call_ReadFile {
	if m != nil {
		return m.ReadFile
	}
	return nil
}

func (m *Call) GetUpdateWeights() *Call_UpdateWeights {
	if m != nil {
		return m.UpdateWeights
	}
	return nil
}

func (m *Call) GetReserveResources() *Call_ReserveResources {
	if m != nil {
		return m.ReserveResources
	}
	return nil
}

func (m *Call) GetUnreserveResources() *Call_UnreserveResources {
	if m != nil {
		return m.UnreserveResources
	}
	return nil
}

func (m *Call) GetCreateVolumes() *Call_CreateVolumes {
	if m != nil {
		return m.CreateVolumes
	}
	return nil
}

func (m *Call) GetDestroyVolumes() *Call_DestroyVolumes {
	if m != nil {
		return m.DestroyVolumes
	}
	return nil
}

func (m *Call) GetUpdateMaintenanceSchedule() *Call_UpdateMaintenanceSchedule {
	if m != nil {
		return m.UpdateMaintenanceSchedule
	}
	return nil
}

func (m *Call) GetStartMaintenance() *Call_StartMaintenance {
	if m != nil {
		return m.StartMaintenance
	}
	return nil
}

func (m *Call) GetStopMaintenance() *Call_StopMaintenance {
	if m != nil {
		return m.StopMaintenance
	}
	return nil
}

func (m *Call) GetSetQuota() *Call_SetQuota {
	if m != nil {
		return m.SetQuota
	}
	return nil
}

func (m *Call) GetRemoveQuota() *Call_RemoveQuota {
	if m != nil {
		return m.RemoveQuota
	}
	return nil
}

// Provides a snapshot of the current metrics tracked by the master.
type Call_GetMetrics struct {
	// If set, `timeout` would be used to determines the maximum amount of time
	// the API will take to respond. If the timeout is exceeded, some metrics
	// may not be included in the response.
	Timeout          *mesos.DurationInfo `protobuf:"bytes,1,opt,name=timeout" json:"timeout,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *Call_GetMetrics) Reset()                    { *m = Call_GetMetrics{} }
func (m *Call_GetMetrics) String() string            { return proto.CompactTextString(m) }
func (*Call_GetMetrics) ProtoMessage()               {}
func (*Call_GetMetrics) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Call_GetMetrics) GetTimeout() *mesos.DurationInfo {
	if m != nil {
		return m.Timeout
	}
	return nil
}

// Sets the logging verbosity level for a specified duration. Mesos uses
// [glog](https://github.com/google/glog) for logging. The library only uses
// verbose logging which means nothing will be output unless the verbosity
// level is set (by default it's 0, libprocess uses levels 1, 2, and 3).
type Call_SetLoggingLevel struct {
	// The verbosity level.
	Level *uint32 `protobuf:"varint,1,req,name=level" json:"level,omitempty"`
	// The duration to keep verbosity level toggled. After this duration, the
	// verbosity level of log would revert to the original level.
	Duration         *mesos.DurationInfo `protobuf:"bytes,2,req,name=duration" json:"duration,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *Call_SetLoggingLevel) Reset()                    { *m = Call_SetLoggingLevel{} }
func (m *Call_SetLoggingLevel) String() string            { return proto.CompactTextString(m) }
func (*Call_SetLoggingLevel) ProtoMessage()               {}
func (*Call_SetLoggingLevel) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

func (m *Call_SetLoggingLevel) GetLevel() uint32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *Call_SetLoggingLevel) GetDuration() *mesos.DurationInfo {
	if m != nil {
		return m.Duration
	}
	return nil
}

// Provides the file listing for a directory.
type Call_ListFiles struct {
	Path             *string `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Call_ListFiles) Reset()                    { *m = Call_ListFiles{} }
func (m *Call_ListFiles) String() string            { return proto.CompactTextString(m) }
func (*Call_ListFiles) ProtoMessage()               {}
func (*Call_ListFiles) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 2} }

func (m *Call_ListFiles) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

// Reads data from a file.
type Call_ReadFile struct {
	// The path of file.
	Path *string `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
	// Initial offset in file to start reading from.
	Offset *uint64 `protobuf:"varint,2,req,name=offset" json:"offset,omitempty"`
	// The maximum number of bytes to read. The read length is capped at 16
	// memory pages.
	Length           *uint64 `protobuf:"varint,3,opt,name=length" json:"length,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Call_ReadFile) Reset()                    { *m = Call_ReadFile{} }
func (m *Call_ReadFile) String() string            { return proto.CompactTextString(m) }
func (*Call_ReadFile) ProtoMessage()               {}
func (*Call_ReadFile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 3} }

func (m *Call_ReadFile) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *Call_ReadFile) GetOffset() uint64 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}

func (m *Call_ReadFile) GetLength() uint64 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

type Call_UpdateWeights struct {
	WeightInfos      []*mesos.WeightInfo `protobuf:"bytes,1,rep,name=weight_infos,json=weightInfos" json:"weight_infos,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *Call_UpdateWeights) Reset()                    { *m = Call_UpdateWeights{} }
func (m *Call_UpdateWeights) String() string            { return proto.CompactTextString(m) }
func (*Call_UpdateWeights) ProtoMessage()               {}
func (*Call_UpdateWeights) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 4} }

func (m *Call_UpdateWeights) GetWeightInfos() []*mesos.WeightInfo {
	if m != nil {
		return m.WeightInfos
	}
	return nil
}

// Reserve resources dynamically on a specific agent.
type Call_ReserveResources struct {
	AgentId          *mesos.AgentID    `protobuf:"bytes,1,req,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	Resources        []*mesos.Resource `protobuf:"bytes,2,rep,name=resources" json:"resources,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *Call_ReserveResources) Reset()                    { *m = Call_ReserveResources{} }
func (m *Call_ReserveResources) String() string            { return proto.CompactTextString(m) }
func (*Call_ReserveResources) ProtoMessage()               {}
func (*Call_ReserveResources) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 5} }

func (m *Call_ReserveResources) GetAgentId() *mesos.AgentID {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *Call_ReserveResources) GetResources() []*mesos.Resource {
	if m != nil {
		return m.Resources
	}
	return nil
}

// Unreserve resources dynamically on a specific agent.
type Call_UnreserveResources struct {
	AgentId          *mesos.AgentID    `protobuf:"bytes,1,req,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	Resources        []*mesos.Resource `protobuf:"bytes,2,rep,name=resources" json:"resources,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *Call_UnreserveResources) Reset()                    { *m = Call_UnreserveResources{} }
func (m *Call_UnreserveResources) String() string            { return proto.CompactTextString(m) }
func (*Call_UnreserveResources) ProtoMessage()               {}
func (*Call_UnreserveResources) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 6} }

func (m *Call_UnreserveResources) GetAgentId() *mesos.AgentID {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *Call_UnreserveResources) GetResources() []*mesos.Resource {
	if m != nil {
		return m.Resources
	}
	return nil
}

// Create persistent volumes on reserved resources. The request is forwarded
// asynchronously to the Mesos agent where the reserved resources are located.
// That asynchronous message may not be delivered or creating the volumes at
// the agent might fail. Volume creation can be verified by sending a
// `GET_VOLUMES` call.
type Call_CreateVolumes struct {
	AgentId          *mesos.AgentID    `protobuf:"bytes,1,req,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	Volumes          []*mesos.Resource `protobuf:"bytes,2,rep,name=volumes" json:"volumes,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *Call_CreateVolumes) Reset()                    { *m = Call_CreateVolumes{} }
func (m *Call_CreateVolumes) String() string            { return proto.CompactTextString(m) }
func (*Call_CreateVolumes) ProtoMessage()               {}
func (*Call_CreateVolumes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 7} }

func (m *Call_CreateVolumes) GetAgentId() *mesos.AgentID {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *Call_CreateVolumes) GetVolumes() []*mesos.Resource {
	if m != nil {
		return m.Volumes
	}
	return nil
}

// Destroy persistent volumes. The request is forwarded asynchronously to the
// Mesos agent where the reserved resources are located. That asynchronous
// message may not be delivered or destroying the volumes at the agent might
// fail. Volume deletion can be verified by sending a `GET_VOLUMES` call.
type Call_DestroyVolumes struct {
	AgentId          *mesos.AgentID    `protobuf:"bytes,1,req,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	Volumes          []*mesos.Resource `protobuf:"bytes,2,rep,name=volumes" json:"volumes,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *Call_DestroyVolumes) Reset()                    { *m = Call_DestroyVolumes{} }
func (m *Call_DestroyVolumes) String() string            { return proto.CompactTextString(m) }
func (*Call_DestroyVolumes) ProtoMessage()               {}
func (*Call_DestroyVolumes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 8} }

func (m *Call_DestroyVolumes) GetAgentId() *mesos.AgentID {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *Call_DestroyVolumes) GetVolumes() []*mesos.Resource {
	if m != nil {
		return m.Volumes
	}
	return nil
}

// Updates the cluster's maintenance schedule.
type Call_UpdateMaintenanceSchedule struct {
	Schedule         *mesos_maintenance.Schedule `protobuf:"bytes,1,req,name=schedule" json:"schedule,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *Call_UpdateMaintenanceSchedule) Reset()         { *m = Call_UpdateMaintenanceSchedule{} }
func (m *Call_UpdateMaintenanceSchedule) String() string { return proto.CompactTextString(m) }
func (*Call_UpdateMaintenanceSchedule) ProtoMessage()    {}
func (*Call_UpdateMaintenanceSchedule) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 9}
}

func (m *Call_UpdateMaintenanceSchedule) GetSchedule() *mesos_maintenance.Schedule {
	if m != nil {
		return m.Schedule
	}
	return nil
}

// Starts the maintenance of the cluster, this would bring a set of machines
// down.
type Call_StartMaintenance struct {
	Machines         []*mesos.MachineID `protobuf:"bytes,1,rep,name=machines" json:"machines,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *Call_StartMaintenance) Reset()                    { *m = Call_StartMaintenance{} }
func (m *Call_StartMaintenance) String() string            { return proto.CompactTextString(m) }
func (*Call_StartMaintenance) ProtoMessage()               {}
func (*Call_StartMaintenance) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 10} }

func (m *Call_StartMaintenance) GetMachines() []*mesos.MachineID {
	if m != nil {
		return m.Machines
	}
	return nil
}

// Stops the maintenance of the cluster, this would bring a set of machines
// back up.
type Call_StopMaintenance struct {
	Machines         []*mesos.MachineID `protobuf:"bytes,1,rep,name=machines" json:"machines,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *Call_StopMaintenance) Reset()                    { *m = Call_StopMaintenance{} }
func (m *Call_StopMaintenance) String() string            { return proto.CompactTextString(m) }
func (*Call_StopMaintenance) ProtoMessage()               {}
func (*Call_StopMaintenance) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 11} }

func (m *Call_StopMaintenance) GetMachines() []*mesos.MachineID {
	if m != nil {
		return m.Machines
	}
	return nil
}

// Sets the quota for resources to be used by a particular role.
type Call_SetQuota struct {
	QuotaRequest     *mesos_quota.QuotaRequest `protobuf:"bytes,1,req,name=quota_request,json=quotaRequest" json:"quota_request,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *Call_SetQuota) Reset()                    { *m = Call_SetQuota{} }
func (m *Call_SetQuota) String() string            { return proto.CompactTextString(m) }
func (*Call_SetQuota) ProtoMessage()               {}
func (*Call_SetQuota) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 12} }

func (m *Call_SetQuota) GetQuotaRequest() *mesos_quota.QuotaRequest {
	if m != nil {
		return m.QuotaRequest
	}
	return nil
}

type Call_RemoveQuota struct {
	Role             *string `protobuf:"bytes,1,req,name=role" json:"role,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Call_RemoveQuota) Reset()                    { *m = Call_RemoveQuota{} }
func (m *Call_RemoveQuota) String() string            { return proto.CompactTextString(m) }
func (*Call_RemoveQuota) ProtoMessage()               {}
func (*Call_RemoveQuota) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 13} }

func (m *Call_RemoveQuota) GetRole() string {
	if m != nil && m.Role != nil {
		return *m.Role
	}
	return ""
}

// *
// Synchronous responses for all calls (except Call::SUBSCRIBE) made to
// the v1 master API.
type Response struct {
	Type                   *Response_Type                   `protobuf:"varint,1,opt,name=type,enum=mesos.v1.master.Response_Type" json:"type,omitempty"`
	GetHealth              *Response_GetHealth              `protobuf:"bytes,2,opt,name=get_health,json=getHealth" json:"get_health,omitempty"`
	GetFlags               *Response_GetFlags               `protobuf:"bytes,3,opt,name=get_flags,json=getFlags" json:"get_flags,omitempty"`
	GetVersion             *Response_GetVersion             `protobuf:"bytes,4,opt,name=get_version,json=getVersion" json:"get_version,omitempty"`
	GetMetrics             *Response_GetMetrics             `protobuf:"bytes,5,opt,name=get_metrics,json=getMetrics" json:"get_metrics,omitempty"`
	GetLoggingLevel        *Response_GetLoggingLevel        `protobuf:"bytes,6,opt,name=get_logging_level,json=getLoggingLevel" json:"get_logging_level,omitempty"`
	ListFiles              *Response_ListFiles              `protobuf:"bytes,7,opt,name=list_files,json=listFiles" json:"list_files,omitempty"`
	ReadFile               *Response_ReadFile               `protobuf:"bytes,8,opt,name=read_file,json=readFile" json:"read_file,omitempty"`
	GetState               *Response_GetState               `protobuf:"bytes,9,opt,name=get_state,json=getState" json:"get_state,omitempty"`
	GetAgents              *Response_GetAgents              `protobuf:"bytes,10,opt,name=get_agents,json=getAgents" json:"get_agents,omitempty"`
	GetFrameworks          *Response_GetFrameworks          `protobuf:"bytes,11,opt,name=get_frameworks,json=getFrameworks" json:"get_frameworks,omitempty"`
	GetExecutors           *Response_GetExecutors           `protobuf:"bytes,12,opt,name=get_executors,json=getExecutors" json:"get_executors,omitempty"`
	GetTasks               *Response_GetTasks               `protobuf:"bytes,13,opt,name=get_tasks,json=getTasks" json:"get_tasks,omitempty"`
	GetRoles               *Response_GetRoles               `protobuf:"bytes,14,opt,name=get_roles,json=getRoles" json:"get_roles,omitempty"`
	GetWeights             *Response_GetWeights             `protobuf:"bytes,15,opt,name=get_weights,json=getWeights" json:"get_weights,omitempty"`
	GetMaster              *Response_GetMaster              `protobuf:"bytes,16,opt,name=get_master,json=getMaster" json:"get_master,omitempty"`
	GetMaintenanceStatus   *Response_GetMaintenanceStatus   `protobuf:"bytes,17,opt,name=get_maintenance_status,json=getMaintenanceStatus" json:"get_maintenance_status,omitempty"`
	GetMaintenanceSchedule *Response_GetMaintenanceSchedule `protobuf:"bytes,18,opt,name=get_maintenance_schedule,json=getMaintenanceSchedule" json:"get_maintenance_schedule,omitempty"`
	GetQuota               *Response_GetQuota               `protobuf:"bytes,19,opt,name=get_quota,json=getQuota" json:"get_quota,omitempty"`
	XXX_unrecognized       []byte                           `json:"-"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetType() Response_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Response_UNKNOWN
}

func (m *Response) GetGetHealth() *Response_GetHealth {
	if m != nil {
		return m.GetHealth
	}
	return nil
}

func (m *Response) GetGetFlags() *Response_GetFlags {
	if m != nil {
		return m.GetFlags
	}
	return nil
}

func (m *Response) GetGetVersion() *Response_GetVersion {
	if m != nil {
		return m.GetVersion
	}
	return nil
}

func (m *Response) GetGetMetrics() *Response_GetMetrics {
	if m != nil {
		return m.GetMetrics
	}
	return nil
}

func (m *Response) GetGetLoggingLevel() *Response_GetLoggingLevel {
	if m != nil {
		return m.GetLoggingLevel
	}
	return nil
}

func (m *Response) GetListFiles() *Response_ListFiles {
	if m != nil {
		return m.ListFiles
	}
	return nil
}

func (m *Response) GetReadFile() *Response_ReadFile {
	if m != nil {
		return m.ReadFile
	}
	return nil
}

func (m *Response) GetGetState() *Response_GetState {
	if m != nil {
		return m.GetState
	}
	return nil
}

func (m *Response) GetGetAgents() *Response_GetAgents {
	if m != nil {
		return m.GetAgents
	}
	return nil
}

func (m *Response) GetGetFrameworks() *Response_GetFrameworks {
	if m != nil {
		return m.GetFrameworks
	}
	return nil
}

func (m *Response) GetGetExecutors() *Response_GetExecutors {
	if m != nil {
		return m.GetExecutors
	}
	return nil
}

func (m *Response) GetGetTasks() *Response_GetTasks {
	if m != nil {
		return m.GetTasks
	}
	return nil
}

func (m *Response) GetGetRoles() *Response_GetRoles {
	if m != nil {
		return m.GetRoles
	}
	return nil
}

func (m *Response) GetGetWeights() *Response_GetWeights {
	if m != nil {
		return m.GetWeights
	}
	return nil
}

func (m *Response) GetGetMaster() *Response_GetMaster {
	if m != nil {
		return m.GetMaster
	}
	return nil
}

func (m *Response) GetGetMaintenanceStatus() *Response_GetMaintenanceStatus {
	if m != nil {
		return m.GetMaintenanceStatus
	}
	return nil
}

func (m *Response) GetGetMaintenanceSchedule() *Response_GetMaintenanceSchedule {
	if m != nil {
		return m.GetMaintenanceSchedule
	}
	return nil
}

func (m *Response) GetGetQuota() *Response_GetQuota {
	if m != nil {
		return m.GetQuota
	}
	return nil
}

// `healthy` would be true if the master is healthy. Delayed responses are
// also indicative of the poor health of the master.
type Response_GetHealth struct {
	Healthy          *bool  `protobuf:"varint,1,req,name=healthy" json:"healthy,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Response_GetHealth) Reset()                    { *m = Response_GetHealth{} }
func (m *Response_GetHealth) String() string            { return proto.CompactTextString(m) }
func (*Response_GetHealth) ProtoMessage()               {}
func (*Response_GetHealth) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *Response_GetHealth) GetHealthy() bool {
	if m != nil && m.Healthy != nil {
		return *m.Healthy
	}
	return false
}

// Contains the flag configuration of the master.
type Response_GetFlags struct {
	Flags            []*mesos.Flag `protobuf:"bytes,1,rep,name=flags" json:"flags,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *Response_GetFlags) Reset()                    { *m = Response_GetFlags{} }
func (m *Response_GetFlags) String() string            { return proto.CompactTextString(m) }
func (*Response_GetFlags) ProtoMessage()               {}
func (*Response_GetFlags) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 1} }

func (m *Response_GetFlags) GetFlags() []*mesos.Flag {
	if m != nil {
		return m.Flags
	}
	return nil
}

// Contains the version information of the master.
type Response_GetVersion struct {
	VersionInfo      *mesos.VersionInfo `protobuf:"bytes,1,req,name=version_info,json=versionInfo" json:"version_info,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *Response_GetVersion) Reset()                    { *m = Response_GetVersion{} }
func (m *Response_GetVersion) String() string            { return proto.CompactTextString(m) }
func (*Response_GetVersion) ProtoMessage()               {}
func (*Response_GetVersion) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 2} }

func (m *Response_GetVersion) GetVersionInfo() *mesos.VersionInfo {
	if m != nil {
		return m.VersionInfo
	}
	return nil
}

// Contains a snapshot of the current metrics.
type Response_GetMetrics struct {
	Metrics          []*mesos.Metric `protobuf:"bytes,1,rep,name=metrics" json:"metrics,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Response_GetMetrics) Reset()                    { *m = Response_GetMetrics{} }
func (m *Response_GetMetrics) String() string            { return proto.CompactTextString(m) }
func (*Response_GetMetrics) ProtoMessage()               {}
func (*Response_GetMetrics) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 3} }

func (m *Response_GetMetrics) GetMetrics() []*mesos.Metric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

// Contains the logging level of the master.
type Response_GetLoggingLevel struct {
	Level            *uint32 `protobuf:"varint,1,req,name=level" json:"level,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Response_GetLoggingLevel) Reset()                    { *m = Response_GetLoggingLevel{} }
func (m *Response_GetLoggingLevel) String() string            { return proto.CompactTextString(m) }
func (*Response_GetLoggingLevel) ProtoMessage()               {}
func (*Response_GetLoggingLevel) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 4} }

func (m *Response_GetLoggingLevel) GetLevel() uint32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

// Contains the file listing(similar to `ls -l`) for a directory.
type Response_ListFiles struct {
	FileInfos        []*mesos.FileInfo `protobuf:"bytes,1,rep,name=file_infos,json=fileInfos" json:"file_infos,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *Response_ListFiles) Reset()                    { *m = Response_ListFiles{} }
func (m *Response_ListFiles) String() string            { return proto.CompactTextString(m) }
func (*Response_ListFiles) ProtoMessage()               {}
func (*Response_ListFiles) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 5} }

func (m *Response_ListFiles) GetFileInfos() []*mesos.FileInfo {
	if m != nil {
		return m.FileInfos
	}
	return nil
}

// Contains the file data.
type Response_ReadFile struct {
	// The size of file (in bytes).
	Size             *uint64 `protobuf:"varint,1,req,name=size" json:"size,omitempty"`
	Data             []byte  `protobuf:"bytes,2,req,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Response_ReadFile) Reset()                    { *m = Response_ReadFile{} }
func (m *Response_ReadFile) String() string            { return proto.CompactTextString(m) }
func (*Response_ReadFile) ProtoMessage()               {}
func (*Response_ReadFile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 6} }

func (m *Response_ReadFile) GetSize() uint64 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

func (m *Response_ReadFile) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// Contains full state of the master i.e. information about the tasks,
// agents, frameworks and executors running in the cluster.
type Response_GetState struct {
	GetTasks         *Response_GetTasks      `protobuf:"bytes,1,opt,name=get_tasks,json=getTasks" json:"get_tasks,omitempty"`
	GetExecutors     *Response_GetExecutors  `protobuf:"bytes,2,opt,name=get_executors,json=getExecutors" json:"get_executors,omitempty"`
	GetFrameworks    *Response_GetFrameworks `protobuf:"bytes,3,opt,name=get_frameworks,json=getFrameworks" json:"get_frameworks,omitempty"`
	GetAgents        *Response_GetAgents     `protobuf:"bytes,4,opt,name=get_agents,json=getAgents" json:"get_agents,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *Response_GetState) Reset()                    { *m = Response_GetState{} }
func (m *Response_GetState) String() string            { return proto.CompactTextString(m) }
func (*Response_GetState) ProtoMessage()               {}
func (*Response_GetState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 7} }

func (m *Response_GetState) GetGetTasks() *Response_GetTasks {
	if m != nil {
		return m.GetTasks
	}
	return nil
}

func (m *Response_GetState) GetGetExecutors() *Response_GetExecutors {
	if m != nil {
		return m.GetExecutors
	}
	return nil
}

func (m *Response_GetState) GetGetFrameworks() *Response_GetFrameworks {
	if m != nil {
		return m.GetFrameworks
	}
	return nil
}

func (m *Response_GetState) GetGetAgents() *Response_GetAgents {
	if m != nil {
		return m.GetAgents
	}
	return nil
}

type Response_GetAgents struct {
	// Registered agents.
	Agents           []*Response_GetAgents_Agent `protobuf:"bytes,1,rep,name=agents" json:"agents,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *Response_GetAgents) Reset()                    { *m = Response_GetAgents{} }
func (m *Response_GetAgents) String() string            { return proto.CompactTextString(m) }
func (*Response_GetAgents) ProtoMessage()               {}
func (*Response_GetAgents) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 8} }

func (m *Response_GetAgents) GetAgents() []*Response_GetAgents_Agent {
	if m != nil {
		return m.Agents
	}
	return nil
}

type Response_GetAgents_Agent struct {
	AgentInfo        *mesos.AgentInfo `protobuf:"bytes,1,req,name=agent_info,json=agentInfo" json:"agent_info,omitempty"`
	Active           *bool            `protobuf:"varint,2,req,name=active" json:"active,omitempty"`
	Version          *string          `protobuf:"bytes,3,req,name=version" json:"version,omitempty"`
	Pid              *string          `protobuf:"bytes,4,opt,name=pid" json:"pid,omitempty"`
	RegisteredTime   *mesos.TimeInfo  `protobuf:"bytes,5,opt,name=registered_time,json=registeredTime" json:"registered_time,omitempty"`
	ReregisteredTime *mesos.TimeInfo  `protobuf:"bytes,6,opt,name=reregistered_time,json=reregisteredTime" json:"reregistered_time,omitempty"`
	// Total resources (including oversubscribed resources) the agent
	// provides.
	TotalResources     []*mesos.Resource `protobuf:"bytes,7,rep,name=total_resources,json=totalResources" json:"total_resources,omitempty"`
	AllocatedResources []*mesos.Resource `protobuf:"bytes,8,rep,name=allocated_resources,json=allocatedResources" json:"allocated_resources,omitempty"`
	OfferedResources   []*mesos.Resource `protobuf:"bytes,9,rep,name=offered_resources,json=offeredResources" json:"offered_resources,omitempty"`
	XXX_unrecognized   []byte            `json:"-"`
}

func (m *Response_GetAgents_Agent) Reset()                    { *m = Response_GetAgents_Agent{} }
func (m *Response_GetAgents_Agent) String() string            { return proto.CompactTextString(m) }
func (*Response_GetAgents_Agent) ProtoMessage()               {}
func (*Response_GetAgents_Agent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 8, 0} }

func (m *Response_GetAgents_Agent) GetAgentInfo() *mesos.AgentInfo {
	if m != nil {
		return m.AgentInfo
	}
	return nil
}

func (m *Response_GetAgents_Agent) GetActive() bool {
	if m != nil && m.Active != nil {
		return *m.Active
	}
	return false
}

func (m *Response_GetAgents_Agent) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

func (m *Response_GetAgents_Agent) GetPid() string {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return ""
}

func (m *Response_GetAgents_Agent) GetRegisteredTime() *mesos.TimeInfo {
	if m != nil {
		return m.RegisteredTime
	}
	return nil
}

func (m *Response_GetAgents_Agent) GetReregisteredTime() *mesos.TimeInfo {
	if m != nil {
		return m.ReregisteredTime
	}
	return nil
}

func (m *Response_GetAgents_Agent) GetTotalResources() []*mesos.Resource {
	if m != nil {
		return m.TotalResources
	}
	return nil
}

func (m *Response_GetAgents_Agent) GetAllocatedResources() []*mesos.Resource {
	if m != nil {
		return m.AllocatedResources
	}
	return nil
}

func (m *Response_GetAgents_Agent) GetOfferedResources() []*mesos.Resource {
	if m != nil {
		return m.OfferedResources
	}
	return nil
}

// Information about all the frameworks known to the master at the current
// time. Note that there might be frameworks unknown to the master running
// on partitioned or unsubscribed agents.
type Response_GetFrameworks struct {
	// Frameworks that have subscribed with the master. Note that this includes
	// frameworks that are disconnected and in the process of re-subscribing.
	Frameworks []*Response_GetFrameworks_Framework `protobuf:"bytes,1,rep,name=frameworks" json:"frameworks,omitempty"`
	// Frameworks that have been teared down.
	CompletedFrameworks []*Response_GetFrameworks_Framework `protobuf:"bytes,2,rep,name=completed_frameworks,json=completedFrameworks" json:"completed_frameworks,omitempty"`
	// Frameworks that have previously subscribed but haven't yet subscribed
	// after a master failover.
	RecoveredFrameworks []*mesos.FrameworkInfo `protobuf:"bytes,3,rep,name=recovered_frameworks,json=recoveredFrameworks" json:"recovered_frameworks,omitempty"`
	XXX_unrecognized    []byte                 `json:"-"`
}

func (m *Response_GetFrameworks) Reset()                    { *m = Response_GetFrameworks{} }
func (m *Response_GetFrameworks) String() string            { return proto.CompactTextString(m) }
func (*Response_GetFrameworks) ProtoMessage()               {}
func (*Response_GetFrameworks) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 9} }

func (m *Response_GetFrameworks) GetFrameworks() []*Response_GetFrameworks_Framework {
	if m != nil {
		return m.Frameworks
	}
	return nil
}

func (m *Response_GetFrameworks) GetCompletedFrameworks() []*Response_GetFrameworks_Framework {
	if m != nil {
		return m.CompletedFrameworks
	}
	return nil
}

func (m *Response_GetFrameworks) GetRecoveredFrameworks() []*mesos.FrameworkInfo {
	if m != nil {
		return m.RecoveredFrameworks
	}
	return nil
}

type Response_GetFrameworks_Framework struct {
	FrameworkInfo      *mesos.FrameworkInfo  `protobuf:"bytes,1,req,name=framework_info,json=frameworkInfo" json:"framework_info,omitempty"`
	Active             *bool                 `protobuf:"varint,2,req,name=active" json:"active,omitempty"`
	Connected          *bool                 `protobuf:"varint,3,req,name=connected" json:"connected,omitempty"`
	RegisteredTime     *mesos.TimeInfo       `protobuf:"bytes,4,opt,name=registered_time,json=registeredTime" json:"registered_time,omitempty"`
	ReregisteredTime   *mesos.TimeInfo       `protobuf:"bytes,5,opt,name=reregistered_time,json=reregisteredTime" json:"reregistered_time,omitempty"`
	UnregisteredTime   *mesos.TimeInfo       `protobuf:"bytes,6,opt,name=unregistered_time,json=unregisteredTime" json:"unregistered_time,omitempty"`
	Offers             []*mesos.Offer        `protobuf:"bytes,7,rep,name=offers" json:"offers,omitempty"`
	InverseOffers      []*mesos.InverseOffer `protobuf:"bytes,8,rep,name=inverse_offers,json=inverseOffers" json:"inverse_offers,omitempty"`
	AllocatedResources []*mesos.Resource     `protobuf:"bytes,9,rep,name=allocated_resources,json=allocatedResources" json:"allocated_resources,omitempty"`
	OfferedResources   []*mesos.Resource     `protobuf:"bytes,10,rep,name=offered_resources,json=offeredResources" json:"offered_resources,omitempty"`
	XXX_unrecognized   []byte                `json:"-"`
}

func (m *Response_GetFrameworks_Framework) Reset()         { *m = Response_GetFrameworks_Framework{} }
func (m *Response_GetFrameworks_Framework) String() string { return proto.CompactTextString(m) }
func (*Response_GetFrameworks_Framework) ProtoMessage()    {}
func (*Response_GetFrameworks_Framework) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 9, 0}
}

func (m *Response_GetFrameworks_Framework) GetFrameworkInfo() *mesos.FrameworkInfo {
	if m != nil {
		return m.FrameworkInfo
	}
	return nil
}

func (m *Response_GetFrameworks_Framework) GetActive() bool {
	if m != nil && m.Active != nil {
		return *m.Active
	}
	return false
}

func (m *Response_GetFrameworks_Framework) GetConnected() bool {
	if m != nil && m.Connected != nil {
		return *m.Connected
	}
	return false
}

func (m *Response_GetFrameworks_Framework) GetRegisteredTime() *mesos.TimeInfo {
	if m != nil {
		return m.RegisteredTime
	}
	return nil
}

func (m *Response_GetFrameworks_Framework) GetReregisteredTime() *mesos.TimeInfo {
	if m != nil {
		return m.ReregisteredTime
	}
	return nil
}

func (m *Response_GetFrameworks_Framework) GetUnregisteredTime() *mesos.TimeInfo {
	if m != nil {
		return m.UnregisteredTime
	}
	return nil
}

func (m *Response_GetFrameworks_Framework) GetOffers() []*mesos.Offer {
	if m != nil {
		return m.Offers
	}
	return nil
}

func (m *Response_GetFrameworks_Framework) GetInverseOffers() []*mesos.InverseOffer {
	if m != nil {
		return m.InverseOffers
	}
	return nil
}

func (m *Response_GetFrameworks_Framework) GetAllocatedResources() []*mesos.Resource {
	if m != nil {
		return m.AllocatedResources
	}
	return nil
}

func (m *Response_GetFrameworks_Framework) GetOfferedResources() []*mesos.Resource {
	if m != nil {
		return m.OfferedResources
	}
	return nil
}

// Lists information about all the executors known to the master at the
// current time. Note that there might be executors unknown to the master
// running on partitioned or unsubscribed agents.
type Response_GetExecutors struct {
	Executors        []*Response_GetExecutors_Executor `protobuf:"bytes,1,rep,name=executors" json:"executors,omitempty"`
	OrphanExecutors  []*Response_GetExecutors_Executor `protobuf:"bytes,2,rep,name=orphan_executors,json=orphanExecutors" json:"orphan_executors,omitempty"`
	XXX_unrecognized []byte                            `json:"-"`
}

func (m *Response_GetExecutors) Reset()                    { *m = Response_GetExecutors{} }
func (m *Response_GetExecutors) String() string            { return proto.CompactTextString(m) }
func (*Response_GetExecutors) ProtoMessage()               {}
func (*Response_GetExecutors) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 10} }

func (m *Response_GetExecutors) GetExecutors() []*Response_GetExecutors_Executor {
	if m != nil {
		return m.Executors
	}
	return nil
}

func (m *Response_GetExecutors) GetOrphanExecutors() []*Response_GetExecutors_Executor {
	if m != nil {
		return m.OrphanExecutors
	}
	return nil
}

type Response_GetExecutors_Executor struct {
	ExecutorInfo     *mesos.ExecutorInfo `protobuf:"bytes,1,req,name=executor_info,json=executorInfo" json:"executor_info,omitempty"`
	AgentId          *mesos.AgentID      `protobuf:"bytes,2,req,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *Response_GetExecutors_Executor) Reset()         { *m = Response_GetExecutors_Executor{} }
func (m *Response_GetExecutors_Executor) String() string { return proto.CompactTextString(m) }
func (*Response_GetExecutors_Executor) ProtoMessage()    {}
func (*Response_GetExecutors_Executor) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 10, 0}
}

func (m *Response_GetExecutors_Executor) GetExecutorInfo() *mesos.ExecutorInfo {
	if m != nil {
		return m.ExecutorInfo
	}
	return nil
}

func (m *Response_GetExecutors_Executor) GetAgentId() *mesos.AgentID {
	if m != nil {
		return m.AgentId
	}
	return nil
}

// Lists information about all the tasks known to the master at the current
// time. Note that there might be tasks unknown to the master running on
// partitioned or unsubscribed agents.
type Response_GetTasks struct {
	// Tasks that are an enqueued on the master waiting (e.g., authorizing)
	// to be launched.
	PendingTasks []*mesos.Task `protobuf:"bytes,1,rep,name=pending_tasks,json=pendingTasks" json:"pending_tasks,omitempty"`
	// Tasks that have been forwarded to the agent for launch. This includes
	// tasks that are running and reached terminal state.
	Tasks []*mesos.Task `protobuf:"bytes,2,rep,name=tasks" json:"tasks,omitempty"`
	// Tasks that have reached terminal state and have all their updates
	// acknowledged by the scheduler.
	CompletedTasks []*mesos.Task `protobuf:"bytes,3,rep,name=completed_tasks,json=completedTasks" json:"completed_tasks,omitempty"`
	// Tasks belonging to frameworks that have not yet re-subscribed with
	// master (e.g., immediately after master failover).
	OrphanTasks      []*mesos.Task `protobuf:"bytes,4,rep,name=orphan_tasks,json=orphanTasks" json:"orphan_tasks,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *Response_GetTasks) Reset()                    { *m = Response_GetTasks{} }
func (m *Response_GetTasks) String() string            { return proto.CompactTextString(m) }
func (*Response_GetTasks) ProtoMessage()               {}
func (*Response_GetTasks) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 11} }

func (m *Response_GetTasks) GetPendingTasks() []*mesos.Task {
	if m != nil {
		return m.PendingTasks
	}
	return nil
}

func (m *Response_GetTasks) GetTasks() []*mesos.Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

func (m *Response_GetTasks) GetCompletedTasks() []*mesos.Task {
	if m != nil {
		return m.CompletedTasks
	}
	return nil
}

func (m *Response_GetTasks) GetOrphanTasks() []*mesos.Task {
	if m != nil {
		return m.OrphanTasks
	}
	return nil
}

// Provides information about every role that is on the role whitelist (if
// enabled), has one or more registered frameworks or has a non-default weight
// or quota.
type Response_GetRoles struct {
	Roles            []*mesos.Role `protobuf:"bytes,1,rep,name=roles" json:"roles,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *Response_GetRoles) Reset()                    { *m = Response_GetRoles{} }
func (m *Response_GetRoles) String() string            { return proto.CompactTextString(m) }
func (*Response_GetRoles) ProtoMessage()               {}
func (*Response_GetRoles) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 12} }

func (m *Response_GetRoles) GetRoles() []*mesos.Role {
	if m != nil {
		return m.Roles
	}
	return nil
}

// Provides the weight information about every role.
type Response_GetWeights struct {
	WeightInfos      []*mesos.WeightInfo `protobuf:"bytes,1,rep,name=weight_infos,json=weightInfos" json:"weight_infos,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *Response_GetWeights) Reset()                    { *m = Response_GetWeights{} }
func (m *Response_GetWeights) String() string            { return proto.CompactTextString(m) }
func (*Response_GetWeights) ProtoMessage()               {}
func (*Response_GetWeights) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 13} }

func (m *Response_GetWeights) GetWeightInfos() []*mesos.WeightInfo {
	if m != nil {
		return m.WeightInfos
	}
	return nil
}

// Contains the master's information.
type Response_GetMaster struct {
	MasterInfo       *mesos.MasterInfo `protobuf:"bytes,1,opt,name=master_info,json=masterInfo" json:"master_info,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *Response_GetMaster) Reset()                    { *m = Response_GetMaster{} }
func (m *Response_GetMaster) String() string            { return proto.CompactTextString(m) }
func (*Response_GetMaster) ProtoMessage()               {}
func (*Response_GetMaster) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 14} }

func (m *Response_GetMaster) GetMasterInfo() *mesos.MasterInfo {
	if m != nil {
		return m.MasterInfo
	}
	return nil
}

// Contains the cluster's maintenance status.
type Response_GetMaintenanceStatus struct {
	Status           *mesos_maintenance.ClusterStatus `protobuf:"bytes,1,req,name=status" json:"status,omitempty"`
	XXX_unrecognized []byte                           `json:"-"`
}

func (m *Response_GetMaintenanceStatus) Reset()         { *m = Response_GetMaintenanceStatus{} }
func (m *Response_GetMaintenanceStatus) String() string { return proto.CompactTextString(m) }
func (*Response_GetMaintenanceStatus) ProtoMessage()    {}
func (*Response_GetMaintenanceStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 15}
}

func (m *Response_GetMaintenanceStatus) GetStatus() *mesos_maintenance.ClusterStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

// Contains the cluster's maintenance schedule.
type Response_GetMaintenanceSchedule struct {
	Schedule         *mesos_maintenance.Schedule `protobuf:"bytes,1,req,name=schedule" json:"schedule,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *Response_GetMaintenanceSchedule) Reset()         { *m = Response_GetMaintenanceSchedule{} }
func (m *Response_GetMaintenanceSchedule) String() string { return proto.CompactTextString(m) }
func (*Response_GetMaintenanceSchedule) ProtoMessage()    {}
func (*Response_GetMaintenanceSchedule) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 16}
}

func (m *Response_GetMaintenanceSchedule) GetSchedule() *mesos_maintenance.Schedule {
	if m != nil {
		return m.Schedule
	}
	return nil
}

// Contains the cluster's configured quotas.
type Response_GetQuota struct {
	Status           *mesos_quota.QuotaStatus `protobuf:"bytes,1,req,name=status" json:"status,omitempty"`
	XXX_unrecognized []byte                   `json:"-"`
}

func (m *Response_GetQuota) Reset()                    { *m = Response_GetQuota{} }
func (m *Response_GetQuota) String() string            { return proto.CompactTextString(m) }
func (*Response_GetQuota) ProtoMessage()               {}
func (*Response_GetQuota) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 17} }

func (m *Response_GetQuota) GetStatus() *mesos_quota.QuotaStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

// *
// Streaming response to `Call::SUBSCRIBE` made to the master.
type Event struct {
	Type             *Event_Type         `protobuf:"varint,1,opt,name=type,enum=mesos.v1.master.Event_Type" json:"type,omitempty"`
	Subscribed       *Event_Subscribed   `protobuf:"bytes,2,opt,name=subscribed" json:"subscribed,omitempty"`
	TaskAdded        *Event_TaskAdded    `protobuf:"bytes,3,opt,name=task_added,json=taskAdded" json:"task_added,omitempty"`
	TaskUpdated      *Event_TaskUpdated  `protobuf:"bytes,4,opt,name=task_updated,json=taskUpdated" json:"task_updated,omitempty"`
	AgentAdded       *Event_AgentAdded   `protobuf:"bytes,5,opt,name=agent_added,json=agentAdded" json:"agent_added,omitempty"`
	AgentRemoved     *Event_AgentRemoved `protobuf:"bytes,6,opt,name=agent_removed,json=agentRemoved" json:"agent_removed,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Event) GetType() Event_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Event_UNKNOWN
}

func (m *Event) GetSubscribed() *Event_Subscribed {
	if m != nil {
		return m.Subscribed
	}
	return nil
}

func (m *Event) GetTaskAdded() *Event_TaskAdded {
	if m != nil {
		return m.TaskAdded
	}
	return nil
}

func (m *Event) GetTaskUpdated() *Event_TaskUpdated {
	if m != nil {
		return m.TaskUpdated
	}
	return nil
}

func (m *Event) GetAgentAdded() *Event_AgentAdded {
	if m != nil {
		return m.AgentAdded
	}
	return nil
}

func (m *Event) GetAgentRemoved() *Event_AgentRemoved {
	if m != nil {
		return m.AgentRemoved
	}
	return nil
}

// First event received when a client subscribes.
type Event_Subscribed struct {
	// Snapshot of the entire cluster state. Further updates to the
	// cluster state are sent as separate events on the stream.
	GetState         *Response_GetState `protobuf:"bytes,1,opt,name=get_state,json=getState" json:"get_state,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *Event_Subscribed) Reset()                    { *m = Event_Subscribed{} }
func (m *Event_Subscribed) String() string            { return proto.CompactTextString(m) }
func (*Event_Subscribed) ProtoMessage()               {}
func (*Event_Subscribed) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

func (m *Event_Subscribed) GetGetState() *Response_GetState {
	if m != nil {
		return m.GetState
	}
	return nil
}

// Forwarded by the master when a task becomes known to it. This can happen
// when a new task is launched by the scheduler or when the task becomes
// known to the master upon an agent (re-)registration after a failover.
type Event_TaskAdded struct {
	Task             *mesos.Task `protobuf:"bytes,1,req,name=task" json:"task,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *Event_TaskAdded) Reset()                    { *m = Event_TaskAdded{} }
func (m *Event_TaskAdded) String() string            { return proto.CompactTextString(m) }
func (*Event_TaskAdded) ProtoMessage()               {}
func (*Event_TaskAdded) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 1} }

func (m *Event_TaskAdded) GetTask() *mesos.Task {
	if m != nil {
		return m.Task
	}
	return nil
}

// Forwarded by the master when an existing task transitions to a new state.
type Event_TaskUpdated struct {
	FrameworkId *mesos.FrameworkID `protobuf:"bytes,1,req,name=framework_id,json=frameworkId" json:"framework_id,omitempty"`
	// This is the status of the task corresponding to the last
	// status update acknowledged by the scheduler.
	Status *mesos.TaskStatus `protobuf:"bytes,2,req,name=status" json:"status,omitempty"`
	// This is the latest state of the task according to the agent.
	State            *mesos.TaskState `protobuf:"varint,3,req,name=state,enum=mesos.v1.TaskState" json:"state,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *Event_TaskUpdated) Reset()                    { *m = Event_TaskUpdated{} }
func (m *Event_TaskUpdated) String() string            { return proto.CompactTextString(m) }
func (*Event_TaskUpdated) ProtoMessage()               {}
func (*Event_TaskUpdated) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 2} }

func (m *Event_TaskUpdated) GetFrameworkId() *mesos.FrameworkID {
	if m != nil {
		return m.FrameworkId
	}
	return nil
}

func (m *Event_TaskUpdated) GetStatus() *mesos.TaskStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *Event_TaskUpdated) GetState() mesos.TaskState {
	if m != nil && m.State != nil {
		return *m.State
	}
	return mesos.TaskState_TASK_STAGING
}

// Forwarded by the master when an agent becomes known to it.
// This can happen when an agent registered for the first
// time, or reregistered after a master failover.
type Event_AgentAdded struct {
	Agent            *Response_GetAgents_Agent `protobuf:"bytes,1,req,name=agent" json:"agent,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *Event_AgentAdded) Reset()                    { *m = Event_AgentAdded{} }
func (m *Event_AgentAdded) String() string            { return proto.CompactTextString(m) }
func (*Event_AgentAdded) ProtoMessage()               {}
func (*Event_AgentAdded) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 3} }

func (m *Event_AgentAdded) GetAgent() *Response_GetAgents_Agent {
	if m != nil {
		return m.Agent
	}
	return nil
}

// Forwarded by the master when an agent is removed.
// This can happen when an agent does not re-register
// within `--agent_reregister_timeout` upon a master failover,
// or when the agent is scheduled for maintenance.
//
// NOTE: It's possible that an agent might become
// active once it has been removed, i.e. if the master
// has gc'ed its list of known "dead" agents.
// See MESOS-5965 for context.
type Event_AgentRemoved struct {
	AgentId          *mesos.AgentID `protobuf:"bytes,1,req,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *Event_AgentRemoved) Reset()                    { *m = Event_AgentRemoved{} }
func (m *Event_AgentRemoved) String() string            { return proto.CompactTextString(m) }
func (*Event_AgentRemoved) ProtoMessage()               {}
func (*Event_AgentRemoved) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 4} }

func (m *Event_AgentRemoved) GetAgentId() *mesos.AgentID {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func init() {
	proto.RegisterType((*Call)(nil), "mesos.v1.master.Call")
	proto.RegisterType((*Call_GetMetrics)(nil), "mesos.v1.master.Call.GetMetrics")
	proto.RegisterType((*Call_SetLoggingLevel)(nil), "mesos.v1.master.Call.SetLoggingLevel")
	proto.RegisterType((*Call_ListFiles)(nil), "mesos.v1.master.Call.ListFiles")
	proto.RegisterType((*Call_ReadFile)(nil), "mesos.v1.master.Call.ReadFile")
	proto.RegisterType((*Call_UpdateWeights)(nil), "mesos.v1.master.Call.UpdateWeights")
	proto.RegisterType((*Call_ReserveResources)(nil), "mesos.v1.master.Call.ReserveResources")
	proto.RegisterType((*Call_UnreserveResources)(nil), "mesos.v1.master.Call.UnreserveResources")
	proto.RegisterType((*Call_CreateVolumes)(nil), "mesos.v1.master.Call.CreateVolumes")
	proto.RegisterType((*Call_DestroyVolumes)(nil), "mesos.v1.master.Call.DestroyVolumes")
	proto.RegisterType((*Call_UpdateMaintenanceSchedule)(nil), "mesos.v1.master.Call.UpdateMaintenanceSchedule")
	proto.RegisterType((*Call_StartMaintenance)(nil), "mesos.v1.master.Call.StartMaintenance")
	proto.RegisterType((*Call_StopMaintenance)(nil), "mesos.v1.master.Call.StopMaintenance")
	proto.RegisterType((*Call_SetQuota)(nil), "mesos.v1.master.Call.SetQuota")
	proto.RegisterType((*Call_RemoveQuota)(nil), "mesos.v1.master.Call.RemoveQuota")
	proto.RegisterType((*Response)(nil), "mesos.v1.master.Response")
	proto.RegisterType((*Response_GetHealth)(nil), "mesos.v1.master.Response.GetHealth")
	proto.RegisterType((*Response_GetFlags)(nil), "mesos.v1.master.Response.GetFlags")
	proto.RegisterType((*Response_GetVersion)(nil), "mesos.v1.master.Response.GetVersion")
	proto.RegisterType((*Response_GetMetrics)(nil), "mesos.v1.master.Response.GetMetrics")
	proto.RegisterType((*Response_GetLoggingLevel)(nil), "mesos.v1.master.Response.GetLoggingLevel")
	proto.RegisterType((*Response_ListFiles)(nil), "mesos.v1.master.Response.ListFiles")
	proto.RegisterType((*Response_ReadFile)(nil), "mesos.v1.master.Response.ReadFile")
	proto.RegisterType((*Response_GetState)(nil), "mesos.v1.master.Response.GetState")
	proto.RegisterType((*Response_GetAgents)(nil), "mesos.v1.master.Response.GetAgents")
	proto.RegisterType((*Response_GetAgents_Agent)(nil), "mesos.v1.master.Response.GetAgents.Agent")
	proto.RegisterType((*Response_GetFrameworks)(nil), "mesos.v1.master.Response.GetFrameworks")
	proto.RegisterType((*Response_GetFrameworks_Framework)(nil), "mesos.v1.master.Response.GetFrameworks.Framework")
	proto.RegisterType((*Response_GetExecutors)(nil), "mesos.v1.master.Response.GetExecutors")
	proto.RegisterType((*Response_GetExecutors_Executor)(nil), "mesos.v1.master.Response.GetExecutors.Executor")
	proto.RegisterType((*Response_GetTasks)(nil), "mesos.v1.master.Response.GetTasks")
	proto.RegisterType((*Response_GetRoles)(nil), "mesos.v1.master.Response.GetRoles")
	proto.RegisterType((*Response_GetWeights)(nil), "mesos.v1.master.Response.GetWeights")
	proto.RegisterType((*Response_GetMaster)(nil), "mesos.v1.master.Response.GetMaster")
	proto.RegisterType((*Response_GetMaintenanceStatus)(nil), "mesos.v1.master.Response.GetMaintenanceStatus")
	proto.RegisterType((*Response_GetMaintenanceSchedule)(nil), "mesos.v1.master.Response.GetMaintenanceSchedule")
	proto.RegisterType((*Response_GetQuota)(nil), "mesos.v1.master.Response.GetQuota")
	proto.RegisterType((*Event)(nil), "mesos.v1.master.Event")
	proto.RegisterType((*Event_Subscribed)(nil), "mesos.v1.master.Event.Subscribed")
	proto.RegisterType((*Event_TaskAdded)(nil), "mesos.v1.master.Event.TaskAdded")
	proto.RegisterType((*Event_TaskUpdated)(nil), "mesos.v1.master.Event.TaskUpdated")
	proto.RegisterType((*Event_AgentAdded)(nil), "mesos.v1.master.Event.AgentAdded")
	proto.RegisterType((*Event_AgentRemoved)(nil), "mesos.v1.master.Event.AgentRemoved")
	proto.RegisterEnum("mesos.v1.master.Call_Type", Call_Type_name, Call_Type_value)
	proto.RegisterEnum("mesos.v1.master.Response_Type", Response_Type_name, Response_Type_value)
	proto.RegisterEnum("mesos.v1.master.Event_Type", Event_Type_name, Event_Type_value)
}

func init() { proto.RegisterFile("master.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 2642 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xbc, 0x59, 0xdd, 0x6e, 0x1b, 0xc7,
	0x15, 0x2e, 0x29, 0x52, 0x22, 0x0f, 0xff, 0x96, 0x23, 0x45, 0x61, 0xd6, 0x6e, 0xa2, 0x28, 0x4a,
	0x6c, 0x17, 0x86, 0x64, 0x2b, 0x28, 0x12, 0xd4, 0xad, 0x05, 0x8a, 0x5c, 0x4b, 0x8c, 0xf9, 0x63,
	0xcf, 0x92, 0x72, 0xd3, 0x5e, 0x10, 0x1b, 0xee, 0x88, 0x62, 0x4d, 0x71, 0xe9, 0xdd, 0xa1, 0x5c,
	0xf7, 0x2d, 0xfa, 0x06, 0x7d, 0x80, 0xa0, 0xe8, 0x23, 0xf4, 0xa6, 0x17, 0xbd, 0xec, 0x5d, 0xd1,
	0x77, 0x29, 0x50, 0xcc, 0xdf, 0xfe, 0x90, 0x4b, 0x5a, 0xb2, 0x90, 0xde, 0x10, 0x73, 0xce, 0x7c,
	0xf3, 0xcd, 0xec, 0xcc, 0x99, 0x33, 0xe7, 0x1c, 0x42, 0xfe, 0xd2, 0xf2, 0x28, 0x71, 0xf7, 0xa7,
	0xae, 0x43, 0x1d, 0x54, 0xba, 0x24, 0x9e, 0xe3, 0xed, 0x5f, 0x3d, 0xde, 0x17, 0x6a, 0x7d, 0x8b,
	0x2b, 0x0e, 0xae, 0x1e, 0x1f, 0x88, 0x1e, 0x0e, 0xd3, 0xbf, 0x0a, 0xb4, 0xd6, 0x68, 0x42, 0xc9,
	0xc4, 0x9a, 0x0c, 0x48, 0xb8, 0x2d, 0x71, 0xba, 0x8f, 0x7b, 0x33, 0x73, 0xa8, 0x25, 0x7e, 0x45,
	0xdf, 0xee, 0x3f, 0xb7, 0x21, 0x55, 0xb3, 0xc6, 0x63, 0xb4, 0x0f, 0x29, 0xfa, 0x6e, 0x4a, 0x2a,
	0x89, 0x9d, 0xc4, 0xfd, 0xe2, 0xa1, 0xbe, 0x3f, 0xb7, 0x84, 0x7d, 0x06, 0xda, 0xef, 0xbe, 0x9b,
	0x12, 0xcc, 0x71, 0xa8, 0x0a, 0xb9, 0x21, 0xa1, 0xfd, 0x4b, 0x42, 0xdd, 0xd1, 0xc0, 0xab, 0x24,
	0x77, 0x12, 0xf7, 0x73, 0x87, 0x3b, 0xf1, 0xc3, 0x4e, 0x08, 0x6d, 0x09, 0x1c, 0x86, 0xa1, 0xdf,
	0x46, 0x2f, 0xa1, 0xec, 0x11, 0xda, 0x1f, 0x3b, 0xc3, 0xe1, 0x68, 0x32, 0xec, 0x8f, 0xc9, 0x15,
	0x19, 0x57, 0xd6, 0x38, 0xd1, 0x97, 0xf1, 0x44, 0x26, 0xa1, 0x4d, 0x81, 0x6e, 0x32, 0x30, 0x2e,
	0x79, 0x51, 0x05, 0x7a, 0x0a, 0x30, 0x1e, 0x79, 0xb4, 0x7f, 0x3e, 0x1a, 0x13, 0xaf, 0x92, 0xe2,
	0x5c, 0x9f, 0xc5, 0x73, 0x35, 0x47, 0x1e, 0x7d, 0xc6, 0x60, 0x38, 0x3b, 0x56, 0x4d, 0xf4, 0x04,
	0xb2, 0x2e, 0xb1, 0x6c, 0x3e, 0xbe, 0x92, 0xe6, 0xc3, 0x3f, 0x8d, 0x1f, 0x8e, 0x89, 0x65, 0xb3,
	0x31, 0x38, 0xe3, 0xca, 0x16, 0xfa, 0x0e, 0x8a, 0xb3, 0xa9, 0x6d, 0x51, 0xd2, 0x7f, 0x4b, 0x46,
	0xc3, 0x0b, 0xea, 0x55, 0xd6, 0x39, 0xc3, 0x17, 0xf1, 0x0c, 0x3d, 0x8e, 0x7d, 0x25, 0xa0, 0xb8,
	0x30, 0x0b, 0x8b, 0xc8, 0x84, 0xb2, 0x4b, 0x3c, 0xe2, 0x5e, 0x91, 0xbe, 0x4b, 0x3c, 0x67, 0xe6,
	0x0e, 0x88, 0x57, 0xd9, 0xe0, 0x74, 0x5f, 0x2d, 0x5b, 0x10, 0x87, 0x63, 0x85, 0xc6, 0x9a, 0x3b,
	0xa7, 0x41, 0xdf, 0xc3, 0xe6, 0x6c, 0xb2, 0x48, 0x9b, 0xe1, 0xb4, 0xf7, 0x97, 0xac, 0x72, 0x32,
	0x4f, 0x83, 0xd1, 0x6c, 0x41, 0xc7, 0xbe, 0x7d, 0xe0, 0x12, 0xf6, 0xed, 0x57, 0xce, 0x78, 0x76,
	0x49, 0xbc, 0x4a, 0x76, 0xd5, 0xb7, 0xd7, 0x38, 0xf6, 0x4c, 0x40, 0x71, 0x61, 0x10, 0x16, 0x51,
	0x0b, 0x4a, 0x36, 0xf1, 0xa8, 0xeb, 0xbc, 0xf3, 0xc9, 0x80, 0x93, 0xed, 0xc5, 0x93, 0xd5, 0x05,
	0x58, 0xb1, 0x15, 0xed, 0x88, 0x8c, 0x1c, 0xb8, 0x23, 0x8f, 0x25, 0x74, 0x35, 0xfa, 0xde, 0xe0,
	0x82, 0xd8, 0xb3, 0x31, 0xa9, 0xe4, 0x38, 0xf5, 0xc1, 0xaa, 0x33, 0x6a, 0x05, 0xe3, 0x4c, 0x39,
	0x0c, 0x7f, 0x32, 0x5b, 0xd6, 0xc5, 0xce, 0xce, 0xa3, 0x96, 0x4b, 0xc3, 0xf3, 0x55, 0xf2, 0xab,
	0xce, 0xce, 0x64, 0xf0, 0x10, 0x15, 0xd6, 0xbc, 0x39, 0x0d, 0x7a, 0x01, 0x9a, 0x47, 0x9d, 0x69,
	0x84, 0xb3, 0xb0, 0xf2, 0xae, 0x50, 0x67, 0x1a, 0xa6, 0x2c, 0x79, 0x51, 0x05, 0xb3, 0x75, 0x76,
	0xfd, 0xb8, 0x37, 0xa8, 0x14, 0x57, 0xd9, 0xba, 0x49, 0xe8, 0x4b, 0x86, 0xc2, 0x19, 0x4f, 0xb6,
	0x50, 0x1d, 0xf2, 0x2e, 0xb9, 0x74, 0xae, 0x88, 0x1c, 0x5f, 0xe2, 0xe3, 0x3f, 0x5f, 0x66, 0x9a,
	0x0c, 0x29, 0x28, 0x72, 0x6e, 0x20, 0xe8, 0x4f, 0x01, 0x02, 0xdf, 0x80, 0x1e, 0xc1, 0x06, 0x1d,
	0x5d, 0x12, 0x67, 0x46, 0xb9, 0x17, 0xca, 0x1d, 0x6e, 0x07, 0x74, 0xf5, 0x99, 0x6b, 0xd1, 0x91,
	0x33, 0x69, 0x4c, 0xce, 0x1d, 0xac, 0x60, 0xfa, 0xef, 0xa1, 0x34, 0xe7, 0x12, 0xd0, 0x16, 0xa4,
	0x85, 0x23, 0x49, 0xec, 0x24, 0xef, 0x17, 0xb0, 0x10, 0xd0, 0x21, 0x64, 0x6c, 0xc9, 0x50, 0x49,
	0xee, 0x24, 0x57, 0x70, 0xfb, 0x38, 0xfd, 0x33, 0xc8, 0xfa, 0x3e, 0x02, 0x21, 0x48, 0x4d, 0x2d,
	0x7a, 0xc1, 0x59, 0xb3, 0x98, 0xb7, 0xf5, 0x36, 0x64, 0x94, 0x17, 0x88, 0xeb, 0x47, 0xdb, 0xb0,
	0xee, 0x9c, 0x9f, 0x7b, 0x84, 0xf2, 0x29, 0x53, 0x58, 0x4a, 0x4c, 0x3f, 0x26, 0x93, 0x21, 0xbd,
	0xe0, 0xce, 0x2e, 0x85, 0xa5, 0xa4, 0x9f, 0x42, 0x21, 0xe2, 0x13, 0xd0, 0x37, 0x90, 0x17, 0x9e,
	0xa4, 0x3f, 0x9a, 0x9c, 0x3b, 0x5e, 0x25, 0xb1, 0xb3, 0x76, 0x3f, 0x77, 0xb8, 0x15, 0xac, 0x5c,
	0x00, 0xf9, 0xba, 0x73, 0x6f, 0xfd, 0xb6, 0xa7, 0xbb, 0xa0, 0xcd, 0xbb, 0x03, 0xf4, 0x10, 0x32,
	0xd6, 0x90, 0x4c, 0x68, 0x7f, 0x64, 0xf3, 0x55, 0xe6, 0x0e, 0xcb, 0x01, 0x51, 0x95, 0xf5, 0x34,
	0xea, 0x78, 0x83, 0x43, 0x1a, 0x36, 0x7a, 0xc4, 0x1c, 0xa1, 0x72, 0x10, 0x49, 0x3e, 0x2f, 0x0a,
	0xe0, 0x8a, 0x15, 0x07, 0x20, 0x9d, 0x02, 0x5a, 0xf4, 0x15, 0x3f, 0xf9, 0xac, 0xaf, 0xa1, 0x10,
	0xf1, 0x25, 0x37, 0x9c, 0xf0, 0x21, 0x6c, 0x28, 0x17, 0xb3, 0x7c, 0x3a, 0x05, 0xd1, 0xc7, 0x50,
	0x8c, 0xfa, 0x9a, 0x9f, 0x74, 0xb6, 0x57, 0xf0, 0xc9, 0x52, 0xf7, 0x83, 0x7e, 0x05, 0x19, 0xdf,
	0x83, 0x89, 0x89, 0x23, 0x77, 0x37, 0x08, 0x01, 0x7c, 0x87, 0xe5, 0xe3, 0xf5, 0x1a, 0x68, 0xf3,
	0x0e, 0x07, 0x1d, 0x40, 0xe6, 0xd2, 0x1a, 0x5c, 0x8c, 0x26, 0x44, 0x99, 0xd9, 0x66, 0xc0, 0xd7,
	0x12, 0x3d, 0x8d, 0x3a, 0xf6, 0x41, 0xfa, 0x31, 0x94, 0xe6, 0x3c, 0xcc, 0xcd, 0x39, 0x5a, 0x90,
	0x51, 0xae, 0x05, 0x55, 0xa1, 0xc0, 0x3d, 0x49, 0xdf, 0x25, 0x6f, 0x66, 0xc4, 0xa3, 0xf2, 0xab,
	0xee, 0x06, 0x0c, 0x22, 0x6c, 0x11, 0x5e, 0x44, 0x60, 0x70, 0xfe, 0x4d, 0x48, 0xd2, 0x3f, 0x87,
	0x5c, 0xc8, 0xd3, 0xb0, 0x2b, 0xe9, 0x3a, 0x72, 0x7b, 0xb2, 0x98, 0xb7, 0x77, 0xff, 0x93, 0x82,
	0x14, 0x0b, 0x62, 0x50, 0x0e, 0x36, 0x7a, 0xed, 0xe7, 0xed, 0xce, 0xab, 0xb6, 0xf6, 0x33, 0x54,
	0x04, 0x38, 0x31, 0xba, 0xfd, 0x53, 0xa3, 0xda, 0xec, 0x9e, 0x6a, 0x09, 0x54, 0x80, 0x2c, 0x93,
	0x9f, 0x35, 0xab, 0x27, 0xa6, 0x96, 0x44, 0x25, 0xc8, 0x31, 0xf1, 0xcc, 0xc0, 0x66, 0xa3, 0xd3,
	0xd6, 0xd6, 0x94, 0xa2, 0x65, 0x74, 0x71, 0xa3, 0x66, 0x6a, 0x29, 0xf4, 0x11, 0x94, 0x99, 0xa2,
	0xd9, 0x39, 0x39, 0x69, 0xb4, 0x4f, 0xfa, 0x4d, 0xe3, 0xcc, 0x68, 0x6a, 0x69, 0xa6, 0x36, 0x17,
	0xd4, 0xeb, 0x6c, 0xba, 0x66, 0xc3, 0xec, 0xf6, 0x9f, 0x35, 0x9a, 0x86, 0xa9, 0x6d, 0xb0, 0xe9,
	0xb0, 0x51, 0xad, 0x73, 0x59, 0xcb, 0xa8, 0xd9, 0xcd, 0x6e, 0xb5, 0x6b, 0x68, 0x59, 0xb5, 0xb8,
	0xea, 0x89, 0xd1, 0xee, 0x9a, 0x1a, 0x20, 0x04, 0x45, 0xbe, 0x38, 0x5c, 0x6d, 0x19, 0xaf, 0x3a,
	0xf8, 0xb9, 0xa9, 0xe5, 0x50, 0x19, 0x0a, 0x4c, 0x67, 0xfc, 0xd6, 0xa8, 0xf5, 0xba, 0x1d, 0x6c,
	0x6a, 0x79, 0xc5, 0xd2, 0xad, 0x9a, 0xcf, 0x4d, 0xad, 0xa0, 0x44, 0xdc, 0x61, 0x53, 0x16, 0xd5,
	0x17, 0xbc, 0x32, 0x1a, 0x27, 0xa7, 0x5d, 0x53, 0x2b, 0x31, 0xd6, 0xde, 0x8b, 0x7a, 0xb5, 0x6b,
	0xf8, 0x3a, 0x4d, 0xcd, 0xdc, 0xaa, 0x9a, 0x5d, 0x03, 0x6b, 0x65, 0xc6, 0x61, 0xf6, 0x8e, 0xcd,
	0x1a, 0x6e, 0x1c, 0x1b, 0x1a, 0x62, 0x5f, 0x87, 0x0d, 0xd3, 0xc0, 0x67, 0x46, 0x1f, 0x1b, 0x66,
	0xa7, 0x87, 0x6b, 0x86, 0xa9, 0x6d, 0xa2, 0x8f, 0x61, 0xb3, 0xd7, 0x5e, 0xec, 0xd8, 0x62, 0x53,
	0xd4, 0xb0, 0xc1, 0xa6, 0x38, 0xeb, 0x34, 0x7b, 0x2d, 0xc3, 0xd4, 0x3e, 0x42, 0x9b, 0x50, 0xaa,
	0x1b, 0x66, 0x17, 0x77, 0xbe, 0xf7, 0x95, 0xdb, 0x48, 0x87, 0x6d, 0x31, 0x6f, 0xa3, 0xdd, 0x35,
	0xda, 0xd5, 0x76, 0xcd, 0xe0, 0x9b, 0xd1, 0x33, 0xb5, 0x8f, 0xd1, 0x5d, 0xa8, 0x2c, 0xf4, 0xd5,
	0x4e, 0x8d, 0x7a, 0xaf, 0x69, 0x68, 0x15, 0xf4, 0x19, 0xdc, 0x91, 0x5f, 0x11, 0x0b, 0xf8, 0x84,
	0x9f, 0x48, 0xb7, 0x8a, 0x23, 0x04, 0x9a, 0x8e, 0xb6, 0x40, 0x33, 0xbb, 0x9d, 0x17, 0x11, 0xed,
	0x1d, 0xb5, 0x67, 0x2f, 0x7b, 0x9d, 0x6e, 0x55, 0xbb, 0xcb, 0x3f, 0xdf, 0x17, 0x7f, 0x8e, 0x34,
	0xc8, 0x63, 0xa3, 0xd5, 0x39, 0x33, 0xa4, 0xe6, 0xd3, 0xdd, 0xff, 0xee, 0xb1, 0x07, 0xc1, 0x9b,
	0x3a, 0x13, 0x8f, 0xa0, 0xc3, 0x48, 0x3c, 0xbd, 0xf8, 0xb0, 0x2a, 0x60, 0x38, 0xa6, 0x3e, 0x06,
	0x16, 0x1e, 0xf7, 0x2f, 0x88, 0x35, 0xa6, 0x17, 0x32, 0xa4, 0xfe, 0x62, 0xf9, 0xc8, 0x13, 0x42,
	0x4f, 0x39, 0x14, 0x67, 0x87, 0xaa, 0x89, 0x8e, 0x80, 0x09, 0xfd, 0xf3, 0xb1, 0x35, 0xf4, 0x64,
	0x30, 0xbd, 0xbb, 0x92, 0xe2, 0x19, 0x43, 0xe2, 0xcc, 0x50, 0xb6, 0x90, 0x21, 0x02, 0xfb, 0x2b,
	0xe2, 0x7a, 0xec, 0xb5, 0x4c, 0x2d, 0x89, 0xbc, 0xc2, 0x14, 0x67, 0x02, 0xcb, 0x83, 0x7b, 0xd9,
	0x56, 0x34, 0x2a, 0x3f, 0x48, 0x5f, 0x83, 0x26, 0x2e, 0x47, 0xe8, 0x41, 0x79, 0xb8, 0x90, 0x23,
	0x88, 0xb0, 0xfa, 0xc1, 0x4a, 0xb2, 0x68, 0x9e, 0x30, 0x9c, 0x8b, 0x12, 0x8e, 0x23, 0x79, 0xc2,
	0xc6, 0xfb, 0x76, 0x3a, 0x36, 0x57, 0x38, 0x0a, 0xe7, 0x0a, 0x99, 0xf7, 0xed, 0x74, 0x4c, 0xbe,
	0x20, 0x8f, 0xca, 0xa3, 0x16, 0x25, 0x32, 0x5c, 0x5e, 0x7d, 0x54, 0x26, 0x43, 0xf2, 0xa3, 0xe2,
	0x2d, 0x65, 0x2f, 0xfc, 0x79, 0x51, 0x31, 0xf2, 0x6a, 0x7b, 0xe1, 0x4f, 0x92, 0xc7, 0xed, 0x45,
	0x34, 0x51, 0x1b, 0x8a, 0xdc, 0x5e, 0x5c, 0xeb, 0x92, 0xbc, 0x75, 0xdc, 0xd7, 0x9e, 0x0c, 0x88,
	0xef, 0xad, 0x36, 0x1a, 0x1f, 0x8e, 0x0b, 0xc3, 0xb0, 0x88, 0x9e, 0x03, 0x53, 0xf4, 0xc9, 0x1f,
	0xc9, 0x60, 0x46, 0x1d, 0xd7, 0x5b, 0x1a, 0xf8, 0x86, 0xe9, 0x0c, 0x85, 0xc6, 0xf9, 0x61, 0x48,
	0x52, 0x3b, 0x44, 0x2d, 0xef, 0xb5, 0x27, 0xa3, 0xdd, 0xd5, 0x3b, 0xd4, 0x65, 0x48, 0xbe, 0x43,
	0xbc, 0xa5, 0x08, 0x98, 0xef, 0xf7, 0x64, 0x8c, 0xbb, 0x9a, 0x00, 0x33, 0x24, 0x27, 0xe0, 0x2d,
	0x65, 0xc6, 0x2a, 0xa1, 0x2b, 0x5d, 0xc3, 0x8c, 0x55, 0x46, 0xc7, 0xce, 0x46, 0x45, 0x72, 0xf2,
	0xa4, 0x04, 0xba, 0xa2, 0x5d, 0xe3, 0xa4, 0x5a, 0x5c, 0xc5, 0x4f, 0x4a, 0x34, 0x91, 0x0d, 0xdb,
	0x82, 0x23, 0x94, 0xc4, 0x50, 0x8b, 0xce, 0xbc, 0x4a, 0x99, 0xf3, 0xed, 0xbf, 0x87, 0x2f, 0x08,
	0x22, 0xf8, 0x28, 0xbc, 0x35, 0x8c, 0xd1, 0xa2, 0x3f, 0x40, 0x65, 0x61, 0x16, 0x15, 0x68, 0x20,
	0x3e, 0xcf, 0xa3, 0x6b, 0xcf, 0xa3, 0x42, 0x8f, 0xed, 0x61, 0xac, 0x5e, 0x9d, 0x8e, 0xc8, 0x20,
	0x36, 0xaf, 0x71, 0x3a, 0x32, 0x0b, 0x19, 0xca, 0x96, 0xfe, 0x25, 0x64, 0x7d, 0x27, 0x88, 0x2a,
	0xb0, 0x21, 0x3c, 0xe7, 0x3b, 0xfe, 0xe4, 0x67, 0xb0, 0x12, 0xf5, 0x47, 0x90, 0x51, 0x8e, 0x0e,
	0xed, 0x41, 0x5a, 0xf8, 0x46, 0x11, 0xa1, 0x14, 0x83, 0xf9, 0x58, 0x3f, 0x16, 0x9d, 0xfa, 0x33,
	0x9e, 0x98, 0x28, 0x5f, 0xf6, 0x2d, 0xe4, 0xa5, 0x3b, 0xe4, 0x81, 0xb8, 0x0c, 0x4d, 0x3e, 0x0a,
	0x86, 0x4a, 0xa0, 0x08, 0xc4, 0xaf, 0x02, 0x41, 0xff, 0x36, 0x92, 0xe0, 0xfc, 0x02, 0x36, 0x94,
	0x3f, 0x14, 0xb3, 0x6b, 0xa1, 0xf8, 0x88, 0x77, 0x60, 0x05, 0xd0, 0xef, 0x41, 0xe9, 0xe4, 0x3a,
	0xa9, 0x8d, 0xfe, 0x34, 0x9c, 0xa6, 0x3c, 0x06, 0x60, 0xee, 0x28, 0x92, 0x2f, 0x84, 0x82, 0x4c,
	0x06, 0xe2, 0x8b, 0xcc, 0x9e, 0xcb, 0x96, 0xa7, 0x1f, 0x46, 0xb3, 0x18, 0x6f, 0xf4, 0x27, 0x11,
	0x32, 0xa5, 0x30, 0x6f, 0x33, 0x9d, 0x6d, 0x51, 0x8b, 0xe7, 0x30, 0x79, 0xcc, 0xdb, 0xfa, 0x8f,
	0x49, 0xbe, 0xa3, 0xc2, 0x0b, 0x45, 0x2e, 0x69, 0xe2, 0x03, 0x2e, 0xe9, 0x82, 0xcb, 0x48, 0xde,
	0xc2, 0x65, 0x2c, 0xfa, 0xb3, 0xb5, 0x5b, 0xf9, 0xb3, 0xa8, 0x8f, 0x4d, 0x7d, 0x88, 0x8f, 0xd5,
	0xff, 0x9c, 0xe2, 0x76, 0x2a, 0x3d, 0x6e, 0x15, 0xd6, 0x25, 0x9b, 0x38, 0x9f, 0x07, 0xd7, 0x60,
	0x13, 0xb9, 0x04, 0x96, 0x03, 0xf5, 0xbf, 0xaf, 0x41, 0x9a, 0x6b, 0xd0, 0x21, 0x80, 0x4c, 0x40,
	0x02, 0xc3, 0xdc, 0x9c, 0x4f, 0x41, 0xf8, 0x89, 0x5b, 0xaa, 0xc9, 0xf2, 0x4f, 0x6b, 0x40, 0x47,
	0x57, 0x84, 0x9f, 0x69, 0x06, 0x4b, 0x89, 0x5d, 0x20, 0xf5, 0xea, 0xaf, 0xf1, 0x98, 0x59, 0x89,
	0x48, 0x83, 0xb5, 0xe9, 0xc8, 0xe6, 0x5f, 0x9f, 0xc5, 0xac, 0x89, 0x9e, 0x40, 0xc9, 0x25, 0xc3,
	0x11, 0x5b, 0x2e, 0xb1, 0xfb, 0x2c, 0x1f, 0x97, 0x4f, 0x7c, 0xc8, 0xda, 0xba, 0xa3, 0x4b, 0x61,
	0x6d, 0xc5, 0x00, 0xca, 0x74, 0xe8, 0x08, 0xca, 0x2e, 0x99, 0x1f, 0xbe, 0xbe, 0x74, 0xb8, 0x16,
	0x06, 0x73, 0x82, 0x27, 0x50, 0xa2, 0x0e, 0xb5, 0xc6, 0x91, 0xda, 0xd8, 0xb2, 0x84, 0xaa, 0xc8,
	0xa1, 0x41, 0x4a, 0x5a, 0x83, 0x4d, 0x6b, 0x3c, 0x76, 0x06, 0x16, 0x25, 0x76, 0xa4, 0x0a, 0xb6,
	0x8c, 0x00, 0xf9, 0xf0, 0x80, 0xe4, 0x08, 0xca, 0xce, 0xf9, 0x39, 0x5f, 0x7d, 0x40, 0x91, 0x5d,
	0x4a, 0xa1, 0x49, 0xb0, 0x4f, 0xa0, 0xff, 0x63, 0x1d, 0x0a, 0x11, 0xc3, 0x43, 0x2f, 0x01, 0x42,
	0x56, 0x2b, 0x6c, 0xe3, 0xf1, 0x35, 0xad, 0x76, 0xdf, 0x6f, 0xe2, 0x10, 0x09, 0xb2, 0x61, 0x6b,
	0xe0, 0x5c, 0x4e, 0xc7, 0x84, 0x7d, 0x6a, 0x88, 0x3c, 0xf9, 0xa1, 0xe4, 0x9b, 0x3e, 0x5d, 0x68,
	0xe1, 0xdf, 0xc1, 0x96, 0x4b, 0x06, 0xce, 0x15, 0xdf, 0x8d, 0xc8, 0xc5, 0x63, 0xb3, 0x7c, 0x1c,
	0x72, 0x3f, 0xaa, 0x8f, 0x1f, 0xeb, 0xa6, 0x3f, 0x28, 0xe0, 0xd2, 0xff, 0x9a, 0x82, 0xac, 0x2f,
	0xa2, 0xa7, 0x50, 0xf4, 0xf9, 0xc2, 0x16, 0xbe, 0x94, 0xb3, 0x70, 0x1e, 0x16, 0x97, 0x5a, 0xfa,
	0x5d, 0xc8, 0x0e, 0x9c, 0xc9, 0x84, 0x0c, 0x28, 0xb1, 0xb9, 0xad, 0x67, 0x70, 0xa0, 0x88, 0xb3,
	0xed, 0xd4, 0xed, 0x6c, 0x3b, 0x7d, 0x03, 0xdb, 0x3e, 0x82, 0xf2, 0x6c, 0x72, 0x83, 0xcb, 0x11,
	0x06, 0x73, 0x82, 0x7b, 0xbc, 0xec, 0x44, 0x5c, 0x75, 0x27, 0x4a, 0xc1, 0xa8, 0x0e, 0xd3, 0x63,
	0xd9, 0x8d, 0x7e, 0x03, 0xc5, 0xd1, 0x84, 0x5d, 0x71, 0xd2, 0x97, 0x03, 0xc4, 0x1d, 0x08, 0x95,
	0xc6, 0x1a, 0xa2, 0x5f, 0x8c, 0x2b, 0x8c, 0x42, 0xd2, 0xd2, 0x7b, 0x94, 0xbd, 0xfd, 0x3d, 0x82,
	0x1b, 0xdc, 0xa3, 0xbf, 0x25, 0x21, 0x1f, 0x7e, 0x0e, 0x50, 0x0b, 0xb2, 0xc1, 0x4b, 0x22, 0x6e,
	0xd1, 0xc1, 0xf5, 0x5e, 0x92, 0x7d, 0xd5, 0xc2, 0x01, 0x03, 0xfa, 0x1d, 0x68, 0x8e, 0x3b, 0xbd,
	0xb0, 0x26, 0x91, 0xf7, 0xe9, 0x83, 0x58, 0x4b, 0x82, 0xc8, 0xef, 0xd1, 0x67, 0x90, 0x51, 0x02,
	0x7a, 0x02, 0x05, 0x35, 0x41, 0xd8, 0xd2, 0x43, 0x67, 0xa1, 0xa0, 0xfc, 0xd8, 0xf3, 0x24, 0x24,
	0x45, 0xca, 0x50, 0xc9, 0xf7, 0x95, 0xa1, 0xf4, 0x7f, 0x25, 0xf8, 0xeb, 0x2d, 0x1e, 0xdf, 0xaf,
	0xa1, 0x30, 0x25, 0x13, 0x9b, 0x25, 0x57, 0xea, 0x05, 0x9f, 0x8b, 0x8b, 0x18, 0x0e, 0xe7, 0x25,
	0x48, 0x0c, 0xda, 0x83, 0xb4, 0x00, 0x27, 0x63, 0xc1, 0xa2, 0x13, 0x7d, 0x03, 0xa5, 0xc0, 0xfb,
	0x08, 0xfc, 0x5a, 0x2c, 0xbe, 0xe8, 0xc3, 0x04, 0xfd, 0x63, 0xc8, 0xcb, 0x3d, 0x17, 0xa3, 0x52,
	0xb1, 0xa3, 0x72, 0x02, 0xc3, 0x87, 0xc8, 0x10, 0x4f, 0xc4, 0xec, 0x7b, 0x90, 0x16, 0x01, 0xff,
	0xc2, 0xa7, 0xb0, 0x7e, 0x2c, 0x3a, 0x75, 0x83, 0x87, 0x66, 0xb7, 0x2e, 0xb5, 0x1e, 0xf3, 0xa7,
	0x5d, 0x86, 0xe8, 0xbf, 0x84, 0x9c, 0x30, 0x05, 0x75, 0x84, 0x89, 0x28, 0x89, 0x80, 0x71, 0x12,
	0xb8, 0xf4, 0xdb, 0xba, 0x09, 0x5b, 0x71, 0x11, 0x3a, 0x7a, 0x02, 0xeb, 0x32, 0xc2, 0x17, 0xc6,
	0xf0, 0x45, 0x7c, 0x89, 0xaf, 0x36, 0x9e, 0x31, 0x2a, 0x19, 0xd6, 0xcb, 0x21, 0x7a, 0x17, 0xb6,
	0xe3, 0xc3, 0xf1, 0x5b, 0xd5, 0x0e, 0x8f, 0xf8, 0x3e, 0x8b, 0x02, 0xdb, 0xd7, 0x73, 0xcb, 0xbb,
	0x13, 0x5b, 0xab, 0x8b, 0x2e, 0x6b, 0xf7, 0xdf, 0xc9, 0xff, 0x67, 0x05, 0x2e, 0x5a, 0x6a, 0x5b,
	0x8f, 0x96, 0xda, 0x36, 0xa2, 0xa5, 0xb6, 0xcc, 0x5c, 0xa9, 0x2d, 0x1b, 0x53, 0x6a, 0x83, 0xc5,
	0x52, 0x5b, 0x2e, 0x5a, 0x6a, 0xcb, 0x47, 0x4b, 0x6d, 0x85, 0xf9, 0x52, 0x5b, 0x71, 0xae, 0xac,
	0x56, 0x5a, 0x51, 0xee, 0xd2, 0x56, 0x96, 0xbb, 0xca, 0xd1, 0x02, 0x15, 0xda, 0xfd, 0x71, 0x03,
	0xd2, 0xc6, 0x15, 0x8b, 0x0a, 0x0f, 0x22, 0xc5, 0xa7, 0x3b, 0x0b, 0x8e, 0x8a, 0xa3, 0xa2, 0xff,
	0xe6, 0x82, 0x37, 0xfb, 0xc1, 0x1b, 0xb8, 0xa3, 0x1f, 0x88, 0x2d, 0xe3, 0xef, 0xcf, 0x97, 0x0c,
	0x33, 0x7d, 0x20, 0x0e, 0x0d, 0x42, 0x47, 0x00, 0xec, 0xb6, 0xf6, 0x2d, 0xdb, 0xe6, 0x8f, 0x6a,
	0xfc, 0xff, 0xc1, 0x72, 0x66, 0xcb, 0x7b, 0x5d, 0x65, 0x38, 0x9c, 0xa5, 0xaa, 0x89, 0x0c, 0xc8,
	0x73, 0x02, 0xf1, 0xc7, 0x9a, 0x2d, 0xdf, 0xdc, 0xdd, 0x15, 0x14, 0xa2, 0x3c, 0x6e, 0xe3, 0x1c,
	0x0d, 0x04, 0x74, 0x0c, 0x39, 0xe1, 0x0b, 0xc5, 0x42, 0xd2, 0x2b, 0xbf, 0x85, 0xfb, 0x46, 0xb1,
	0x12, 0x11, 0x47, 0x8b, 0xa5, 0x9c, 0x42, 0x41, 0x70, 0x88, 0x3f, 0xab, 0xec, 0xa5, 0x7f, 0xe4,
	0x86, 0x58, 0x44, 0xe9, 0xd9, 0xc6, 0x79, 0x2b, 0x24, 0xe9, 0x2d, 0x00, 0x33, 0xbc, 0x47, 0xa1,
	0x8a, 0x4f, 0xe2, 0xe6, 0x15, 0x1f, 0xfd, 0x00, 0xb2, 0xfe, 0xde, 0xa1, 0x5d, 0x48, 0xb1, 0x0f,
	0x97, 0xb7, 0x6f, 0xde, 0x3d, 0xf2, 0x3e, 0xfd, 0x2f, 0x09, 0xc8, 0x85, 0xb6, 0x8a, 0xa5, 0xb2,
	0xa1, 0x88, 0xca, 0x5e, 0x4c, 0x65, 0x83, 0x78, 0xaa, 0x8e, 0x73, 0x41, 0x34, 0x65, 0xa3, 0x87,
	0xfe, 0x6d, 0x17, 0x2f, 0xcc, 0x56, 0x74, 0xbe, 0xe8, 0x35, 0x47, 0x0f, 0x20, 0x2d, 0xbe, 0x92,
	0x45, 0x57, 0xc5, 0x70, 0x4a, 0xa2, 0xc0, 0x04, 0x0b, 0x04, 0xdb, 0xa2, 0xe0, 0x18, 0xd0, 0x11,
	0xa4, 0xf9, 0x06, 0xca, 0x95, 0xdd, 0x20, 0x39, 0x12, 0xe3, 0xf4, 0x5f, 0x43, 0x3e, 0x7c, 0x1e,
	0x37, 0xfb, 0x8b, 0x66, 0x77, 0xb4, 0xc4, 0x3b, 0xf9, 0x85, 0xef, 0xba, 0x96, 0x60, 0x32, 0xbb,
	0xec, 0xfd, 0x6a, 0xbd, 0x6e, 0xd4, 0xb5, 0x24, 0xd2, 0x20, 0xcf, 0x65, 0x51, 0x7b, 0xae, 0x0b,
	0xff, 0xc4, 0xbd, 0x88, 0x84, 0xa4, 0x98, 0xdb, 0x10, 0x0a, 0x51, 0x33, 0xae, 0x6b, 0xe9, 0xe3,
	0x3d, 0xd0, 0x1d, 0x77, 0xb8, 0x6f, 0x4d, 0xad, 0xc1, 0x05, 0x99, 0xff, 0xcc, 0xe3, 0xf5, 0x17,
	0xae, 0x43, 0x1d, 0xef, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x26, 0x07, 0xe4, 0xe8, 0x1a, 0x22,
	0x00, 0x00,
}
