all:
	@cd base && make
	@cd app && make
	@cd audit && make
	@cd config-item && make
	@cd content && make
	@cd commit && make
	@cd release && make
	@cd released-ci && make
	@cd event && make
	@cd hook && make
	@cd hook-revision && make
	@cd group && make
	@cd released-group && make
	@cd credential && make
	@cd credential-scope && make
	@cd template-space && make
	@cd template && make
	@cd template-revision && make
	@cd template-set && make
	@cd app-template-binding && make
	@cd template-binding-relation && make
	@cd template-variable && make
	@cd app-template-variable && make
	@cd kv && make
	@cd released-kv && make
	@cd strategy && make
	@cd client && make
	@cd client-event && make
	@cd client-query && make

clean:
	@cd base && make clean
	@cd app && make clean
	@cd audit && make clean
	@cd config-item && make clean
	@cd commit && make clean
	@cd content && make clean
	@cd release && make clean
	@cd released-ci && make clean
	@cd event && make clean
	@cd hook && make
	@cd hook-revision && make clean
	@cd group && make clean
	@cd released-group && make clean
	@cd credential && make clean
	@cd credential-scope && make clean
	@cd template-space && make clean
	@cd template && make clean
	@cd template-revision && make clean
	@cd template-set && make clean
	@cd app-template-binding && make clean
	@cd template-binding-relation && make clean
	@cd template-variable && make clean
	@cd app-template-variable && make clean
	@cd kv && make clean
	@cd released-kv && make clean
	@cd strategy && make clean
	@cd client && make clean
	@cd client-event && make clean
	@cd client-query && make clean
