// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: template_binding_relation.proto

package pbtbr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TemplateBoundCounts is template bound counts.
type TemplateBoundCounts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TemplateId            uint32 `protobuf:"varint,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	BoundUnnamedAppCount  uint32 `protobuf:"varint,2,opt,name=bound_unnamed_app_count,json=boundUnnamedAppCount,proto3" json:"bound_unnamed_app_count,omitempty"`
	BoundNamedAppCount    uint32 `protobuf:"varint,3,opt,name=bound_named_app_count,json=boundNamedAppCount,proto3" json:"bound_named_app_count,omitempty"`
	BoundTemplateSetCount uint32 `protobuf:"varint,4,opt,name=bound_template_set_count,json=boundTemplateSetCount,proto3" json:"bound_template_set_count,omitempty"`
}

func (x *TemplateBoundCounts) Reset() {
	*x = TemplateBoundCounts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_template_binding_relation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemplateBoundCounts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateBoundCounts) ProtoMessage() {}

func (x *TemplateBoundCounts) ProtoReflect() protoreflect.Message {
	mi := &file_template_binding_relation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateBoundCounts.ProtoReflect.Descriptor instead.
func (*TemplateBoundCounts) Descriptor() ([]byte, []int) {
	return file_template_binding_relation_proto_rawDescGZIP(), []int{0}
}

func (x *TemplateBoundCounts) GetTemplateId() uint32 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

func (x *TemplateBoundCounts) GetBoundUnnamedAppCount() uint32 {
	if x != nil {
		return x.BoundUnnamedAppCount
	}
	return 0
}

func (x *TemplateBoundCounts) GetBoundNamedAppCount() uint32 {
	if x != nil {
		return x.BoundNamedAppCount
	}
	return 0
}

func (x *TemplateBoundCounts) GetBoundTemplateSetCount() uint32 {
	if x != nil {
		return x.BoundTemplateSetCount
	}
	return 0
}

// TemplateRevisionBoundCounts is template release bound counts.
type TemplateRevisionBoundCounts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TemplateRevisionId   uint32 `protobuf:"varint,1,opt,name=template_revision_id,json=templateRevisionId,proto3" json:"template_revision_id,omitempty"`
	BoundUnnamedAppCount uint32 `protobuf:"varint,2,opt,name=bound_unnamed_app_count,json=boundUnnamedAppCount,proto3" json:"bound_unnamed_app_count,omitempty"`
	BoundNamedAppCount   uint32 `protobuf:"varint,3,opt,name=bound_named_app_count,json=boundNamedAppCount,proto3" json:"bound_named_app_count,omitempty"`
}

func (x *TemplateRevisionBoundCounts) Reset() {
	*x = TemplateRevisionBoundCounts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_template_binding_relation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemplateRevisionBoundCounts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateRevisionBoundCounts) ProtoMessage() {}

func (x *TemplateRevisionBoundCounts) ProtoReflect() protoreflect.Message {
	mi := &file_template_binding_relation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateRevisionBoundCounts.ProtoReflect.Descriptor instead.
func (*TemplateRevisionBoundCounts) Descriptor() ([]byte, []int) {
	return file_template_binding_relation_proto_rawDescGZIP(), []int{1}
}

func (x *TemplateRevisionBoundCounts) GetTemplateRevisionId() uint32 {
	if x != nil {
		return x.TemplateRevisionId
	}
	return 0
}

func (x *TemplateRevisionBoundCounts) GetBoundUnnamedAppCount() uint32 {
	if x != nil {
		return x.BoundUnnamedAppCount
	}
	return 0
}

func (x *TemplateRevisionBoundCounts) GetBoundNamedAppCount() uint32 {
	if x != nil {
		return x.BoundNamedAppCount
	}
	return 0
}

// TemplateSetBoundCounts is template set bound counts.
type TemplateSetBoundCounts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TemplateSetId        uint32 `protobuf:"varint,1,opt,name=template_set_id,json=templateSetId,proto3" json:"template_set_id,omitempty"`
	BoundUnnamedAppCount uint32 `protobuf:"varint,2,opt,name=bound_unnamed_app_count,json=boundUnnamedAppCount,proto3" json:"bound_unnamed_app_count,omitempty"`
	BoundNamedAppCount   uint32 `protobuf:"varint,3,opt,name=bound_named_app_count,json=boundNamedAppCount,proto3" json:"bound_named_app_count,omitempty"`
}

func (x *TemplateSetBoundCounts) Reset() {
	*x = TemplateSetBoundCounts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_template_binding_relation_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemplateSetBoundCounts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateSetBoundCounts) ProtoMessage() {}

func (x *TemplateSetBoundCounts) ProtoReflect() protoreflect.Message {
	mi := &file_template_binding_relation_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateSetBoundCounts.ProtoReflect.Descriptor instead.
func (*TemplateSetBoundCounts) Descriptor() ([]byte, []int) {
	return file_template_binding_relation_proto_rawDescGZIP(), []int{2}
}

func (x *TemplateSetBoundCounts) GetTemplateSetId() uint32 {
	if x != nil {
		return x.TemplateSetId
	}
	return 0
}

func (x *TemplateSetBoundCounts) GetBoundUnnamedAppCount() uint32 {
	if x != nil {
		return x.BoundUnnamedAppCount
	}
	return 0
}

func (x *TemplateSetBoundCounts) GetBoundNamedAppCount() uint32 {
	if x != nil {
		return x.BoundNamedAppCount
	}
	return 0
}

// TemplateBoundUnnamedAppDetail is template bound unnamed app detail.
type TemplateBoundUnnamedAppDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TemplateRevisionId   uint32 `protobuf:"varint,1,opt,name=template_revision_id,json=templateRevisionId,proto3" json:"template_revision_id,omitempty"`
	TemplateRevisionName string `protobuf:"bytes,2,opt,name=template_revision_name,json=templateRevisionName,proto3" json:"template_revision_name,omitempty"`
	AppId                uint32 `protobuf:"varint,3,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppName              string `protobuf:"bytes,4,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
}

func (x *TemplateBoundUnnamedAppDetail) Reset() {
	*x = TemplateBoundUnnamedAppDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_template_binding_relation_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemplateBoundUnnamedAppDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateBoundUnnamedAppDetail) ProtoMessage() {}

func (x *TemplateBoundUnnamedAppDetail) ProtoReflect() protoreflect.Message {
	mi := &file_template_binding_relation_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateBoundUnnamedAppDetail.ProtoReflect.Descriptor instead.
func (*TemplateBoundUnnamedAppDetail) Descriptor() ([]byte, []int) {
	return file_template_binding_relation_proto_rawDescGZIP(), []int{3}
}

func (x *TemplateBoundUnnamedAppDetail) GetTemplateRevisionId() uint32 {
	if x != nil {
		return x.TemplateRevisionId
	}
	return 0
}

func (x *TemplateBoundUnnamedAppDetail) GetTemplateRevisionName() string {
	if x != nil {
		return x.TemplateRevisionName
	}
	return ""
}

func (x *TemplateBoundUnnamedAppDetail) GetAppId() uint32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *TemplateBoundUnnamedAppDetail) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

// TemplateBoundNamedAppDetail is template bound named app detail.
type TemplateBoundNamedAppDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TemplateRevisionId   uint32 `protobuf:"varint,1,opt,name=template_revision_id,json=templateRevisionId,proto3" json:"template_revision_id,omitempty"`
	TemplateRevisionName string `protobuf:"bytes,2,opt,name=template_revision_name,json=templateRevisionName,proto3" json:"template_revision_name,omitempty"`
	AppId                uint32 `protobuf:"varint,3,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppName              string `protobuf:"bytes,4,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	ReleaseId            uint32 `protobuf:"varint,5,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"`
	ReleaseName          string `protobuf:"bytes,6,opt,name=release_name,json=releaseName,proto3" json:"release_name,omitempty"`
}

func (x *TemplateBoundNamedAppDetail) Reset() {
	*x = TemplateBoundNamedAppDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_template_binding_relation_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemplateBoundNamedAppDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateBoundNamedAppDetail) ProtoMessage() {}

func (x *TemplateBoundNamedAppDetail) ProtoReflect() protoreflect.Message {
	mi := &file_template_binding_relation_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateBoundNamedAppDetail.ProtoReflect.Descriptor instead.
func (*TemplateBoundNamedAppDetail) Descriptor() ([]byte, []int) {
	return file_template_binding_relation_proto_rawDescGZIP(), []int{4}
}

func (x *TemplateBoundNamedAppDetail) GetTemplateRevisionId() uint32 {
	if x != nil {
		return x.TemplateRevisionId
	}
	return 0
}

func (x *TemplateBoundNamedAppDetail) GetTemplateRevisionName() string {
	if x != nil {
		return x.TemplateRevisionName
	}
	return ""
}

func (x *TemplateBoundNamedAppDetail) GetAppId() uint32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *TemplateBoundNamedAppDetail) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *TemplateBoundNamedAppDetail) GetReleaseId() uint32 {
	if x != nil {
		return x.ReleaseId
	}
	return 0
}

func (x *TemplateBoundNamedAppDetail) GetReleaseName() string {
	if x != nil {
		return x.ReleaseName
	}
	return ""
}

// TemplateBoundTemplateSetDetail is template bound unnamed app detail.
type TemplateBoundTemplateSetDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TemplateSetId   uint32 `protobuf:"varint,1,opt,name=template_set_id,json=templateSetId,proto3" json:"template_set_id,omitempty"`
	TemplateSetName string `protobuf:"bytes,2,opt,name=template_set_name,json=templateSetName,proto3" json:"template_set_name,omitempty"`
}

func (x *TemplateBoundTemplateSetDetail) Reset() {
	*x = TemplateBoundTemplateSetDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_template_binding_relation_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemplateBoundTemplateSetDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateBoundTemplateSetDetail) ProtoMessage() {}

func (x *TemplateBoundTemplateSetDetail) ProtoReflect() protoreflect.Message {
	mi := &file_template_binding_relation_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateBoundTemplateSetDetail.ProtoReflect.Descriptor instead.
func (*TemplateBoundTemplateSetDetail) Descriptor() ([]byte, []int) {
	return file_template_binding_relation_proto_rawDescGZIP(), []int{5}
}

func (x *TemplateBoundTemplateSetDetail) GetTemplateSetId() uint32 {
	if x != nil {
		return x.TemplateSetId
	}
	return 0
}

func (x *TemplateBoundTemplateSetDetail) GetTemplateSetName() string {
	if x != nil {
		return x.TemplateSetName
	}
	return ""
}

// MultiTemplateBoundTemplateSetDetail is multiple templates bound unnamed app detail.
type MultiTemplateBoundTemplateSetDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TemplateId      uint32 `protobuf:"varint,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	TemplateName    string `protobuf:"bytes,2,opt,name=template_name,json=templateName,proto3" json:"template_name,omitempty"`
	TemplateSetId   uint32 `protobuf:"varint,3,opt,name=template_set_id,json=templateSetId,proto3" json:"template_set_id,omitempty"`
	TemplateSetName string `protobuf:"bytes,4,opt,name=template_set_name,json=templateSetName,proto3" json:"template_set_name,omitempty"`
}

func (x *MultiTemplateBoundTemplateSetDetail) Reset() {
	*x = MultiTemplateBoundTemplateSetDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_template_binding_relation_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiTemplateBoundTemplateSetDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiTemplateBoundTemplateSetDetail) ProtoMessage() {}

func (x *MultiTemplateBoundTemplateSetDetail) ProtoReflect() protoreflect.Message {
	mi := &file_template_binding_relation_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiTemplateBoundTemplateSetDetail.ProtoReflect.Descriptor instead.
func (*MultiTemplateBoundTemplateSetDetail) Descriptor() ([]byte, []int) {
	return file_template_binding_relation_proto_rawDescGZIP(), []int{6}
}

func (x *MultiTemplateBoundTemplateSetDetail) GetTemplateId() uint32 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

func (x *MultiTemplateBoundTemplateSetDetail) GetTemplateName() string {
	if x != nil {
		return x.TemplateName
	}
	return ""
}

func (x *MultiTemplateBoundTemplateSetDetail) GetTemplateSetId() uint32 {
	if x != nil {
		return x.TemplateSetId
	}
	return 0
}

func (x *MultiTemplateBoundTemplateSetDetail) GetTemplateSetName() string {
	if x != nil {
		return x.TemplateSetName
	}
	return ""
}

// TemplateRevisionBoundUnnamedAppDetail is template release bound unnamed app detail.
type TemplateRevisionBoundUnnamedAppDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId   uint32 `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppName string `protobuf:"bytes,2,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
}

func (x *TemplateRevisionBoundUnnamedAppDetail) Reset() {
	*x = TemplateRevisionBoundUnnamedAppDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_template_binding_relation_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemplateRevisionBoundUnnamedAppDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateRevisionBoundUnnamedAppDetail) ProtoMessage() {}

func (x *TemplateRevisionBoundUnnamedAppDetail) ProtoReflect() protoreflect.Message {
	mi := &file_template_binding_relation_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateRevisionBoundUnnamedAppDetail.ProtoReflect.Descriptor instead.
func (*TemplateRevisionBoundUnnamedAppDetail) Descriptor() ([]byte, []int) {
	return file_template_binding_relation_proto_rawDescGZIP(), []int{7}
}

func (x *TemplateRevisionBoundUnnamedAppDetail) GetAppId() uint32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *TemplateRevisionBoundUnnamedAppDetail) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

// TemplateRevisionBoundNamedAppDetail is template release bound named app detail.
type TemplateRevisionBoundNamedAppDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId       uint32 `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppName     string `protobuf:"bytes,2,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	ReleaseId   uint32 `protobuf:"varint,3,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"`
	ReleaseName string `protobuf:"bytes,4,opt,name=release_name,json=releaseName,proto3" json:"release_name,omitempty"`
}

func (x *TemplateRevisionBoundNamedAppDetail) Reset() {
	*x = TemplateRevisionBoundNamedAppDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_template_binding_relation_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemplateRevisionBoundNamedAppDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateRevisionBoundNamedAppDetail) ProtoMessage() {}

func (x *TemplateRevisionBoundNamedAppDetail) ProtoReflect() protoreflect.Message {
	mi := &file_template_binding_relation_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateRevisionBoundNamedAppDetail.ProtoReflect.Descriptor instead.
func (*TemplateRevisionBoundNamedAppDetail) Descriptor() ([]byte, []int) {
	return file_template_binding_relation_proto_rawDescGZIP(), []int{8}
}

func (x *TemplateRevisionBoundNamedAppDetail) GetAppId() uint32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *TemplateRevisionBoundNamedAppDetail) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *TemplateRevisionBoundNamedAppDetail) GetReleaseId() uint32 {
	if x != nil {
		return x.ReleaseId
	}
	return 0
}

func (x *TemplateRevisionBoundNamedAppDetail) GetReleaseName() string {
	if x != nil {
		return x.ReleaseName
	}
	return ""
}

// TemplateSetBoundUnnamedAppDetail is template set bound unnamed app detail.
type TemplateSetBoundUnnamedAppDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId   uint32 `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppName string `protobuf:"bytes,2,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
}

func (x *TemplateSetBoundUnnamedAppDetail) Reset() {
	*x = TemplateSetBoundUnnamedAppDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_template_binding_relation_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemplateSetBoundUnnamedAppDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateSetBoundUnnamedAppDetail) ProtoMessage() {}

func (x *TemplateSetBoundUnnamedAppDetail) ProtoReflect() protoreflect.Message {
	mi := &file_template_binding_relation_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateSetBoundUnnamedAppDetail.ProtoReflect.Descriptor instead.
func (*TemplateSetBoundUnnamedAppDetail) Descriptor() ([]byte, []int) {
	return file_template_binding_relation_proto_rawDescGZIP(), []int{9}
}

func (x *TemplateSetBoundUnnamedAppDetail) GetAppId() uint32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *TemplateSetBoundUnnamedAppDetail) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

// MultiTemplateSetBoundUnnamedAppDetail is template set bound unnamed app detail.
type MultiTemplateSetBoundUnnamedAppDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TemplateSetId   uint32 `protobuf:"varint,1,opt,name=template_set_id,json=templateSetId,proto3" json:"template_set_id,omitempty"`
	TemplateSetName string `protobuf:"bytes,2,opt,name=template_set_name,json=templateSetName,proto3" json:"template_set_name,omitempty"`
	AppId           uint32 `protobuf:"varint,3,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppName         string `protobuf:"bytes,4,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
}

func (x *MultiTemplateSetBoundUnnamedAppDetail) Reset() {
	*x = MultiTemplateSetBoundUnnamedAppDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_template_binding_relation_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiTemplateSetBoundUnnamedAppDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiTemplateSetBoundUnnamedAppDetail) ProtoMessage() {}

func (x *MultiTemplateSetBoundUnnamedAppDetail) ProtoReflect() protoreflect.Message {
	mi := &file_template_binding_relation_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiTemplateSetBoundUnnamedAppDetail.ProtoReflect.Descriptor instead.
func (*MultiTemplateSetBoundUnnamedAppDetail) Descriptor() ([]byte, []int) {
	return file_template_binding_relation_proto_rawDescGZIP(), []int{10}
}

func (x *MultiTemplateSetBoundUnnamedAppDetail) GetTemplateSetId() uint32 {
	if x != nil {
		return x.TemplateSetId
	}
	return 0
}

func (x *MultiTemplateSetBoundUnnamedAppDetail) GetTemplateSetName() string {
	if x != nil {
		return x.TemplateSetName
	}
	return ""
}

func (x *MultiTemplateSetBoundUnnamedAppDetail) GetAppId() uint32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *MultiTemplateSetBoundUnnamedAppDetail) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

// TemplateSetBoundUnnamedAppDetail is template set bound named app detail.
type TemplateSetBoundNamedAppDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId       uint32 `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppName     string `protobuf:"bytes,2,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	ReleaseId   uint32 `protobuf:"varint,3,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"`
	ReleaseName string `protobuf:"bytes,4,opt,name=release_name,json=releaseName,proto3" json:"release_name,omitempty"`
}

func (x *TemplateSetBoundNamedAppDetail) Reset() {
	*x = TemplateSetBoundNamedAppDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_template_binding_relation_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemplateSetBoundNamedAppDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateSetBoundNamedAppDetail) ProtoMessage() {}

func (x *TemplateSetBoundNamedAppDetail) ProtoReflect() protoreflect.Message {
	mi := &file_template_binding_relation_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateSetBoundNamedAppDetail.ProtoReflect.Descriptor instead.
func (*TemplateSetBoundNamedAppDetail) Descriptor() ([]byte, []int) {
	return file_template_binding_relation_proto_rawDescGZIP(), []int{11}
}

func (x *TemplateSetBoundNamedAppDetail) GetAppId() uint32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *TemplateSetBoundNamedAppDetail) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *TemplateSetBoundNamedAppDetail) GetReleaseId() uint32 {
	if x != nil {
		return x.ReleaseId
	}
	return 0
}

func (x *TemplateSetBoundNamedAppDetail) GetReleaseName() string {
	if x != nil {
		return x.ReleaseName
	}
	return ""
}

// LatestTemplateBoundUnnamedAppDetail is the latest template bound unnamed app detail.
type LatestTemplateBoundUnnamedAppDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TemplateSetId   uint32 `protobuf:"varint,1,opt,name=template_set_id,json=templateSetId,proto3" json:"template_set_id,omitempty"`
	TemplateSetName string `protobuf:"bytes,2,opt,name=template_set_name,json=templateSetName,proto3" json:"template_set_name,omitempty"`
	AppId           uint32 `protobuf:"varint,3,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppName         string `protobuf:"bytes,4,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
}

func (x *LatestTemplateBoundUnnamedAppDetail) Reset() {
	*x = LatestTemplateBoundUnnamedAppDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_template_binding_relation_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LatestTemplateBoundUnnamedAppDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatestTemplateBoundUnnamedAppDetail) ProtoMessage() {}

func (x *LatestTemplateBoundUnnamedAppDetail) ProtoReflect() protoreflect.Message {
	mi := &file_template_binding_relation_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatestTemplateBoundUnnamedAppDetail.ProtoReflect.Descriptor instead.
func (*LatestTemplateBoundUnnamedAppDetail) Descriptor() ([]byte, []int) {
	return file_template_binding_relation_proto_rawDescGZIP(), []int{12}
}

func (x *LatestTemplateBoundUnnamedAppDetail) GetTemplateSetId() uint32 {
	if x != nil {
		return x.TemplateSetId
	}
	return 0
}

func (x *LatestTemplateBoundUnnamedAppDetail) GetTemplateSetName() string {
	if x != nil {
		return x.TemplateSetName
	}
	return ""
}

func (x *LatestTemplateBoundUnnamedAppDetail) GetAppId() uint32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *LatestTemplateBoundUnnamedAppDetail) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

var File_template_binding_relation_proto protoreflect.FileDescriptor

var file_template_binding_relation_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x5f, 0x62, 0x69, 0x6e, 0x64, 0x69,
	0x6e, 0x67, 0x5f, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x70, 0x62, 0x74, 0x62, 0x72, 0x22, 0xd9, 0x01, 0x0a, 0x13, 0x54, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x73,
	0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49,
	0x64, 0x12, 0x35, 0x0a, 0x17, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x75, 0x6e, 0x6e, 0x61, 0x6d,
	0x65, 0x64, 0x5f, 0x61, 0x70, 0x70, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x14, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x55, 0x6e, 0x6e, 0x61, 0x6d, 0x65, 0x64,
	0x41, 0x70, 0x70, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x31, 0x0a, 0x15, 0x62, 0x6f, 0x75, 0x6e,
	0x64, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x64, 0x5f, 0x61, 0x70, 0x70, 0x5f, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x12, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x4e, 0x61,
	0x6d, 0x65, 0x64, 0x41, 0x70, 0x70, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x37, 0x0a, 0x18, 0x62,
	0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x65,
	0x74, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x15, 0x62,
	0x6f, 0x75, 0x6e, 0x64, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x53, 0x65, 0x74, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x22, 0xb9, 0x01, 0x0a, 0x1b, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x73, 0x12, 0x30, 0x0a, 0x14, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x5f, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x12, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x76, 0x69,
	0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x35, 0x0a, 0x17, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x5f,
	0x75, 0x6e, 0x6e, 0x61, 0x6d, 0x65, 0x64, 0x5f, 0x61, 0x70, 0x70, 0x5f, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x14, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x55, 0x6e,
	0x6e, 0x61, 0x6d, 0x65, 0x64, 0x41, 0x70, 0x70, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x31, 0x0a,
	0x15, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x64, 0x5f, 0x61, 0x70, 0x70,
	0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x12, 0x62, 0x6f,
	0x75, 0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x64, 0x41, 0x70, 0x70, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0xaa, 0x01, 0x0a, 0x16, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x53, 0x65, 0x74,
	0x42, 0x6f, 0x75, 0x6e, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x12, 0x26, 0x0a, 0x0f, 0x74,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x53, 0x65,
	0x74, 0x49, 0x64, 0x12, 0x35, 0x0a, 0x17, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x75, 0x6e, 0x6e,
	0x61, 0x6d, 0x65, 0x64, 0x5f, 0x61, 0x70, 0x70, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x14, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x55, 0x6e, 0x6e, 0x61, 0x6d,
	0x65, 0x64, 0x41, 0x70, 0x70, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x31, 0x0a, 0x15, 0x62, 0x6f,
	0x75, 0x6e, 0x64, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x64, 0x5f, 0x61, 0x70, 0x70, 0x5f, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x12, 0x62, 0x6f, 0x75, 0x6e, 0x64,
	0x4e, 0x61, 0x6d, 0x65, 0x64, 0x41, 0x70, 0x70, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0xb9, 0x01,
	0x0a, 0x1d, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x55,
	0x6e, 0x6e, 0x61, 0x6d, 0x65, 0x64, 0x41, 0x70, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12,
	0x30, 0x0a, 0x14, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x76, 0x69,
	0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x12, 0x74,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x12, 0x34, 0x0a, 0x16, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x65,
	0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x14, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x76, 0x69, 0x73,
	0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x19,
	0x0a, 0x08, 0x61, 0x70, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xf9, 0x01, 0x0a, 0x1b, 0x54, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x64,
	0x41, 0x70, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x30, 0x0a, 0x14, 0x74, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x12, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x34, 0x0a, 0x16, 0x74,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x74, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x70, 0x70, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x70, 0x70, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65,
	0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x74, 0x0a, 0x1e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74,
	0x65, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x53, 0x65,
	0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x26, 0x0a, 0x0f, 0x74, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x5f, 0x73, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0d, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x53, 0x65, 0x74, 0x49, 0x64, 0x12,
	0x2a, 0x0a, 0x11, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x65, 0x74, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x74, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x53, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xbf, 0x01, 0x0a, 0x23,
	0x4d, 0x75, 0x6c, 0x74, 0x69, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x75,
	0x6e, 0x64, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x53, 0x65, 0x74, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x74, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0d, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x53, 0x65, 0x74, 0x49,
	0x64, 0x12, 0x2a, 0x0a, 0x11, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x65,
	0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x74, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x53, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x59, 0x0a,
	0x25, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f,
	0x6e, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x55, 0x6e, 0x6e, 0x61, 0x6d, 0x65, 0x64, 0x41, 0x70, 0x70,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x19, 0x0a,
	0x08, 0x61, 0x70, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x99, 0x01, 0x0a, 0x23, 0x54, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x6f, 0x75,
	0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x64, 0x41, 0x70, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x70, 0x70, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x70, 0x70, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x49,
	0x64, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x22, 0x54, 0x0a, 0x20, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x53, 0x65, 0x74, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x55, 0x6e, 0x6e, 0x61, 0x6d, 0x65, 0x64, 0x41,
	0x70, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12,
	0x19, 0x0a, 0x08, 0x61, 0x70, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x61, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xad, 0x01, 0x0a, 0x25, 0x4d,
	0x75, 0x6c, 0x74, 0x69, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x53, 0x65, 0x74, 0x42,
	0x6f, 0x75, 0x6e, 0x64, 0x55, 0x6e, 0x6e, 0x61, 0x6d, 0x65, 0x64, 0x41, 0x70, 0x70, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x12, 0x26, 0x0a, 0x0f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x5f, 0x73, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x74,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x53, 0x65, 0x74, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x11,
	0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x65, 0x74, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74,
	0x65, 0x53, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12,
	0x19, 0x0a, 0x08, 0x61, 0x70, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x61, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x94, 0x01, 0x0a, 0x1e, 0x54,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x53, 0x65, 0x74, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x4e,
	0x61, 0x6d, 0x65, 0x64, 0x41, 0x70, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x15, 0x0a,
	0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x61,
	0x70, 0x70, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x70, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x09, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x49, 0x64, 0x12, 0x21,
	0x0a, 0x0c, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x22, 0xab, 0x01, 0x0a, 0x23, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x54, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x55, 0x6e, 0x6e, 0x61, 0x6d, 0x65, 0x64,
	0x41, 0x70, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x26, 0x0a, 0x0f, 0x74, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0d, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x53, 0x65, 0x74, 0x49,
	0x64, 0x12, 0x2a, 0x0a, 0x11, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x65,
	0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x74, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x53, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x15, 0x0a,
	0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x61,
	0x70, 0x70, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x70, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x42,
	0x6b, 0x5a, 0x69, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x54, 0x65,
	0x6e, 0x63, 0x65, 0x6e, 0x74, 0x42, 0x6c, 0x75, 0x65, 0x6b, 0x69, 0x6e, 0x67, 0x2f, 0x62, 0x6b,
	0x2d, 0x62, 0x63, 0x73, 0x2f, 0x62, 0x63, 0x73, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x2f, 0x62, 0x63, 0x73, 0x2d, 0x62, 0x73, 0x63, 0x70, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x74, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x2d, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x2d, 0x72, 0x65,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x3b, 0x70, 0x62, 0x74, 0x62, 0x72, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_template_binding_relation_proto_rawDescOnce sync.Once
	file_template_binding_relation_proto_rawDescData = file_template_binding_relation_proto_rawDesc
)

func file_template_binding_relation_proto_rawDescGZIP() []byte {
	file_template_binding_relation_proto_rawDescOnce.Do(func() {
		file_template_binding_relation_proto_rawDescData = protoimpl.X.CompressGZIP(file_template_binding_relation_proto_rawDescData)
	})
	return file_template_binding_relation_proto_rawDescData
}

var file_template_binding_relation_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_template_binding_relation_proto_goTypes = []interface{}{
	(*TemplateBoundCounts)(nil),                   // 0: pbtbr.TemplateBoundCounts
	(*TemplateRevisionBoundCounts)(nil),           // 1: pbtbr.TemplateRevisionBoundCounts
	(*TemplateSetBoundCounts)(nil),                // 2: pbtbr.TemplateSetBoundCounts
	(*TemplateBoundUnnamedAppDetail)(nil),         // 3: pbtbr.TemplateBoundUnnamedAppDetail
	(*TemplateBoundNamedAppDetail)(nil),           // 4: pbtbr.TemplateBoundNamedAppDetail
	(*TemplateBoundTemplateSetDetail)(nil),        // 5: pbtbr.TemplateBoundTemplateSetDetail
	(*MultiTemplateBoundTemplateSetDetail)(nil),   // 6: pbtbr.MultiTemplateBoundTemplateSetDetail
	(*TemplateRevisionBoundUnnamedAppDetail)(nil), // 7: pbtbr.TemplateRevisionBoundUnnamedAppDetail
	(*TemplateRevisionBoundNamedAppDetail)(nil),   // 8: pbtbr.TemplateRevisionBoundNamedAppDetail
	(*TemplateSetBoundUnnamedAppDetail)(nil),      // 9: pbtbr.TemplateSetBoundUnnamedAppDetail
	(*MultiTemplateSetBoundUnnamedAppDetail)(nil), // 10: pbtbr.MultiTemplateSetBoundUnnamedAppDetail
	(*TemplateSetBoundNamedAppDetail)(nil),        // 11: pbtbr.TemplateSetBoundNamedAppDetail
	(*LatestTemplateBoundUnnamedAppDetail)(nil),   // 12: pbtbr.LatestTemplateBoundUnnamedAppDetail
}
var file_template_binding_relation_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_template_binding_relation_proto_init() }
func file_template_binding_relation_proto_init() {
	if File_template_binding_relation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_template_binding_relation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemplateBoundCounts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_template_binding_relation_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemplateRevisionBoundCounts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_template_binding_relation_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemplateSetBoundCounts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_template_binding_relation_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemplateBoundUnnamedAppDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_template_binding_relation_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemplateBoundNamedAppDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_template_binding_relation_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemplateBoundTemplateSetDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_template_binding_relation_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiTemplateBoundTemplateSetDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_template_binding_relation_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemplateRevisionBoundUnnamedAppDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_template_binding_relation_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemplateRevisionBoundNamedAppDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_template_binding_relation_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemplateSetBoundUnnamedAppDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_template_binding_relation_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiTemplateSetBoundUnnamedAppDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_template_binding_relation_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemplateSetBoundNamedAppDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_template_binding_relation_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LatestTemplateBoundUnnamedAppDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_template_binding_relation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_template_binding_relation_proto_goTypes,
		DependencyIndexes: file_template_binding_relation_proto_depIdxs,
		MessageInfos:      file_template_binding_relation_proto_msgTypes,
	}.Build()
	File_template_binding_relation_proto = out.File
	file_template_binding_relation_proto_rawDesc = nil
	file_template_binding_relation_proto_goTypes = nil
	file_template_binding_relation_proto_depIdxs = nil
}
